// CSV Exercise Pool Batch 5 — exercises 4001–5000
export const CSV_EXERCISES_BATCH5 = [
  { name: 'Lane Shuffle Defensive Drill', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'Defensive Slide (Full Court)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Closeout Drill', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Drop Step Footwork', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'Triple Threat to Drive', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'Jab Step Series', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Beginner' },
  { name: 'Rocker Step', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Beginner' },
  { name: 'Euro Step Jump', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Advanced' },
  { name: 'Spin Move Footwork', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'Crossover Step Cutback', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'Retreat Dribble Simulation', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Zigzag Sprint (Basketball Court)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Box-Out Footwork', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Beginner' },
  { name: 'Post Feed Footwork', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'Rim Jump (Max Vertical)', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Advanced' },
  { name: 'Lane Agility Drill (NBA)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Shuttle Run (28ft)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Three-Quarter Court Sprint', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'On-Ball Defensive Footwork', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'Baseline Sprint to Closeout', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Cruyff Turn Footwork', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'Stop-and-Go Sprint', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Lateral Shuffle to Sprint', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Diagonal Run Pattern', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Curved Sprint (Arc Run)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Instep Kick Simulation (No Ball)', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Beginner' },
  { name: 'Volley Strike Motion', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Intermediate' },
  { name: 'Hip Rotation Kick Load', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Goalkeeper Side Dive', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Goalkeeper Shuffle to Dive', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Explosive Start from Set Position', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Soccer Agility Box Drill', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'W-Run Drill', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Compass Run', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Pressing Trigger Sprint', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Covering Sprint (Diagonal Back)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Headed Ball Jump (Sim)', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Intermediate' },
  { name: 'Hip Check Balance Drill', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Intermediate' },
  { name: 'Fake and Accelerate Drill', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Advanced' },
  { name: 'Multi-Directional Soccer Sprint', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Split Step Reactive', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Beginner' },
  { name: 'Wide Step to Recovery', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Forehand Swing Simulation', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Backhand Swing Simulation', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Overhead Smash Simulation', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Net Rush Sprint', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Baseline Shuffle Rally Sim', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Cross-Court Sprint Recovery', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'First Step Reaction Drill', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Intermediate' },
  { name: 'Low Volley Hip Hinge', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Beginner' },
  { name: 'Serve Load and Drive (Sim)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Drop Shot Recovery Sprint', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Lob Chase Sprint', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Deuce-Side to Ad-Side Shuffle', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Tennis Agility Star Drill', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Front Kick Chamber', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Beginner' },
  { name: 'Roundhouse Kick Chamber', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Side Kick Chamber', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Back Kick Chamber', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Axe Kick', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Advanced' },
  { name: 'Hook Kick', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Advanced' },
  { name: 'Jump Front Kick', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Advanced' },
  { name: 'Jump Roundhouse Kick', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Advanced' },
  { name: 'Spinning Back Kick', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Advanced' },
  { name: 'Spinning Heel Kick', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Advanced' },
  { name: 'Jab-Cross Combo Shadow', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Jab-Cross-Hook Shadow', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Jab-Cross-Hook-Uppercut Shadow', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Overhand Right Shadow', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Body Jab Shadow', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Defensive Slip Left-Right', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Beginner' },
  { name: 'Defensive Roll Under', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'Peek-a-Boo Guard Footwork', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'Muay Thai Teep (Push Kick Sim)', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Intermediate' },
  { name: 'Muay Thai Knee Strike (Clinch Sim)', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Advanced' },
  { name: 'Golf Backswing Rotation', category: 'bodyweight', subCategory: 'Thoracic Spine', difficulty: 'Beginner' },
  { name: 'Golf Downswing Hip Shift', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Golf Follow-Through Rotation', category: 'bodyweight', subCategory: 'Obliques', difficulty: 'Beginner' },
  { name: 'Hip Dissociation Drill (Golf)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Pelvic Tilt to Rotation', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Lateral Sway Correction Drill', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Early Extension Fix Drill', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Thoracic Rotation Golf Prep', category: 'bodyweight', subCategory: 'Thoracic Spine', difficulty: 'Beginner' },
  { name: 'Wrist Hinge Drill', category: 'bodyweight', subCategory: 'Forearms', difficulty: 'Beginner' },
  { name: 'Trail Side Hip Turn', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Rotary Breathing Drill (Dry)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Freestyle Pull Pattern (Dry)', category: 'bodyweight', subCategory: 'Back', difficulty: 'Beginner' },
  { name: 'Butterfly Undulation (Dry)', category: 'bodyweight', subCategory: 'Lower Back', difficulty: 'Intermediate' },
  { name: 'Backstroke Arm Circle (Dry)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Breaststroke Arm Pull (Dry)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Beginner' },
  { name: 'Flip Turn Tuck Practice', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Start Block Dive Prep', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Underwater Dolphin Kick (Dry)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Body Roll Drill (Side Balance)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Catch Position Shoulder Drill', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Zumba Basic Merengue Step', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Beginner' },
  { name: 'Zumba Salsa Basic', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Beginner' },
  { name: 'Zumba Cumbia Step', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Beginner' },
  { name: 'Zumba Reggaeton Hip Drop', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Aerobics Step Touch', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Beginner' },
  { name: 'Aerobics Grapevine', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Beginner' },
  { name: 'Aerobics Knee Lift March', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Beginner' },
  { name: 'Hip Hop Bounce Step', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Beginner' },
  { name: 'Barre Tendu (Side)', category: 'bodyweight', subCategory: 'Inner Thighs', difficulty: 'Beginner' },
  { name: 'Barre Tendu (Front)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Barre Degage', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Barre Grand Battement', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Intermediate' },
  { name: 'Barre Releve Passe', category: 'bodyweight', subCategory: 'Calves', difficulty: 'Intermediate' },
  { name: 'Ballet First Position Plie', category: 'bodyweight', subCategory: 'Inner Thighs', difficulty: 'Beginner' },
  { name: 'Ballet Second Position Grand Plie', category: 'bodyweight', subCategory: 'Inner Thighs', difficulty: 'Intermediate' },
  { name: 'Sit to Stand (Chair)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Sit to Stand with Arms Crossed', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Standing Marching in Place', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Beginner' },
  { name: 'Step Touch Side to Side', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Beginner' },
  { name: 'Heel-to-Toe Walk', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Beginner' },
  { name: 'Side Step with Arm Swing', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Beginner' },
  { name: 'Wall Push-Up (Senior Version)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Beginner' },
  { name: 'Seated Leg Extension', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Seated Ankle Pump', category: 'bodyweight', subCategory: 'Calves', difficulty: 'Beginner' },
  { name: 'Seated Hip March', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Beginner' },
  { name: 'Seated Shoulder Roll', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Seated Neck Tilt', category: 'bodyweight', subCategory: 'Neck', difficulty: 'Beginner' },
  { name: 'Tightrope Walk (Wall Support)', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Beginner' },
  { name: 'Single-Leg Stand (Fingertip Wall)', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Beginner' },
  { name: 'Tai Chi Basic Ward-Off', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Tai Chi Brush Knee', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Tai Chi Wave Hands Like Clouds', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Tai Chi Grasp the Sparrow\'s Tail', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Pelvic Floor Kegel Contraction', category: 'bodyweight', subCategory: 'Pelvic Floor', difficulty: 'Beginner' },
  { name: 'Pelvic Floor Reverse Kegel', category: 'bodyweight', subCategory: 'Pelvic Floor', difficulty: 'Beginner' },
  { name: 'Diaphragm Kegel Coordination', category: 'bodyweight', subCategory: 'Pelvic Floor', difficulty: 'Beginner' },
  { name: 'Prenatal Cat-Cow Stretch', category: 'bodyweight', subCategory: 'Lower Back', difficulty: 'Beginner' },
  { name: 'Prenatal Side-Lying Leg Raise', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Prenatal Wall Squat', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Postnatal Glute Bridge (Pelvic Floor)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Postnatal Bird Dog (Gentle)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Diastasis Recti Breath + Brace', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Postnatal Heel Slide', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Air Squat (Crossfit Standard)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Pistol Squat (Crossfit)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Burpee Box Jump Over', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Deep Squat FMS Pattern', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Hurdle Step FMS Pattern', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Intermediate' },
  { name: 'Inline Lunge FMS Pattern', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Shoulder Mobility Screen', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Active Straight-Leg Raise', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Beginner' },
  { name: 'Trunk Stability Push-Up', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Rotary Stability Pattern', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Y-Balance Reach Composite', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Intermediate' },
  { name: 'Block Start Acceleration (Sim)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Acceleration Phase Sprint (20m)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Maximum Velocity Sprint (30m)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Deceleration Run (15m)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Flying 30m Sprint', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Long Jump Approach Run', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Advanced' },
  { name: 'Triple Jump Hop Step Jump', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Advanced' },
  { name: 'High Jump Approach (Fosbury)', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Advanced' },
  { name: 'Shot Put Footwork (Glide)', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'Discus Rotation Footwork', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Advanced' },
  { name: 'Hammer Throw Entry Footwork', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Advanced' },
  { name: 'Javelin Crossover Steps', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'Hurdle Trail Leg Drill', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'Hurdle Lead Leg Drill', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: '400m Pace Training Run', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Tabata Air Squat (20s/10s x8)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Tabata Push-Up (20s/10s x8)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Tabata Burpee (20s/10s x8)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Tabata Mountain Climber', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'AMRAP 10min: Squat + Push-Up', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: '20-10 Interval Sprint', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: '30-30 Interval Run', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: '60-60 Interval Run', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: '10-20-30 Running Protocol', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Fartlek 5-Pace Run', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Norwegian 4x4 Interval (Sim)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Beep Test Progression', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Cooper 12-Minute Run Test', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: '5K Pacing Run', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Toe Spread and Squeeze', category: 'bodyweight', subCategory: 'Foot Intrinsics', difficulty: 'Beginner' },
  { name: 'Short Foot Exercise (Arch Lift)', category: 'bodyweight', subCategory: 'Foot Intrinsics', difficulty: 'Beginner' },
  { name: 'Heel Walk (10m)', category: 'bodyweight', subCategory: 'Tibialis Anterior', difficulty: 'Beginner' },
  { name: 'Toe Walk (10m)', category: 'bodyweight', subCategory: 'Calves', difficulty: 'Beginner' },
  { name: 'Inside Edge Walk', category: 'bodyweight', subCategory: 'Peroneal', difficulty: 'Beginner' },
  { name: 'Outside Edge Walk', category: 'bodyweight', subCategory: 'Tibialis Posterior', difficulty: 'Beginner' },
  { name: 'Barefoot Single-Leg Balance', category: 'bodyweight', subCategory: 'Foot Intrinsics', difficulty: 'Intermediate' },
  { name: 'Intrinsic Foot Load Progression', category: 'bodyweight', subCategory: 'Foot Intrinsics', difficulty: 'Intermediate' },
  { name: 'Monkey Bar Traverse (Full)', category: 'bodyweight', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Pole Climb (Full)', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Net Climb (Cargo Net)', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Tire Crawl Through', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Wall Climb (Obstacle)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Low Crawl (Under Net)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'High Crawl (Over Net)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Balance Beam Full Length', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Intermediate' },
  { name: 'Mud Run Simulation Circuit', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Quadruped Hip Circle (Full ROM)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Prone Hip ER Lift', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Prone Hip IR Lift', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Supine Clam (Full ROM)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Standing Hip Hike (Trendelenburg)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Glute Squeeze to Posterior Pelvic Tilt', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Mini Band Squat Walkout', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Mini Band Lateral Monster Walk', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Mini Band Pull-Apart (Thighs)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Seated Hip Abduction (No Weight)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Standing Hip Abduction Pulse', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Lying Frog Pump', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Coin Flip Balance Catch', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'Clap Behind Back Jump', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Advanced' },
  { name: 'Double Clap Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Triple Clap Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Elbow Lever to Planche Transition', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Freestanding Handstand Pirouette', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Handstand Walk 10m', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Handstand Press from Standing', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'One-Arm Handstand (Wall Assisted)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Neck Isometric Front (Hand Press)', category: 'bodyweight', subCategory: 'Neck', difficulty: 'Beginner' },
  { name: 'Neck Isometric Back (Hand Press)', category: 'bodyweight', subCategory: 'Neck', difficulty: 'Beginner' },
  { name: 'Neck Isometric Side (Hand Press)', category: 'bodyweight', subCategory: 'Neck', difficulty: 'Beginner' },
  { name: 'Suboccipital Release', category: 'bodyweight', subCategory: 'Neck', difficulty: 'Beginner' },
  { name: 'Cervical Retraction Drill', category: 'bodyweight', subCategory: 'Neck', difficulty: 'Beginner' },
  { name: 'Eye Convergence Drill', category: 'bodyweight', subCategory: 'Eyes', difficulty: 'Beginner' },
  { name: 'Eye Divergence Drill', category: 'bodyweight', subCategory: 'Eyes', difficulty: 'Beginner' },
  { name: 'Eye Saccade Drill (Rapid Gaze)', category: 'bodyweight', subCategory: 'Eyes', difficulty: 'Beginner' },
  { name: 'Vestibular Head-Tilt Balance', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Intermediate' },
  { name: 'Gaze Stabilization Squat', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Intermediate' },
  { name: 'Pull-Up Max Set Test', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Push-Up Max Set Test (Timed 1min)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Squat Max Set Test (Timed 1min)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Pull-Up Negative Only Set', category: 'bodyweight', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Wall Handstand Kick-Up Test', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Planche Lean ISO Hold (Max Time)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Front Lever Tuck ISO Hold (Max)', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'L-Sit ISO Hold (Max Time)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Dragon Flag ISO Hold', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Hollow Body ISO Hold (Max Time)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Arch Body ISO Hold (Max Time)', category: 'bodyweight', subCategory: 'Lower Back', difficulty: 'Beginner' },
  { name: 'Reverse Plank ISO Hold (Max)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Side Plank ISO Hold (Max Each)', category: 'bodyweight', subCategory: 'Obliques', difficulty: 'Intermediate' },
  { name: 'Squat ISO Hold (Bottom 90s)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Split ISO Hold (60s)', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Advanced' },
  { name: 'Bridge ISO Hold (60s)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Crow Pose ISO Hold', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Headstand ISO Hold (60s)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Forearm Stand ISO Hold (60s)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Bear Crawl (100m)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Crab Walk (50m)', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Duck Walk (50m)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Inch Worm (50m)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Broad Jump (10 Continuous)', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Advanced' },
  { name: 'Power Clean for Speed (60%)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Hip Thrust Heavy (Max Effort)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Advanced' },
  { name: 'Nordic Hamstring Loaded Eccentric', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Advanced' },
  { name: 'Sled Push Max Effort (Short)', category: 'weighted', subCategory: 'Legs', difficulty: 'Advanced' },
  { name: 'Barbell Complex Football Specific', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Overhead Tricep Throw (Med Ball)', category: 'weighted', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Chest Pass Power (Med Ball)', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Barbell Thruster (CrossFit Standard)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Dumbbell Snatch (CrossFit)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Kettlebell Swing (American)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Kettlebell Swing (Russian)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Barbell Power Clean (CrossFit)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Barbell Hang Power Clean', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Dumbbell Devil Press (CrossFit)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Dumbbell Man Maker (CrossFit)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Ground-to-Overhead (Dumbbell)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Ground-to-Overhead (Barbell)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Double Dumbbell Strict Press', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Double Dumbbell Push Press', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Double Dumbbell Front Squat', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Cable Lateral Raise (Elbow at 90°)', category: 'weighted', subCategory: 'Lateral Deltoid', difficulty: 'Intermediate' },
  { name: 'Cable Bent-Over Rear Delt Fly', category: 'weighted', subCategory: 'Rear Deltoid', difficulty: 'Intermediate' },
  { name: 'Dumbbell Lateral Raise ISO Hold Top', category: 'weighted', subCategory: 'Lateral Deltoid', difficulty: 'Intermediate' },
  { name: 'Cable Curl (Max Stretch Low Pulley)', category: 'weighted', subCategory: 'Biceps', difficulty: 'Advanced' },
  { name: 'Cable Curl (Peak Contraction High)', category: 'weighted', subCategory: 'Biceps', difficulty: 'Intermediate' },
  { name: 'Barbell Curl (Strict Scott Bench)', category: 'weighted', subCategory: 'Biceps', difficulty: 'Intermediate' },
  { name: 'Cable Tricep Pushdown (Elbow Forward)', category: 'weighted', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Cable Tricep Extension (Elbows Back)', category: 'weighted', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Machine Pec Dec (Wide ROM)', category: 'weighted', subCategory: 'Chest', difficulty: 'Beginner' },
  { name: 'Machine Pec Dec (Narrow ROM)', category: 'weighted', subCategory: 'Inner Chest', difficulty: 'Intermediate' },
  { name: 'Machine Pec Dec (Loaded Stretch)', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Dumbbell Row (Elbow to Hip)', category: 'weighted', subCategory: 'Lats', difficulty: 'Intermediate' },
  { name: 'Dumbbell Row (Elbow to Ceiling)', category: 'weighted', subCategory: 'Upper Back', difficulty: 'Intermediate' },
  { name: 'Machine Chest Press (Slow Eccentric)', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Machine Incline Chest (Wide Grip)', category: 'weighted', subCategory: 'Upper Chest', difficulty: 'Intermediate' },
  { name: 'Machine Shoulder Press (Narrow)', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Machine Shoulder Press (Wide)', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Barbell Curl (Slow 4s Eccentric)', category: 'weighted', subCategory: 'Biceps', difficulty: 'Intermediate' },
  { name: 'Dumbbell Skull Crusher (Slow 4s)', category: 'weighted', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Dumbbell Fly (Deep Loaded Stretch)', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Barbell Row (Heavy Cheat Style)', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Barbell Squat (Texas Method Intensity)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Squat (Texas Method Volume)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Barbell Deadlift (Texas Method)', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Barbell Squat (Starting Strength 3x5)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Barbell Press (Starting Strength)', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Barbell Power Clean (Starting Strength)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Barbell Squat (Juggernaut Method)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Barbell Deadlift (Cube Method)', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Barbell Squat (Smolov Base Cycle)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Complex (Cosgrove)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Barbell Complex (Quattro Stagioni)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Barbell Ladder (1-2-3 Rung)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Leg Press Machine Pyramid', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Leg Curl Machine Pyramid', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Leg Extension Machine Pyramid', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Full Machine Circuit (10 Stations)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Machine Superset Upper Body', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Machine Superset Lower Body', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Dumbbell Full Body A (3 exercises)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Dumbbell Full Body B (3 exercises)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Dumbbell Push Circuit', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Dumbbell Pull Circuit', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Dumbbell Leg Circuit', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Dumbbell Shoulder Circuit', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Dumbbell Arm Superset (Bi + Tri)', category: 'weighted', subCategory: 'Biceps', difficulty: 'Beginner' },
  { name: 'Dumbbell Core Circuit (4 Moves)', category: 'weighted', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Dumbbell Romanian Deadlift + Row', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Dumbbell Squat + Curl + Press', category: 'weighted', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Dumbbell Lunge + Lateral Raise', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Dumbbell RDL + Kickback', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Dumbbell Hip Thrust + Fly', category: 'weighted', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Dumbbell Reverse Lunge + Row', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Dumbbell Squat + Rear Delt Fly', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Dumbbell Squat Jump + Press', category: 'weighted', subCategory: 'Plyometrics', difficulty: 'Intermediate' },
  { name: 'Dumbbell Lateral Lunge + Curl', category: 'weighted', subCategory: 'Inner Thighs', difficulty: 'Intermediate' },
  { name: 'Dumbbell Overhead Lunge + Extension', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Rowing Machine Stroke Rate 18-20', category: 'weighted', subCategory: 'Cardio', difficulty: 'Beginner' },
  { name: 'Rowing Machine Stroke Rate 24', category: 'weighted', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Rowing Machine 500m Sprint', category: 'weighted', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Rowing Machine 2000m Time Trial', category: 'weighted', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Rowing Machine Tabata Intervals', category: 'weighted', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Spin Bike Flat Road Cadence', category: 'weighted', subCategory: 'Cardio', difficulty: 'Beginner' },
  { name: 'Spin Bike Hill Climb (High Resist)', category: 'weighted', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Spin Bike Sprint Interval', category: 'weighted', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Spin Bike Tabata Cycling', category: 'weighted', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Spin Bike HIIT (20s on 10s off)', category: 'weighted', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Band Squat (Heavy Loop)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Band Deadlift (Heavy Loop)', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Band Romanian Deadlift (Looped)', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Band Hip Thrust (Looped Under Feet)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Band Pull-Apart (Horizontal)', category: 'weighted', subCategory: 'Rear Deltoid', difficulty: 'Beginner' },
  { name: 'Band Overhead Press (Single Arm)', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Band Lat Pulldown (Overhead Anchor)', category: 'weighted', subCategory: 'Lats', difficulty: 'Intermediate' },
  { name: 'Band Row (Behind Door Anchor)', category: 'weighted', subCategory: 'Back', difficulty: 'Beginner' },
  { name: 'Band Chest Fly (Behind Anchor)', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Band Tricep Extension (Overhead)', category: 'weighted', subCategory: 'Triceps', difficulty: 'Beginner' },
  { name: 'Band Bicep Curl (Double)', category: 'weighted', subCategory: 'Biceps', difficulty: 'Beginner' },
  { name: 'Band Lateral Walk Heavy', category: 'weighted', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Band Glute Kickback (Quad)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Band Clamshell (Heavy)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Band Romanian Deadlift + Row', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Band Squat + Press', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Band Deadlift + Curl', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Band Full Body Circuit (8 Exercises)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'TRX Y-Fly', category: 'weighted', subCategory: 'Rear Deltoid', difficulty: 'Intermediate' },
  { name: 'TRX T-Fly', category: 'weighted', subCategory: 'Rear Deltoid', difficulty: 'Intermediate' },
  { name: 'TRX W-Fly', category: 'weighted', subCategory: 'Rotator Cuff', difficulty: 'Intermediate' },
  { name: 'TRX I-Fly (Lat Pull)', category: 'weighted', subCategory: 'Lats', difficulty: 'Intermediate' },
  { name: 'TRX Crunch', category: 'weighted', subCategory: 'Abs', difficulty: 'Intermediate' },
  { name: 'TRX Plank Saw', category: 'weighted', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'TRX Sprinter Start', category: 'weighted', subCategory: 'Hip Flexors', difficulty: 'Intermediate' },
  { name: 'TRX Side Plank', category: 'weighted', subCategory: 'Obliques', difficulty: 'Intermediate' },
  { name: 'TRX Squat (Suspended)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'TRX Lunge (Rear Foot)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'TRX Bulgarian Split Squat', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'TRX Hip Press (Bilateral)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'TRX Hip Press (Unilateral)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Advanced' },
  { name: 'Barbell OHP (Eccentric Emphasis 5s)', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Barbell OHP (Cluster Set)', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Dumbbell Arnold Press (Standing)', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Dumbbell Lateral Raise (Seated)', category: 'weighted', subCategory: 'Lateral Deltoid', difficulty: 'Beginner' },
  { name: 'Dumbbell Rear Delt Combo (3 Angles)', category: 'weighted', subCategory: 'Rear Deltoid', difficulty: 'Intermediate' },
  { name: 'Dumbbell Cuban Press (Full)', category: 'weighted', subCategory: 'Rotator Cuff', difficulty: 'Intermediate' },
  { name: 'Dumbbell Bradford Press', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Dumbbell See-Saw Press (Alternating)', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Cable Face Pull (Wide, Rope)', category: 'weighted', subCategory: 'Rear Deltoid', difficulty: 'Beginner' },
  { name: 'Cable Face Pull (Narrow, Rope)', category: 'weighted', subCategory: 'Rear Deltoid', difficulty: 'Beginner' },
  { name: 'Cable Rear Delt Row (Rope, High)', category: 'weighted', subCategory: 'Rear Deltoid', difficulty: 'Intermediate' },
  { name: 'Machine Lateral Raise (Full ROM Slow)', category: 'weighted', subCategory: 'Lateral Deltoid', difficulty: 'Intermediate' },
  { name: 'Machine Rear Delt (Full ROM)', category: 'weighted', subCategory: 'Rear Deltoid', difficulty: 'Beginner' },
  { name: 'Machine Upright Row', category: 'weighted', subCategory: 'Traps', difficulty: 'Intermediate' },
  { name: 'Machine Shrug (Heavy)', category: 'weighted', subCategory: 'Traps', difficulty: 'Intermediate' },
  { name: 'Bear Complex (5 Reps Each)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Javorek Complex 1', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Javorek Complex 2', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'King Complex (DL-Shrug-Row-HPC-Press)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Dumbbell Bird Dog Row', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Barbell Good Morning (Rounded)', category: 'weighted', subCategory: 'Lower Back', difficulty: 'Advanced' },
  { name: 'Barbell Good Morning (Arched)', category: 'weighted', subCategory: 'Lower Back', difficulty: 'Intermediate' },
  { name: 'Jefferson Curl (Loaded)', category: 'weighted', subCategory: 'Lower Back', difficulty: 'Advanced' },
  { name: 'Barbell Hip Hinge with Dowel', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Beginner' },
  { name: 'Belt Squat (Plate Loaded)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Hip Thrust (Plate Loaded Machine)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Lat Pulldown (Plate Loaded)', category: 'weighted', subCategory: 'Lats', difficulty: 'Intermediate' },
  { name: 'Seated Row (Plate Loaded)', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Overhead Press (Plate Loaded)', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Hyperextension (Plate Loaded)', category: 'weighted', subCategory: 'Lower Back', difficulty: 'Intermediate' },
  { name: 'Glute Drive (Plate Loaded)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Nordic Hamstring Machine (GHD)', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Advanced' },
  { name: 'Reverse Hyper (Plate Loaded)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'T-Bar Row (Plate Loaded)', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Farmer Handle Deadlift', category: 'weighted', subCategory: 'Grip', difficulty: 'Advanced' },
  { name: 'One-Hand Barbell Deadlift', category: 'weighted', subCategory: 'Grip', difficulty: 'Advanced' },
  { name: 'Plate Pinch Curl', category: 'weighted', subCategory: 'Grip', difficulty: 'Advanced' },
  { name: 'Axle Bar Overhead Press', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Towel Pull-Up (Weighted)', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Weighted Shadowbox (Light Dumbbells)', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Medicine Ball Punch Throw (Wall)', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Medicine Ball Uppercut Throw', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Resistance Band Jab-Cross', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Resistance Band Hook', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Wrist Roller Full Up + Down', category: 'weighted', subCategory: 'Forearms', difficulty: 'Intermediate' },
  { name: 'Pronation Dumbbell Curl', category: 'weighted', subCategory: 'Forearms', difficulty: 'Intermediate' },
  { name: 'Supination Dumbbell Curl', category: 'weighted', subCategory: 'Forearms', difficulty: 'Intermediate' },
  { name: 'Barbell Wrist Curl (Seated, Full)', category: 'weighted', subCategory: 'Forearms', difficulty: 'Beginner' },
  { name: 'EZ Bar Pronation Curl', category: 'weighted', subCategory: 'Forearms', difficulty: 'Intermediate' },
  { name: 'Cable Wrist Curl (Low Anchor)', category: 'weighted', subCategory: 'Forearms', difficulty: 'Beginner' },
  { name: 'Cable Reverse Wrist Curl (Low)', category: 'weighted', subCategory: 'Forearms', difficulty: 'Beginner' },
  { name: 'Dumbbell Zottman Curl', category: 'weighted', subCategory: 'Brachialis', difficulty: 'Intermediate' },
  { name: 'Stone Deadlift to Platform', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Sandbag Carry to Bag Load', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Keg Carry + Press Medley', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Log Carry + Squat Medley', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Farmer Walk + Sled Push Medley', category: 'weighted', subCategory: 'Grip', difficulty: 'Advanced' },
  { name: 'Atlas Stone Series (4 Stones)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Double Kettlebell Rack Walk', category: 'weighted', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Double Kettlebell Overhead Walk', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Dumbbell Waiters Walk (Both Arms)', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Single-Arm Farmer Walk', category: 'weighted', subCategory: 'Obliques', difficulty: 'Intermediate' },
  { name: 'Zercher Carry (Barbell)', category: 'weighted', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Goblet Carry (Kettlebell)', category: 'weighted', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Bottoms-Up Kettlebell Walk', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Barbell Hip Thrust (High Rep)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Dumbbell Romanian Deadlift (High Rep)', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Beginner' },
  { name: 'Banded Hip Thrust (Resistance)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Banded Glute Bridge (Pulse)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Cable Glute Kickback (Standing)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Cable Hip Abduction (Standing)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Leg Press Glute Focus (High Foot)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Machine Hip Thrust (Seated)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Dumbbell Bulgarian Split Squat (High Rep)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Barbell Hip Thrust (Pause at Top)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Dumbbell Goblet Squat (High Rep)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Barbell Box Squat (Competition Width)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Advanced' },
  { name: 'Barbell Paused Front Squat (2s)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Romanian DL (Snatch Grip)', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Advanced' },
  { name: 'Barbell Sumo DL (Slow Down)', category: 'weighted', subCategory: 'Inner Thighs', difficulty: 'Advanced' },
  { name: 'Barbell Bench (Powerlifting Arch)', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Dumbbell Cossack Squat (Loaded)', category: 'weighted', subCategory: 'Inner Thighs', difficulty: 'Advanced' },
  { name: 'Medicine Ball Soccer Throw', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Medicine Ball Cricket Bowl Sim', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Medicine Ball Baseball Throw', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Medicine Ball Golf Swing Sim', category: 'weighted', subCategory: 'Obliques', difficulty: 'Intermediate' },
  { name: 'Sandbag Bear Hug Squat (Heavy)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Sandbag Over Shoulder (Right)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Sandbag Over Shoulder (Left)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Sandbag Zercher Lunge', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Tire Hammer Slam (Overhead)', category: 'weighted', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Sled Row + Walk Complex', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Sled Face Pull + Backpedal', category: 'weighted', subCategory: 'Rear Deltoid', difficulty: 'Intermediate' },
  { name: 'Battle Rope Seated Slams', category: 'weighted', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Battle Rope Kneeling Power Slam', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Battle Rope Hip Circle Wave', category: 'weighted', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Battle Rope Sprawl Wave', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Barbell Sumo DL (Banded)', category: 'weighted', subCategory: 'Inner Thighs', difficulty: 'Advanced' },
  { name: 'Barbell Hip Thrust (Chains)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Advanced' },
  { name: 'Barbell Squat (Chains)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
];