// CSV Exercise Pool — 1000 exercises from uploaded database
// Each entry: { name, category ('bodyweight'|'weighted'), subCategory (muscle group), difficulty }

export const CSV_EXERCISES = [
  // ── PUSH / CHEST ──
  { name: 'Standard Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Beginner' },
  { name: 'Wide-Grip Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Beginner' },
  { name: 'Narrow-Grip Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Beginner' },
  { name: 'Diamond Push-Up', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Decline Push-Up', category: 'bodyweight', subCategory: 'Upper Chest', difficulty: 'Intermediate' },
  { name: 'Incline Push-Up', category: 'bodyweight', subCategory: 'Lower Chest', difficulty: 'Beginner' },
  { name: 'Pike Push-Up', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Archer Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Pseudo Planche Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Clap Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Explosive Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Spiderman Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'T Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Staggered Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Hindu Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Dive Bomber Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'One-Arm Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Typewriter Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Ring Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Fingertip Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Elevated Pike Push-Up', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Chest Dip', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Tiger Bend Push-Up', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Advanced' },
  { name: 'Knuckle Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Beginner' },
  { name: 'Slow Eccentric Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Shoulder-Width Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Beginner' },
  { name: '3-Second Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Isometric Push-Up Hold', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Push-Up to Downward Dog', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Beginner' },
  { name: 'Planche Lean', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Push-Up with Rotation', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Plyometric Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Military Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Decline Clap Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Wide Push-Up Hold', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Beginner' },
  { name: 'Knee Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Beginner' },
  { name: 'Feet-Elevated Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Ring Dip', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Tuck Planche', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Straddle Planche', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Lateral Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'One-Arm Push-Up (Knees)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Push-Up with Leg Raise', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Side-to-Side Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Push-Up Jack', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Tricep Push-Up Hold', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Push-Up to Child\'s Pose', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Beginner' },
  { name: 'Push-Up Walkout', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },

  // ── BACK / PULL ──
  { name: 'Pull-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Chin-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Wide-Grip Pull-Up', category: 'bodyweight', subCategory: 'Upper Back', difficulty: 'Intermediate' },
  { name: 'Neutral-Grip Pull-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Commando Pull-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'L-Sit Pull-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Explosive Pull-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Archer Pull-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Muscle-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Inverted Row', category: 'bodyweight', subCategory: 'Back', difficulty: 'Beginner' },
  { name: 'Wide Inverted Row', category: 'bodyweight', subCategory: 'Upper Back', difficulty: 'Beginner' },
  { name: 'Narrow Inverted Row', category: 'bodyweight', subCategory: 'Back', difficulty: 'Beginner' },
  { name: 'Australian Pull-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Beginner' },
  { name: 'Scapular Pull-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Beginner' },
  { name: 'Dead Hang', category: 'bodyweight', subCategory: 'Grip', difficulty: 'Beginner' },
  { name: 'Active Dead Hang', category: 'bodyweight', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Negative Pull-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Beginner' },
  { name: 'Towel Pull-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Typewriter Pull-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'One-Arm Hang', category: 'bodyweight', subCategory: 'Grip', difficulty: 'Advanced' },
  { name: 'Superman Hold', category: 'bodyweight', subCategory: 'Lower Back', difficulty: 'Beginner' },
  { name: 'Superman Pulse', category: 'bodyweight', subCategory: 'Lower Back', difficulty: 'Beginner' },
  { name: 'Back Extension (Floor)', category: 'bodyweight', subCategory: 'Lower Back', difficulty: 'Beginner' },
  { name: 'Good Morning (Bodyweight)', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Beginner' },
  { name: 'Reverse Hyper', category: 'bodyweight', subCategory: 'Lower Back', difficulty: 'Intermediate' },
  { name: 'Prone Y-T-W Raise', category: 'bodyweight', subCategory: 'Upper Back', difficulty: 'Beginner' },
  { name: 'Scapular Retraction', category: 'bodyweight', subCategory: 'Upper Back', difficulty: 'Beginner' },
  { name: 'Ring Row', category: 'bodyweight', subCategory: 'Back', difficulty: 'Beginner' },
  { name: 'Kipping Pull-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Butterfly Pull-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Slow-Negative Inverted Row', category: 'bodyweight', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Ring Face Pull', category: 'bodyweight', subCategory: 'Rear Deltoid', difficulty: 'Intermediate' },
  { name: 'Feet-Elevated Ring Row', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Towel Row', category: 'bodyweight', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Door Frame Row', category: 'bodyweight', subCategory: 'Back', difficulty: 'Beginner' },
  { name: 'Front Lever', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Tuck Front Lever', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Back Lever', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Jumping Pull-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Beginner' },
  { name: 'Band-Assisted Pull-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Beginner' },
  { name: 'Close-Grip Chin-Up', category: 'bodyweight', subCategory: 'Biceps', difficulty: 'Intermediate' },
  { name: 'Mixed-Grip Pull-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Plyo Pull-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },

  // ── SHOULDERS ──
  { name: 'Wall Handstand', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Free Handstand', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Handstand Push-Up', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Elevated Pike Push-Up (Box)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Band Pull-Apart', category: 'bodyweight', subCategory: 'Rear Deltoid', difficulty: 'Beginner' },
  { name: 'Wall Angels', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Arm Circles (Forward)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Arm Circles (Backward)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Shoulder Taps', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Pike Press', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Crab Walk', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Inchworm', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Shoulder Circles', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Lateral Arm Raise (Resistance Band)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Handstand Hold', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Pike Press on Box', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Shoulder Press (Bands)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Front Raise (Bands)', category: 'bodyweight', subCategory: 'Front Deltoid', difficulty: 'Beginner' },
  { name: 'Rear Delt Fly (Bands)', category: 'bodyweight', subCategory: 'Rear Deltoid', difficulty: 'Beginner' },
  { name: 'Face Pull (Bands)', category: 'bodyweight', subCategory: 'Rear Deltoid', difficulty: 'Beginner' },
  { name: 'External Rotation (Band)', category: 'bodyweight', subCategory: 'Rotator Cuff', difficulty: 'Beginner' },
  { name: 'Internal Rotation (Band)', category: 'bodyweight', subCategory: 'Rotator Cuff', difficulty: 'Beginner' },

  // ── ARMS (Triceps / Biceps) ──
  { name: 'Human Flag', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Tricep Dip (Bench)', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Beginner' },
  { name: 'Tricep Dip (Parallel Bars)', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Close-Grip Push-Up', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Beginner' },
  { name: 'Overhead Tricep Extension (Band)', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Beginner' },
  { name: 'Tricep Kickback (Band)', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Beginner' },
  { name: 'Skull Crusher (Bodyweight)', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Diamond Push-Up Wide', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Beginner' },
  { name: 'Bench Dip to Failure', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Korean Dip', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Advanced' },
  { name: 'One-Arm Tricep Push-Up', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Advanced' },
  { name: 'Chin-Up (Close Grip)', category: 'bodyweight', subCategory: 'Biceps', difficulty: 'Intermediate' },
  { name: 'Resistance Band Curl', category: 'bodyweight', subCategory: 'Biceps', difficulty: 'Beginner' },
  { name: 'Towel Curl', category: 'bodyweight', subCategory: 'Biceps', difficulty: 'Intermediate' },
  { name: 'Isometric Bicep Hold', category: 'bodyweight', subCategory: 'Biceps', difficulty: 'Beginner' },
  { name: 'Hammer Curl (Band)', category: 'bodyweight', subCategory: 'Biceps', difficulty: 'Beginner' },
  { name: 'Concentration Curl (Band)', category: 'bodyweight', subCategory: 'Biceps', difficulty: 'Beginner' },
  { name: 'Negative Chin-Up', category: 'bodyweight', subCategory: 'Biceps', difficulty: 'Beginner' },
  { name: 'Inverted Curl', category: 'bodyweight', subCategory: 'Biceps', difficulty: 'Intermediate' },

  // ── LEGS ──
  { name: 'Bodyweight Squat', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Sumo Squat', category: 'bodyweight', subCategory: 'Inner Thighs', difficulty: 'Beginner' },
  { name: 'Pulse Squat', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Jump Squat', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Pistol Squat', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Shrimp Squat', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Pause Squat', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Split Squat', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Bulgarian Split Squat', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Lateral Lunge', category: 'bodyweight', subCategory: 'Inner Thighs', difficulty: 'Beginner' },
  { name: 'Cossack Squat', category: 'bodyweight', subCategory: 'Inner Thighs', difficulty: 'Intermediate' },
  { name: 'Step-Up', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Box Jump', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Broad Jump', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Single Leg Deadlift', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Nordic Curl', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Advanced' },
  { name: 'Sissy Squat', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Glute Bridge', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Single-Leg Glute Bridge', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Hip Thrust (Bodyweight)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Donkey Kick', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Fire Hydrant', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Calf Raise (Double)', category: 'bodyweight', subCategory: 'Calves', difficulty: 'Beginner' },
  { name: 'Calf Raise (Single Leg)', category: 'bodyweight', subCategory: 'Calves', difficulty: 'Intermediate' },
  { name: 'Ankle Hops', category: 'bodyweight', subCategory: 'Calves', difficulty: 'Beginner' },
  { name: 'Ankle Pogos', category: 'bodyweight', subCategory: 'Calves', difficulty: 'Intermediate' },
  { name: 'Drop Jump', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Fifer Scissor Hops', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Glute Bridge March', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'High Knees', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Hip Airplane', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Isometric Wall Sit', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Lateral Bound (Skater)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Lunge to Knee Drive', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Nordic Hamstring Curl', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Advanced' },

  // ── CORE ──
  { name: 'Plank', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Side Plank', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Hollow Hold', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Arch Hold', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'L-Sit', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'V-Sit', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Dead Bug', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Bicycle Crunch', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Russian Twist', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Mountain Climber', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Plank to Pike', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Windshield Wiper', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Dragon Flag', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Ab Wheel Rollout', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Hanging Leg Raise', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Toes to Bar', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Dish Drill', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'GHD Sit-Up', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Hanging Knee Raises', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Hanging Straight Leg Raise', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Hollow Rock', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Leg Raises (Floor)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Flutter Kicks', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Toe Touches', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Crunch', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Reverse Crunch', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Cable Anti-Rotation Hold', category: 'weighted', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Pallof Press', category: 'weighted', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Cable Woodchop High to Low', category: 'weighted', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Medicine Ball Slam', category: 'weighted', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Medicine Ball Rotational Throw', category: 'weighted', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Landmine Rotation', category: 'weighted', subCategory: 'Core', difficulty: 'Intermediate' },

  // ── CARDIO ──
  { name: 'Burpee', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Butt Kicks', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Beginner' },
  { name: 'Jumping Jacks', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Beginner' },
  { name: 'Star Jumps', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Tuck Jumps', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Skater Hops', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Bear Crawl', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Agility Ladder Drills', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Jump Rope', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Beginner' },
  { name: 'Hill Sprint', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Box Drill', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },

  // ── MOBILITY ──
  { name: 'Cat-Cow', category: 'bodyweight', subCategory: 'Mobility', difficulty: 'Beginner' },
  { name: "World's Greatest Stretch", category: 'bodyweight', subCategory: 'Mobility', difficulty: 'Beginner' },
  { name: 'Spiderman Lunge', category: 'bodyweight', subCategory: 'Mobility', difficulty: 'Beginner' },
  { name: 'Shoulder Dislocate', category: 'bodyweight', subCategory: 'Mobility', difficulty: 'Beginner' },
  { name: 'Scorpion Stretch', category: 'bodyweight', subCategory: 'Mobility', difficulty: 'Intermediate' },
  { name: 'Seal Stretch', category: 'bodyweight', subCategory: 'Mobility', difficulty: 'Beginner' },
  { name: 'Child\'s Pose', category: 'bodyweight', subCategory: 'Mobility', difficulty: 'Beginner' },
  { name: 'Cobra Stretch', category: 'bodyweight', subCategory: 'Mobility', difficulty: 'Beginner' },
  { name: 'Hip Flexor Stretch', category: 'bodyweight', subCategory: 'Mobility', difficulty: 'Beginner' },
  { name: 'Pigeon Pose', category: 'bodyweight', subCategory: 'Mobility', difficulty: 'Intermediate' },
  { name: 'Downward Dog', category: 'bodyweight', subCategory: 'Mobility', difficulty: 'Beginner' },
  { name: 'Thoracic Rotation', category: 'bodyweight', subCategory: 'Mobility', difficulty: 'Beginner' },
  { name: 'Hip 90/90 Stretch', category: 'bodyweight', subCategory: 'Mobility', difficulty: 'Beginner' },
  { name: 'Lying Hamstring Stretch', category: 'bodyweight', subCategory: 'Mobility', difficulty: 'Beginner' },
  { name: 'Standing Quad Stretch', category: 'bodyweight', subCategory: 'Mobility', difficulty: 'Beginner' },
  { name: 'Seated Forward Fold', category: 'bodyweight', subCategory: 'Mobility', difficulty: 'Beginner' },

  // ── WEIGHTED — CHEST ──
  { name: 'Barbell Bench Press', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Dumbbell Bench Press', category: 'weighted', subCategory: 'Chest', difficulty: 'Beginner' },
  { name: 'Incline Barbell Press', category: 'weighted', subCategory: 'Upper Chest', difficulty: 'Intermediate' },
  { name: 'Incline Dumbbell Press', category: 'weighted', subCategory: 'Upper Chest', difficulty: 'Beginner' },
  { name: 'Decline Bench Press', category: 'weighted', subCategory: 'Lower Chest', difficulty: 'Intermediate' },
  { name: 'Dumbbell Floor Press', category: 'weighted', subCategory: 'Chest', difficulty: 'Beginner' },
  { name: 'Landmine Press', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Cable Chest Fly', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Dumbbell Chest Fly', category: 'weighted', subCategory: 'Chest', difficulty: 'Beginner' },
  { name: 'Machine Chest Press', category: 'weighted', subCategory: 'Chest', difficulty: 'Beginner' },
  { name: 'Cable Chest Press', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },

  // ── WEIGHTED — BACK ──
  { name: 'Barbell Row', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Dumbbell Row', category: 'weighted', subCategory: 'Back', difficulty: 'Beginner' },
  { name: 'T-Bar Row', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Chest-Supported Row', category: 'weighted', subCategory: 'Back', difficulty: 'Beginner' },
  { name: 'Seal Row', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Lat Pulldown', category: 'weighted', subCategory: 'Back', difficulty: 'Beginner' },
  { name: 'Cable Row', category: 'weighted', subCategory: 'Back', difficulty: 'Beginner' },
  { name: 'Single Arm Cable Row', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Face Pull', category: 'weighted', subCategory: 'Rear Deltoid', difficulty: 'Beginner' },
  { name: 'Reverse Fly', category: 'weighted', subCategory: 'Rear Deltoid', difficulty: 'Beginner' },
  { name: 'Deadlift', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Romanian Deadlift', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Trap Bar Deadlift', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Good Morning (Weighted)', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Jefferson Curl', category: 'weighted', subCategory: 'Lower Back', difficulty: 'Advanced' },
  { name: 'Single-Arm Dumbbell Row', category: 'weighted', subCategory: 'Back', difficulty: 'Beginner' },

  // ── WEIGHTED — SHOULDERS ──
  { name: 'Overhead Press', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Dumbbell Shoulder Press', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Arnold Press', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Lateral Raise (Dumbbell)', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Front Raise (Dumbbell)', category: 'weighted', subCategory: 'Front Deltoid', difficulty: 'Beginner' },
  { name: 'Rear Delt Fly (Dumbbell)', category: 'weighted', subCategory: 'Rear Deltoid', difficulty: 'Beginner' },
  { name: 'Cable Lateral Raise', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Upright Row', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Push Press', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Bradford Press', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Cable Rope Face Pull', category: 'weighted', subCategory: 'Rear Deltoid', difficulty: 'Beginner' },
  { name: 'KB Overhead Carry', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },

  // ── WEIGHTED — ARMS ──
  { name: 'Barbell Curl', category: 'weighted', subCategory: 'Biceps', difficulty: 'Beginner' },
  { name: 'Dumbbell Curl', category: 'weighted', subCategory: 'Biceps', difficulty: 'Beginner' },
  { name: 'Hammer Curl', category: 'weighted', subCategory: 'Biceps', difficulty: 'Beginner' },
  { name: 'Preacher Curl', category: 'weighted', subCategory: 'Biceps', difficulty: 'Intermediate' },
  { name: 'Cable Curl', category: 'weighted', subCategory: 'Biceps', difficulty: 'Beginner' },
  { name: 'Tricep Pushdown', category: 'weighted', subCategory: 'Triceps', difficulty: 'Beginner' },
  { name: 'Overhead Tricep Extension', category: 'weighted', subCategory: 'Triceps', difficulty: 'Beginner' },
  { name: 'Skull Crusher', category: 'weighted', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Close-Grip Bench Press', category: 'weighted', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Dumbbell Kickback', category: 'weighted', subCategory: 'Triceps', difficulty: 'Beginner' },
  { name: 'Cable Overhead Extension', category: 'weighted', subCategory: 'Triceps', difficulty: 'Beginner' },
  { name: 'EZ-Bar Skullcrusher', category: 'weighted', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Concentration Curl', category: 'weighted', subCategory: 'Biceps', difficulty: 'Beginner' },
  { name: 'Curl to Press', category: 'weighted', subCategory: 'Biceps', difficulty: 'Intermediate' },

  // ── WEIGHTED — LEGS ──
  { name: 'Barbell Back Squat', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Front Squat', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Goblet Squat', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Leg Press', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Hack Squat', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Bulgarian Split Squat (Weighted)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Walking Lunge (Weighted)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Leg Extension', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Leg Curl', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Beginner' },
  { name: 'Calf Raise (Standing Weighted)', category: 'weighted', subCategory: 'Calves', difficulty: 'Beginner' },
  { name: 'Barbell Hip Thrust', category: 'weighted', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Goblet Reverse Lunge', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Hamstring Curl Machine', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Beginner' },
  { name: 'Hip Thrust (Weighted)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'KB Goblet Squat', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'KB Lunge Walk', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Pistol Squat (Weighted)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },

  // ── WEIGHTED — FULL BODY ──
  { name: 'Power Clean', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Clean and Press', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Snatch', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Thruster', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Kettlebell Swing', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Turkish Get-Up', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Man Maker', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Dumbbell Complex', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Battle Ropes', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Clean and Jerk', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: "Farmer's Carry", category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Front Rack Carry', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'KB Clean to Press', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Kettlebell Snatch', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Medicine Ball Overhead Catch', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Sandbag Carry', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Sled Push', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
];