// Exercise Database Batch 4 — IDs 3001–4000
export const CSV_EXERCISES_BATCH4 = [
  { name: 'Wall Handstand Chest-to-Wall', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Freestanding Handstand Attempt', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Handstand Kick-Up (Both Legs)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Straddle Handstand Hold', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'One-Arm Handstand Wall Support', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Handstand Vertical Hold Test', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Tuck Planche Hold (Rings)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Advanced Tuck Planche Hold', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Straddle Planche Hold', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Full Planche Hold (Assisted)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Tuck Front Lever Hold', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Advanced Tuck Front Lever Hold', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Straddle Front Lever Hold', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Full Front Lever Hold (Assisted)', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Tuck Back Lever Hang', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Advanced Tuck Back Lever', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Straddle Back Lever Hold', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Iron Cross Progression (Tuck)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Ring Support Hold (30s)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Ring Support with Turned-Out Hands', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Ring Dip (Full ROM)', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Advanced' },
  { name: 'Ring Push-Up (Full ROM)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Ring Row (Full ROM)', category: 'bodyweight', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Ring False Grip Dead Hang', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Muscle-Up Transition Drill (Bar)', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Muscle-Up Negative (Ring)', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Strict Bar Muscle-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'L-Sit on Floor (Parallel Bars)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'V-Sit on Parallel Bars', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Manna Tuck Progression', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Dragon Flag Full ROM', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Dragon Flag Negative (5s)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Dragon Flag Isometric Hold', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Human Flag Tuck Attempt', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Human Flag Full (Assisted)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Skin the Cat (Full ROM)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'German Hang (Passive)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Back Extension on Bar (Kip)', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Typewriter Pull-Up (Full)', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Commando Pull-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Side-to-Side Pull-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'One-Arm Dead Hang (30s)', category: 'bodyweight', subCategory: 'Grip', difficulty: 'Advanced' },
  { name: 'One-Arm Pull-Up Negative', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'One-Arm Ring Row', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Back Lever to Skin the Cat', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Front Lever Row', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'L-Sit Pull-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Archer Pull-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Pelican Curl (Rings)', category: 'bodyweight', subCategory: 'Biceps', difficulty: 'Advanced' },
  { name: 'Ring Bicep Curl', category: 'bodyweight', subCategory: 'Biceps', difficulty: 'Advanced' },
  { name: 'One-Arm Ring Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Ring Planche Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Ring Rear Support Hold', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Advanced' },
  { name: 'Cross Tuck (Rings)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Maltese Tuck (Rings)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Straddle Planche Push-Up (Bars)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Planche Lean + Hip Extension', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Handstand Pirouette (Full)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Clapping Push-Up (Chest Level)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Superman Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: '90° Push-Up', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Advanced' },
  { name: 'Push-Up + Reach Under', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Push-Up to Hip Circle', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Push-Up with Ankle Tap', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Hindu Push-Up with Pause at Top', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Push-Up (Feet on Ball)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Stability Ball Push-Up Staggered', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Push-Up with Ball Pass', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Spiderman Push-Up (Both Sides)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'T-Push-Up (Dumbbell Grip)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Diamond Push-Up to Flare', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Advanced' },
  { name: 'Reverse Push-Up with Hip Pop', category: 'bodyweight', subCategory: 'Upper Back', difficulty: 'Intermediate' },
  { name: 'Explosive Wide-to-Narrow Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Weighted Vest Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Weighted Vest Decline Push-Up', category: 'bodyweight', subCategory: 'Upper Chest', difficulty: 'Intermediate' },
  { name: 'Weighted Vest Dip', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Advanced' },
  { name: 'Weighted Vest Pike Push-Up', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Weighted Vest Pull-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Band-Resisted Push-Up (Across Back)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Band-Resisted Dip', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Advanced' },
  { name: 'Band-Resisted Pull-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Push-Up on Unstable Surface', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'BOSU Push-Up (Dome Down)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'BOSU Push-Up (Dome Up)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Suspension Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Suspension Fly to Push', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Gymnastics Ring Push-Up with Fly', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Ring Dip to Push-Up Combo', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Advanced' },
  { name: 'Slow Push-Up Negative (8s Down)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Push-Up Pyramid (1 to 10)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: '100 Push-Up Challenge', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Push-Up Max Rep Test', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Push-Up Hold + Shoulder Tap', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Push-Up with Elevated Front Foot', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Push-Up Complex (Wide-Narrow-Diamond)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Plyo Push-Up + Lateral Hop', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: '10 Types of Push-Up Circuit', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Pseudo Planche Push-Up with Band', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Shrimp Squat (Full)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Shrimp Squat Negative', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Shrimp Squat to Box', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Natural Leg Extension', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Sissy Squat Full ROM', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Sissy Squat with Pause', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Dragon Squat', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Lunge Matrix (6 Directions)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Lateral Lunge to Step-Up', category: 'bodyweight', subCategory: 'Inner Thighs', difficulty: 'Advanced' },
  { name: 'Curtsy Lunge to Side Kick', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Reverse Lunge to Forward Kick', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Walking Lunge (Backward)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Jumping Split Lunge (Scissors)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Cross-Body Lunge (Traveling)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Single-Leg Box Jump Landing', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Advanced' },
  { name: 'Depth Jump to Sprint', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Advanced' },
  { name: 'Bounding (Continuous)', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Advanced' },
  { name: 'Single-Arm Overhead Lunge (BW)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Contralateral Step + Reach', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Intermediate' },
  { name: 'Single-Leg Deadlift + Hop', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Advanced' },
  { name: 'Pistol Squat to Tuck Jump', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Step-Up (Crossover)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Lateral Bound + Stick (3 Reps)', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Advanced' },
  { name: 'Split Squat ISO Hold (60s)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Nordic Drop to Push-Up', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Advanced' },
  { name: 'GHD Sit-Up Negative', category: 'bodyweight', subCategory: 'Abs', difficulty: 'Advanced' },
  { name: 'GHD Hip Extension + Row', category: 'bodyweight', subCategory: 'Lower Back', difficulty: 'Advanced' },
  { name: 'Full ROM Bulgarian Split Squat', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Floating Split Squat', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Glute Bridge + Knee Drive', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Glute Bridge + Leg Extension', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Single-Leg Hip Thrust + Curl', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Advanced' },
  { name: 'Resisted Hip Thrust (Band, Seated)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Wall Sit + Bicep Curl (BW)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Wall Sit + Shoulder Press (BW)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Deep Squat + Calf Raise', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Squat + Lateral Leg Raise', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Ab Wheel Rollout (From Toes, Max)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Ab Wheel Circle (From Knees)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Ab Wheel Single-Arm (From Knees)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Ab Wheel Pike (Standing)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Ab Wheel Lateral (From Knees)', category: 'bodyweight', subCategory: 'Obliques', difficulty: 'Advanced' },
  { name: 'Dragon Flag Full Lowering Phase', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Dragon Flag Tuck-to-Full Transition', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'GHD Sit-Up (Full Hyperextension)', category: 'bodyweight', subCategory: 'Abs', difficulty: 'Advanced' },
  { name: 'GHD Side Bend', category: 'bodyweight', subCategory: 'Obliques', difficulty: 'Advanced' },
  { name: 'GHD Oblique Crunch', category: 'bodyweight', subCategory: 'Obliques', difficulty: 'Advanced' },
  { name: 'Hollow Body Press (Parallettes)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Hollow Body Rock + Pull', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Hollow Body 360 Roll', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Tuck-to-Hollow Transition', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Straddle-to-Hollow Transition', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Windmill Complex (Full Circuit)', category: 'bodyweight', subCategory: 'Obliques', difficulty: 'Advanced' },
  { name: 'Tuck Planche to Hollow', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'L-Sit to Tuck Planche', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'V-Sit to Tuck Planche', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Press to Handstand (Tuck)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Press to Handstand (Straddle)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Negative Press to Handstand', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Lying Weighted Oblique Crunch (BW)', category: 'bodyweight', subCategory: 'Obliques', difficulty: 'Intermediate' },
  { name: 'Decline Hanging Leg Raise', category: 'bodyweight', subCategory: 'Lower Abs', difficulty: 'Intermediate' },
  { name: 'Decline Hanging Tuck Raise', category: 'bodyweight', subCategory: 'Lower Abs', difficulty: 'Intermediate' },
  { name: 'Hanging L-Sit Hold', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Hanging Straddle L-Sit', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Hanging Pike Raise', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Hanging Full Lever Raise', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Hanging L-Sit + Pull-Up Combo', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Hanging Single-Leg Raise (Slow)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Hanging Tuck Spin', category: 'bodyweight', subCategory: 'Obliques', difficulty: 'Advanced' },
  { name: 'Hanging Straddle Swing', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Parallel Bar L-Sit + Dip', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'V-Sit + Dip', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Manna Shoulder Extension', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Straddle Press to L-Sit', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Full 360° Core Circuit (BW)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Isometric Side Bend (Hinge)', category: 'bodyweight', subCategory: 'Obliques', difficulty: 'Intermediate' },
  { name: 'Loaded Progressive Hollow (Leg Lower)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Starfish Crunch', category: 'bodyweight', subCategory: 'Abs', difficulty: 'Intermediate' },
  { name: 'Reverse Plank Leg Raise', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Reverse Plank Push', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Supine Hip Circle', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Supine Leg Figure 8', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Prone Plank Circuit (All Variations)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Side Plank Complex (Dip-Raise-Twist)', category: 'bodyweight', subCategory: 'Obliques', difficulty: 'Advanced' },
  { name: 'Anti-Rotation Complex (Band Circuit)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Man Maker (BW Version)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Turkish Get-Up Complex (All Phases)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Calisthenics Complex (Pull-Push-Squat)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'EMOM Pull-Up + Push-Up', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'AMRAP Burpee + Pull-Up', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Grease the Groove (Pull-Up)', category: 'bodyweight', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Grease the Groove (Dip)', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Grease the Groove (Push-Up)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Beginner' },
  { name: 'Max Effort Pull-Up Test', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Max Effort Push-Up Test', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Max Effort Dip Test', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Advanced' },
  { name: 'Max Effort Squat Test (60s)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Pull-Up to Leg Raise Combo', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Push-Up to Burpee Combo', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Squat to Tuck Jump Combo', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Dip to L-Sit Combo', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Advanced' },
  { name: 'Muscle-Up to Dip Combo', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Handstand to Plank Combo', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Pull-Up Grip Rotation (OWNW)', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Calisthenics HIIT (10 Exercises)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Timed Calisthenics Block (20/10)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Ladder Calisthenics (Pull-Push-Hinge)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Deck of Cards Workout', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: '300 Rep Challenge', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Movement Flow (Crawl-Jump-Roll)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Animal Flow Circuit', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Primal Movement Sequence', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Kickboxing Shadowbox Combo', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Shadowbox Jab-Cross-Hook-Uppercut', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Beginner' },
  { name: 'Shadowbox Defensive Slip + Strike', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Jump Rope (Cross)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Jump Rope (Double Under)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Jump Rope (Backward)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Jump Rope (High Knee)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Jump Rope (Single-Leg Alternating)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Jump Rope (Speed)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Jump Rope Pyramid (10 to 100)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Boxing Heavy Bag Combo', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Boxing Heavy Bag Footwork Drill', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Muay Thai Round Kicks (Bag)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Slip Bag Drill (Head Movement)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Speed Bag Drill', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Double End Bag Drill', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Wrestle Pummeling Drill', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'BJJ Hip Escape (Shrimp)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'BJJ Technical Stand-Up', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'BJJ Guard Movement Drill', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Breakfall (Front Roll)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Breakfall (Side Roll)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Crow Pose (Bakasana)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Side Crow (Parsva Bakasana)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Eight-Angle Pose (Astavakrasana)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Firefly Pose (Tittibhasana)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Peacock Pose (Mayurasana)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Handstand Scorpion (Vrschikasana)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Forearm Stand (Pincha)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Forearm Stand Balance', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Forearm Stand Scorpion', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'One-Arm Balance Pose (Vasisthasana)', category: 'bodyweight', subCategory: 'Obliques', difficulty: 'Advanced' },
  { name: 'Full Boat Pose (Paripurna Navasana)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Half Boat Pose', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Boat Pose Variation (Toe Hold)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Flying Pigeon (Eka Pada Galavasana)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Compass Pose (Parivrtta Surya Yantrasana)', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Advanced' },
  { name: 'Half Moon Pose (Ardha Chandrasana)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Revolved Half Moon', category: 'bodyweight', subCategory: 'Obliques', difficulty: 'Advanced' },
  { name: 'King Dancer Pose (Natarajasana)', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Advanced' },
  { name: 'Warrior III with Bound', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Advanced' },
  { name: 'Bird of Paradise Pose', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Advanced' },
  { name: 'Bound Warrior II', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Bound Side Angle', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Deep Squat Twist (Revolved)', category: 'bodyweight', subCategory: 'Thoracic Spine', difficulty: 'Intermediate' },
  { name: 'Deep Squat + Prayer Twist', category: 'bodyweight', subCategory: 'Thoracic Spine', difficulty: 'Intermediate' },
  { name: 'Pigeon + Quad Bind', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Advanced' },
  { name: 'Yin Hip Flexor Hold (5 min)', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Beginner' },
  { name: 'Yin Butterfly Hold (5 min)', category: 'bodyweight', subCategory: 'Inner Thighs', difficulty: 'Beginner' },
  { name: 'Yin Dragon Pose Hold', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Intermediate' },
  { name: 'Yin Saddle Pose Hold', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Advanced' },
  { name: 'Yin Sleeping Swan Hold', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Yin Twisted Roots Hold', category: 'bodyweight', subCategory: 'Obliques', difficulty: 'Beginner' },
  { name: 'Yin Caterpillar Fold', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Beginner' },
  { name: 'Yin Deer Pose Hold', category: 'bodyweight', subCategory: 'Hip Rotators', difficulty: 'Beginner' },
  { name: 'Yin Banana Pose (Side Body)', category: 'bodyweight', subCategory: 'Obliques', difficulty: 'Beginner' },
  { name: 'Yin Supported Fish', category: 'bodyweight', subCategory: 'Thoracic Spine', difficulty: 'Beginner' },
  { name: "Yin Child's Pose (Extended)", category: 'bodyweight', subCategory: 'Lower Back', difficulty: 'Beginner' },
  { name: 'Yin Frog Pose (Deep)', category: 'bodyweight', subCategory: 'Inner Thighs', difficulty: 'Intermediate' },
  { name: "Yin Wide-Knee Child's Pose", category: 'bodyweight', subCategory: 'Inner Thighs', difficulty: 'Beginner' },
  { name: 'Yin Supported Bridge (Long Hold)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Slackline Walk (Full Length)', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Advanced' },
  { name: 'Slackline Jump + Land', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Advanced' },
  { name: 'Balance Beam Walk with Arm Swing', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Beginner' },
  { name: 'Balance Beam Turn', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Intermediate' },
  { name: 'Balance Beam Squat', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'BOSU Pistol Squat', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'BOSU Lateral Jump', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Advanced' },
  { name: 'BOSU Lunge', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'BOSU Hip Hinge', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'BOSU Push-Up to Flip', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'BOSU Plank Hold', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'BOSU Mountain Climber', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'BOSU Burpee', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Wobble Board Squat', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Wobble Board Single-Leg Stand', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Advanced' },
  { name: 'Trampoline Single-Leg Landing', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Intermediate' },
  { name: 'Trampoline Tuck Jump', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Intermediate' },
  { name: 'Trampoline Twist', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Advanced' },
  { name: 'Reactive Sprint (Partner Tap)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'T-Test Agility Drill', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Illinois Agility Test', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Pro Agility Shuttle', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: '505 Agility Test', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'L-Run Drill', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Reactive Partner Mirror Drill', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Sprint + Jump + Land', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Advanced' },
  { name: 'Reaction Ball Drill', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'Tennis Ball Wall Toss + Sprint', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'Vision Tracking Sprint', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Contract-Relax Hamstring Stretch', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Beginner' },
  { name: 'Contract-Relax Hip Flexor Stretch', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Beginner' },
  { name: 'Contract-Relax Adductor Stretch', category: 'bodyweight', subCategory: 'Inner Thighs', difficulty: 'Beginner' },
  { name: 'Contract-Relax Shoulder Stretch', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Contract-Relax Calf Stretch', category: 'bodyweight', subCategory: 'Calves', difficulty: 'Beginner' },
  { name: 'Active Release Hip Flexor', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Beginner' },
  { name: 'Active Release Hamstring', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Beginner' },
  { name: 'Active Release Calf', category: 'bodyweight', subCategory: 'Calves', difficulty: 'Beginner' },
  { name: 'Active Release Shoulder', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Neural Flossing Sciatic', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Beginner' },
  { name: 'Neural Flossing Femoral', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Neural Flossing Median Nerve', category: 'bodyweight', subCategory: 'Forearms', difficulty: 'Beginner' },
  { name: 'Neural Flossing Radial Nerve', category: 'bodyweight', subCategory: 'Forearms', difficulty: 'Beginner' },
  { name: 'Neural Flossing Ulnar Nerve', category: 'bodyweight', subCategory: 'Forearms', difficulty: 'Beginner' },
  { name: 'Diaphragmatic Breathing (Recovery)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Parasympathetic Breathing', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Cold-Water Breath (Wim Hof Style)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Body Scan Progressive Relaxation', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Foam Roll Full Body Circuit', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Lacrosse Ball Full Body Circuit', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Post-Workout Static Stretch (Full)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Pre-Workout Dynamic Warm-Up (Full)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Joint Circles Full Body Circuit', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Morning Wake-Up Flow', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Evening Wind-Down Flow', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Desk Worker Recovery Flow', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Athlete Active Recovery Day Flow', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Park Bench Dip', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Beginner' },
  { name: 'Park Bench Incline Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Beginner' },
  { name: 'Park Bar Inverted Row', category: 'bodyweight', subCategory: 'Back', difficulty: 'Beginner' },
  { name: 'Park Bar Pull-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Beginner' },
  { name: 'Park Bar Knee Raise', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Playground Ring Row', category: 'bodyweight', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Playground Monkey Bars', category: 'bodyweight', subCategory: 'Grip', difficulty: 'Intermediate' },
  { name: 'Prehab Knee Circuit (Full)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Prehab Shoulder Circuit (Full)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Prehab Hip Circuit (Full)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Prehab Lower Back Circuit', category: 'bodyweight', subCategory: 'Lower Back', difficulty: 'Beginner' },
  { name: 'Prehab Ankle Circuit', category: 'bodyweight', subCategory: 'Ankles', difficulty: 'Beginner' },
  { name: 'Prehab Wrist Circuit', category: 'bodyweight', subCategory: 'Wrists', difficulty: 'Beginner' },
  { name: 'Prehab Neck Circuit', category: 'bodyweight', subCategory: 'Neck', difficulty: 'Beginner' },
  { name: 'Postural Correction Circuit', category: 'bodyweight', subCategory: 'Upper Back', difficulty: 'Beginner' },
  { name: 'Scapular Stability Circuit', category: 'bodyweight', subCategory: 'Serratus Anterior', difficulty: 'Intermediate' },
  { name: 'Hip Stability Circuit', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Core Stability Circuit (Full)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Breathing Circuit (4 Styles)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Beginner BW Workout A', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Beginner BW Workout B', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Intermediate BW Workout A', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Intermediate BW Workout B', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Advanced BW Workout A', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Advanced BW Workout B', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Full Body Stretch Routine (20 min)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Full Body Activation Routine', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Power Development Circuit', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Speed Development Circuit', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Agility Development Circuit', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Strength Endurance Circuit', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Hypertrophy BW Circuit', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Skill Practice Circuit (BW)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Handstand Practice Circuit', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Planche Progression Circuit', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Front Lever Progression Circuit', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Back Lever Progression Circuit', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Barbell Wide Grip Bench (5s Pause)', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Barbell Close Grip Bench (5s Pause)', category: 'weighted', subCategory: 'Triceps', difficulty: 'Advanced' },
  { name: 'Barbell Incline (5s Pause)', category: 'weighted', subCategory: 'Upper Chest', difficulty: 'Advanced' },
  { name: 'Barbell Decline (5s Pause)', category: 'weighted', subCategory: 'Lower Chest', difficulty: 'Advanced' },
  { name: 'Barbell Bench Press (Spoto Pause)', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Barbell Reverse Grip Bench Press', category: 'weighted', subCategory: 'Upper Chest', difficulty: 'Intermediate' },
  { name: 'Barbell Floor Press (5s Pause)', category: 'weighted', subCategory: 'Triceps', difficulty: 'Advanced' },
  { name: 'Barbell Pin Press (3-Board Height)', category: 'weighted', subCategory: 'Triceps', difficulty: 'Advanced' },
  { name: 'Barbell Larsen Press', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Barbell Bench with Chains', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Barbell Incline with Bands', category: 'weighted', subCategory: 'Upper Chest', difficulty: 'Advanced' },
  { name: 'Barbell Decline with Chains', category: 'weighted', subCategory: 'Lower Chest', difficulty: 'Advanced' },
  { name: 'Barbell Isometric Bench (3s Push)', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Barbell Bench (Concentric Only)', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Barbell 21s Bench Press', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Barbell Floor Press with Bands', category: 'weighted', subCategory: 'Triceps', difficulty: 'Advanced' },
  { name: 'Barbell Swiss Bar Incline', category: 'weighted', subCategory: 'Upper Chest', difficulty: 'Intermediate' },
  { name: 'Barbell Cambered Bar Bench', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Barbell Sumo + Bands', category: 'weighted', subCategory: 'Inner Thighs', difficulty: 'Advanced' },
  { name: 'Barbell Conventional + Chains', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Barbell Trap Bar (Standard Height)', category: 'weighted', subCategory: 'Back', difficulty: 'Beginner' },
  { name: 'Barbell Romanian + Pause at Mid-Shin', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Advanced' },
  { name: 'Barbell Stiff-Leg + 2-Second Pause', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Advanced' },
  { name: 'Barbell Romanian + Banded', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Advanced' },
  { name: 'Barbell Deadlift (Clean Grip Pause)', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Barbell Snatch Grip Deadlift (Pause)', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Barbell Jefferson Deadlift', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Barbell Kneeling Romanian Deadlift', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Advanced' },
  { name: 'Barbell Seated Romanian Deadlift', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Barbell Deficit Conventional DL (3in)', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Barbell Dead-Stop Deadlift (Touch Floor)', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Barbell Reverse Band Deadlift', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Barbell Axle Deadlift (Fat Bar)', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Barbell Trap Bar (Low Handle)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Barbell Trap Bar (High Handle)', category: 'weighted', subCategory: 'Back', difficulty: 'Beginner' },
  { name: 'Barbell Sumo (Wide Stance Pause)', category: 'weighted', subCategory: 'Inner Thighs', difficulty: 'Advanced' },
  { name: 'Barbell Block Pull (3-inch Block)', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Barbell Deadlift (Hatfield Style)', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Barbell Speed Pull (60% 1RM x 3)', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Barbell Overcoming Isometric DL', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Barbell Overcoming Isometric Squat', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Yielding Isometric Squat', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Romanian to Power Shrug', category: 'weighted', subCategory: 'Traps', difficulty: 'Intermediate' },
  { name: 'Barbell Heels-Elevated Safety Bar Squat', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Barbell Safety Bar Box Squat', category: 'weighted', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Barbell Banded Box Squat', category: 'weighted', subCategory: 'Glutes', difficulty: 'Advanced' },
  { name: 'Barbell High Bar Olympic Squat', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Barbell Low Bar Squat (Slightly Wider)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Advanced' },
  { name: 'Barbell Front Squat (Pause at Bottom)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Front Squat (Crossed Arms)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Barbell Zombie Front Squat (Pause)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Pin Squat (Just Off Floor)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Safety Bar Squat (High Bar)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Barbell Safety Bar Lunge', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Barbell Safety Bar Step-Up', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Barbell Zercher Good Morning + Squat', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Barbell Hip Belt Squat (Cable Machine)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Barbell Squat with Accommodating R.', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Pause Squat (2s at Parallel)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Pause Squat (at Knee Height)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Tendon Squat (Pin at Parallel)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell 5×5 Squat (Classic)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Barbell 20-Rep Squat (Breathing)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Power Clean (Max Effort)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Barbell Clean Pull', category: 'weighted', subCategory: 'Traps', difficulty: 'Advanced' },
  { name: 'Barbell Tall Power Clean', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Barbell Hang Power Snatch', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Barbell Full Snatch', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Barbell Snatch Balance (Full)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Jerk Behind Neck', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Barbell Split Jerk (Full)', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Barbell Power Jerk', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Barbell Squat Clean (Full)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Barbell Clean and Jerk (Max)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Barbell Snatch (Max)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Barbell Behind Neck Squat', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Jerk Dip + Drive', category: 'weighted', subCategory: 'Legs', difficulty: 'Advanced' },
  { name: 'Barbell Overhead Squat (Max)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Push Press (Max Effort)', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Barbell Clean Deadlift (Full)', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Barbell Snatch Deadlift (Full)', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Barbell Tall Snatch', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Barbell Clean High Pull (Hang)', category: 'weighted', subCategory: 'Traps', difficulty: 'Advanced' },
  { name: 'Barbell Snatch High Pull (Hang)', category: 'weighted', subCategory: 'Traps', difficulty: 'Advanced' },
  { name: 'Barbell Rack Jerk', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Barbell Drop Under (Snatch)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Barbell Drop Under (Clean)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Barbell Paused Jerk Dip (3s)', category: 'weighted', subCategory: 'Legs', difficulty: 'Advanced' },
  { name: 'Dumbbell Single-Arm Press (Seated)', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Dumbbell Chest Supported Lateral Raise', category: 'weighted', subCategory: 'Lateral Deltoid', difficulty: 'Intermediate' },
  { name: 'Dumbbell Chest Supported Rear Delt Row (Neutral)', category: 'weighted', subCategory: 'Rear Deltoid', difficulty: 'Intermediate' },
  { name: 'Dumbbell Incline Row (High Angle)', category: 'weighted', subCategory: 'Upper Back', difficulty: 'Intermediate' },
  { name: 'Dumbbell Prone T-Raise (Loaded)', category: 'weighted', subCategory: 'Rear Deltoid', difficulty: 'Intermediate' },
  { name: 'Dumbbell Prone Y-Raise (Loaded)', category: 'weighted', subCategory: 'Upper Back', difficulty: 'Intermediate' },
  { name: 'Dumbbell Prone W-Raise (Loaded)', category: 'weighted', subCategory: 'Rotator Cuff', difficulty: 'Intermediate' },
  { name: 'Dumbbell Prone I-Raise (Loaded)', category: 'weighted', subCategory: 'Lats', difficulty: 'Intermediate' },
  { name: 'Dumbbell Side-Lying Rear Delt Raise', category: 'weighted', subCategory: 'Rear Deltoid', difficulty: 'Beginner' },
  { name: 'Dumbbell Lying Lateral Raise (Floor)', category: 'weighted', subCategory: 'Lateral Deltoid', difficulty: 'Intermediate' },
  { name: 'Dumbbell Incline Lateral Raise', category: 'weighted', subCategory: 'Lateral Deltoid', difficulty: 'Intermediate' },
  { name: 'Dumbbell Decline Lateral Raise', category: 'weighted', subCategory: 'Lateral Deltoid', difficulty: 'Intermediate' },
  { name: 'Dumbbell Cable-Style Rear Delt Fly', category: 'weighted', subCategory: 'Rear Deltoid', difficulty: 'Intermediate' },
  { name: 'Dumbbell Lying Cross-Body Hammer Curl', category: 'weighted', subCategory: 'Brachialis', difficulty: 'Intermediate' },
  { name: 'Dumbbell Prone Hammer Curl', category: 'weighted', subCategory: 'Brachialis', difficulty: 'Intermediate' },
  { name: 'Dumbbell Scott Curl (Short ROM Top)', category: 'weighted', subCategory: 'Biceps', difficulty: 'Intermediate' },
  { name: 'Dumbbell Waiter Curl', category: 'weighted', subCategory: 'Biceps', difficulty: 'Intermediate' },
  { name: 'Dumbbell 21s Curl', category: 'weighted', subCategory: 'Biceps', difficulty: 'Intermediate' },
  { name: 'Dumbbell Overhead Extension (EZ Grip)', category: 'weighted', subCategory: 'Triceps', difficulty: 'Beginner' },
  { name: 'Dumbbell Floor Skull Crusher', category: 'weighted', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Dumbbell JM Press', category: 'weighted', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Dumbbell 1.5 Rep Overhead Extension', category: 'weighted', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Dumbbell Tate Press (Floor)', category: 'weighted', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Dumbbell Single-Arm Overhead Extension (Kneeling)', category: 'weighted', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Dumbbell Pronated Kickback', category: 'weighted', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Dumbbell Lateral Raise (Bent-Over)', category: 'weighted', subCategory: 'Rear Deltoid', difficulty: 'Beginner' },
  { name: 'Dumbbell Front Raise (Plate Hold Simulate)', category: 'weighted', subCategory: 'Front Deltoid', difficulty: 'Beginner' },
  { name: 'Dumbbell Cuban Rotation', category: 'weighted', subCategory: 'Rotator Cuff', difficulty: 'Intermediate' },
  { name: 'Dumbbell W-Press', category: 'weighted', subCategory: 'Rear Deltoid', difficulty: 'Intermediate' },
  { name: 'Dumbbell Spider Curl (Flat Bench)', category: 'weighted', subCategory: 'Biceps', difficulty: 'Intermediate' },
  { name: 'Cable Lower Chest Fly (High Anchor)', category: 'weighted', subCategory: 'Lower Chest', difficulty: 'Intermediate' },
  { name: 'Cable Upper Chest Fly (Low Anchor)', category: 'weighted', subCategory: 'Upper Chest', difficulty: 'Intermediate' },
  { name: 'Cable Mid Chest Fly (Same Height)', category: 'weighted', subCategory: 'Chest', difficulty: 'Beginner' },
  { name: 'Cable Single-Arm Incline Press', category: 'weighted', subCategory: 'Upper Chest', difficulty: 'Intermediate' },
  { name: 'Cable Single-Arm Decline Press', category: 'weighted', subCategory: 'Lower Chest', difficulty: 'Intermediate' },
  { name: 'Cable Press (Kneeling, Low)', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Cable Press (Kneeling, High)', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Cable Lying Press (Prone)', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Cable Lat Pullover (Stiff Arm, Seated)', category: 'weighted', subCategory: 'Lats', difficulty: 'Intermediate' },
  { name: 'Cable Lat Pullover (Incline Bench)', category: 'weighted', subCategory: 'Lats', difficulty: 'Intermediate' },
  { name: 'Cable Pulldown (Behind Neck, Light)', category: 'weighted', subCategory: 'Lats', difficulty: 'Intermediate' },
  { name: 'Cable Pulldown (Half ROM Burnout)', category: 'weighted', subCategory: 'Lats', difficulty: 'Intermediate' },
  { name: 'Cable Row (Pronated, High Anchor)', category: 'weighted', subCategory: 'Upper Back', difficulty: 'Intermediate' },
  { name: 'Cable Row (Supinated, Low Anchor)', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Cable Lean-Away Row', category: 'weighted', subCategory: 'Lats', difficulty: 'Intermediate' },
  { name: 'Cable Straight-Arm Row (Seated)', category: 'weighted', subCategory: 'Lats', difficulty: 'Intermediate' },
  { name: 'Cable High Row (Prone, Low Bench)', category: 'weighted', subCategory: 'Upper Back', difficulty: 'Intermediate' },
  { name: 'Cable Single-Arm Face Pull (Supinate)', category: 'weighted', subCategory: 'Rear Deltoid', difficulty: 'Intermediate' },
  { name: 'Cable Single-Arm External Rotation (Standing)', category: 'weighted', subCategory: 'Rotator Cuff', difficulty: 'Beginner' },
  { name: 'Cable Overhead Press (Single, Low)', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Cable Lateral Raise (Both Arms, Low)', category: 'weighted', subCategory: 'Lateral Deltoid', difficulty: 'Intermediate' },
  { name: 'Cable Front Raise (Both Arms, Low)', category: 'weighted', subCategory: 'Front Deltoid', difficulty: 'Beginner' },
  { name: 'Cable Rear Delt Fly (Cross, Seated)', category: 'weighted', subCategory: 'Rear Deltoid', difficulty: 'Intermediate' },
  { name: 'Cable Rear Delt Fly (Cross, Standing)', category: 'weighted', subCategory: 'Rear Deltoid', difficulty: 'Intermediate' },
  { name: 'Cable Upright Row (Rope)', category: 'weighted', subCategory: 'Traps', difficulty: 'Intermediate' },
  { name: 'Cable Upright Row (Bar, Wide)', category: 'weighted', subCategory: 'Rear Deltoid', difficulty: 'Intermediate' },
  { name: 'Cable Hammer Curl (Both Arms)', category: 'weighted', subCategory: 'Brachialis', difficulty: 'Beginner' },
  { name: 'Cable Curl + Overhead Extension Superset', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Cable Tricep Kickback (Standing)', category: 'weighted', subCategory: 'Triceps', difficulty: 'Beginner' },
  { name: 'Cable Overhand Curl (Low Anchor)', category: 'weighted', subCategory: 'Biceps', difficulty: 'Intermediate' },
  { name: 'Pec Dec (Elbows Bent, Heavier)', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Pec Dec (Arms Straight, Light)', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Pec Dec (Pause at Stretch)', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Incline Press Machine (Full ROM)', category: 'weighted', subCategory: 'Upper Chest', difficulty: 'Beginner' },
  { name: 'Decline Press Machine (Full ROM)', category: 'weighted', subCategory: 'Lower Chest', difficulty: 'Beginner' },
  { name: 'Shoulder Press Machine (Behind Neck)', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Pulldown (Supinated, Unilateral)', category: 'weighted', subCategory: 'Lats', difficulty: 'Intermediate' },
  { name: 'Low Row Machine (Upright Torso)', category: 'weighted', subCategory: 'Lower Back', difficulty: 'Intermediate' },
  { name: 'High Row Machine (Lean Forward)', category: 'weighted', subCategory: 'Upper Back', difficulty: 'Intermediate' },
  { name: 'Chest-Supported T-Bar Row (Machine)', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Standing Calf Machine (Donkey)', category: 'weighted', subCategory: 'Calves', difficulty: 'Intermediate' },
  { name: 'Hack Squat (Pause at Bottom)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Hack Squat (1.5 Rep)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'V-Squat Machine (Pause)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Leg Curl (Bilateral, Full ROM)', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Beginner' },
  { name: 'Leg Curl (Unilateral, Paused)', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Leg Extension (Unilateral)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Adductor (Seated, Full Stretch)', category: 'weighted', subCategory: 'Inner Thighs', difficulty: 'Intermediate' },
  { name: 'Abductor (Seated, Full Stretch)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'GHD Hip Extension (Loaded)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Reverse Hyperextension (Machine)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Belt Squat (Pause + Heels Elevated)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Pendulum Squat (Pause)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Pendulum Squat (1.5 Rep)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Shoulder Abduction Machine', category: 'weighted', subCategory: 'Lateral Deltoid', difficulty: 'Beginner' },
  { name: 'Knee Flexion Machine (Short ROM)', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Beginner' },
  { name: 'Hip Thrust Machine (Pause)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Hip Flexion Machine (Standing)', category: 'weighted', subCategory: 'Hip Flexors', difficulty: 'Beginner' },
  { name: 'Kneeling Hip Flexion Machine', category: 'weighted', subCategory: 'Hip Flexors', difficulty: 'Beginner' },
  { name: 'Rear Delt Machine (Elbows Wide)', category: 'weighted', subCategory: 'Rear Deltoid', difficulty: 'Beginner' },
  { name: 'Earthquake Bar Bench Press', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Earthquake Bar Overhead Press', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Camber Bar Squat (Wide Stance)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Advanced' },
  { name: 'Safety Bar Squat (Narrow Stance)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Safety Bar Pause Squat', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Safety Bar Walking Lunge', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Safety Bar Split Squat', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Safety Bar Step-Down', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Log Clean and Press (Comp Style)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Log Strict Press', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Log Push Press', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Circus Dumbbell Clean', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Husafell Stone Carry', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Keg to Shoulder', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Keg Overhead Press', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Atlas Stone Deadlift', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Stone Over Bar (55-inch)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Axle Continental Clean', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Axle Push Press (Clean to Press)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Frame Deadlift', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Frame Walk (Competition)', category: 'weighted', subCategory: 'Grip', difficulty: 'Advanced' },
  { name: 'Kettlebell Alternating Snatch', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Kettlebell Double Swing', category: 'weighted', subCategory: 'Glutes', difficulty: 'Advanced' },
  { name: 'Kettlebell Double Deadlift', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Kettlebell Double Press (Seated)', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Kettlebell Double Row', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Kettlebell Suitcase Deadlift', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Kettlebell Staggered Deadlift', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Kettlebell Deadlift + Lateral Lunge', category: 'weighted', subCategory: 'Inner Thighs', difficulty: 'Intermediate' },
  { name: 'Kettlebell Lateral Deadlift', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Sandbag Clean', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Sandbag Press', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Sandbag Squat to Press', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Sandbag RDL', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Sandbag Lunge', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Sandbag Row', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'D-Ball Row', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'D-Ball Squat to Shoulder', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'D-Ball Burpee', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'D-Ball Lateral Slam', category: 'weighted', subCategory: 'Obliques', difficulty: 'Advanced' },
  { name: 'D-Ball Turkish Get-Up', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Plate Complex: Squat-Curl-Press', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Plate Complex: Lunge-Raise-Chop', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Plate Overhead Carry', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Plate Zercher Carry', category: 'weighted', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Barbell Hip Thrust (Velocity-Based)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Advanced' },
  { name: 'Trap Bar Deadlift (Velocity-Based)', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Barbell Bench (Touch-and-Go, Speed)', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Dumbbell Total Body Explosive Press', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'KB Complex for Sport (5 Exercises)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Olympic Lifting Warm-Up Sequence', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Power Development Barbell Complex', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Speed Squat (Bands, 50% 1RM)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Speed Deadlift (Chains, 60%)', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Speed Bench (Bands, 50%)', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Max Effort Squat Variation (Weekly)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Max Effort Deadlift Variation', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Max Effort Press Variation', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Dynamic Effort Lower Day', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Dynamic Effort Upper Day', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Conjugate Method Accessory Block', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Westside Barbell Box Squat Protocol', category: 'weighted', subCategory: 'Glutes', difficulty: 'Advanced' },
  { name: 'Westside Speed Bench Protocol', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: '5/3/1 Main Lift (Squat Week 1)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: '5/3/1 Main Lift (Deadlift Week 2)', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: '5/3/1 Main Lift (Bench Week 3)', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: '5/3/1 Main Lift (OHP Week 4)', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'GZCLP Tier 1 Lift', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'GZCLP Tier 2 Lift', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'GZCLP Tier 3 Lift', category: 'weighted', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Lateral Box Shuffle', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Beginner' },
  { name: 'Skipping with Arm Swing', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Beginner' },
  { name: 'March with Trunk Lean', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Beginner' },
  { name: 'High Kick Walk', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Beginner' },
  { name: 'Cross-Step Walk', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Beginner' },
  { name: 'Lateral Skip', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Beginner' },
  { name: 'Power Skip Height Focus', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Intermediate' },
  { name: 'Power Skip Distance Focus', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Intermediate' },
  { name: 'Single-Leg Skip', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Backward Skip', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Scissor Lunge Pulse', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Standing Groin Stretch Active', category: 'bodyweight', subCategory: 'Inner Thighs', difficulty: 'Beginner' },
  { name: 'Standing Hip Flexor Pulse', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Beginner' },
  { name: 'Side-to-Side Weight Shift', category: 'bodyweight', subCategory: 'Inner Thighs', difficulty: 'Beginner' },
  { name: 'Quick-Step Ladder BW', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'Running A-Skip', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Beginner' },
  { name: 'Running B-Skip', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Running C-Skip', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Intermediate' },
  { name: 'Arm Circle Drill Large', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Arm Circle Drill Small', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Vertical Arm Swing Drill', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Horizontal Arm Drive Drill', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Sprinters Start Drill', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Knee Drive Pop', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Intermediate' },
  { name: 'Triple Extension Jump', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Advanced' },
  { name: 'Reactive Shuffle Low Position', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Box Shuffle with Arm Drive', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'Lateral Cone Hop Continuous', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Intermediate' },
  { name: 'Star Drill 5-Point', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Y-Drill 3-Point', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Beginner' },
  { name: 'Reactive Lunge Sprint', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Broad Jump to Lateral Bound', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Advanced' },
  { name: 'Lateral Broad Jump Alternating', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Advanced' },
  { name: 'Hurdle Walkovers', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Beginner' },
  { name: 'Hurdle Side Step', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Beginner' },
  { name: 'Two-Leg Hurdle Jump', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Intermediate' },
  { name: 'Single-Leg Hurdle Hop', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Advanced' },
  { name: 'Barbell OHP Seated Strict', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Barbell OHP Behind Neck Light', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Barbell OHP 5s Eccentric', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Barbell OHP Paused at Bottom', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Barbell Seated Tricep Extension', category: 'weighted', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Dumbbell Press Alternating Seated', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Dumbbell Press Neutral Standing', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Dumbbell Press Wide Elbows Seated', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Dumbbell Press Iso Single Arm Seated', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Cable Z-Press', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Cable High Lateral Raise', category: 'weighted', subCategory: 'Lateral Deltoid', difficulty: 'Intermediate' },
  { name: 'Cable Low Lateral Raise Elbow Lead', category: 'weighted', subCategory: 'Lateral Deltoid', difficulty: 'Intermediate' },
  { name: 'Cable 90-Degree Lateral Raise Hold', category: 'weighted', subCategory: 'Lateral Deltoid', difficulty: 'Intermediate' },
  { name: 'Cable External Rotation D-Ring', category: 'weighted', subCategory: 'Rotator Cuff', difficulty: 'Beginner' },
  { name: 'Cable Internal Rotation D-Ring', category: 'weighted', subCategory: 'Rotator Cuff', difficulty: 'Beginner' },
  { name: 'Machine Lateral Raise Elbow Pad', category: 'weighted', subCategory: 'Lateral Deltoid', difficulty: 'Beginner' },
  { name: 'Machine Rear Delt Elbow Pad', category: 'weighted', subCategory: 'Rear Deltoid', difficulty: 'Beginner' },
  { name: 'Machine Front Raise', category: 'weighted', subCategory: 'Front Deltoid', difficulty: 'Beginner' },
  { name: 'Barbell Preacher Curl Wide', category: 'weighted', subCategory: 'Biceps', difficulty: 'Intermediate' },
  { name: 'Barbell Preacher Curl Narrow', category: 'weighted', subCategory: 'Biceps', difficulty: 'Intermediate' },
  { name: 'Barbell Reverse Preacher Curl', category: 'weighted', subCategory: 'Brachialis', difficulty: 'Intermediate' },
  { name: 'Barbell Standing Curl 5s Eccentric', category: 'weighted', subCategory: 'Biceps', difficulty: 'Intermediate' },
  { name: 'Barbell Isometric Curl Hold 90', category: 'weighted', subCategory: 'Biceps', difficulty: 'Intermediate' },
  { name: 'EZ Bar Reverse Curl Full ROM', category: 'weighted', subCategory: 'Brachialis', difficulty: 'Beginner' },
  { name: 'Dumbbell Alternate Curl Supinating', category: 'weighted', subCategory: 'Biceps', difficulty: 'Beginner' },
  { name: 'Dumbbell Incline Neutral Curl', category: 'weighted', subCategory: 'Brachialis', difficulty: 'Intermediate' },
  { name: 'Dumbbell Spider Curl Steep Incline', category: 'weighted', subCategory: 'Biceps', difficulty: 'Intermediate' },
  { name: 'Cable Curl Seated Low Anchor', category: 'weighted', subCategory: 'Biceps', difficulty: 'Beginner' },
  { name: 'Cable Curl Standing High Anchor', category: 'weighted', subCategory: 'Biceps', difficulty: 'Intermediate' },
  { name: 'Cable Bayesian Curl Max Stretch', category: 'weighted', subCategory: 'Biceps', difficulty: 'Advanced' },
  { name: 'Machine Curl Incline', category: 'weighted', subCategory: 'Biceps', difficulty: 'Beginner' },
  { name: 'Machine Preacher Full ROM', category: 'weighted', subCategory: 'Biceps', difficulty: 'Beginner' },
  { name: 'Barbell Skull Crusher Wide', category: 'weighted', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Barbell Skull Crusher Narrow', category: 'weighted', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Barbell Close-Grip Skull Crusher Combo', category: 'weighted', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'EZ Bar Skull Crusher 5s Eccentric', category: 'weighted', subCategory: 'Triceps', difficulty: 'Advanced' },
  { name: 'EZ Bar JM Press', category: 'weighted', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Dumbbell Skull Crusher Floor', category: 'weighted', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Dumbbell Cross-Face Extension', category: 'weighted', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Cable Tricep Pressdown Underhand Bar', category: 'weighted', subCategory: 'Triceps', difficulty: 'Beginner' },
  { name: 'Cable Tricep Pressdown Neutral Handle', category: 'weighted', subCategory: 'Triceps', difficulty: 'Beginner' },
  { name: 'Cable Overhead Extension Wide Grip', category: 'weighted', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Machine Tricep Extension Unilateral', category: 'weighted', subCategory: 'Triceps', difficulty: 'Beginner' },
  { name: 'Barbell Deadlift 5x5 Classic', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Barbell Squat 5x5 Classic', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Barbell Bench 5x5 Classic', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Barbell OHP 5x5 Classic', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Barbell Bent Row 5x5 Classic', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Barbell Deadlift 3x3 Heavy', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Barbell Squat 3x3 Heavy', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Bench 3x3 Heavy', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Barbell Deadlift 1RM Attempt', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Barbell Squat 1RM Attempt', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Bench 1RM Attempt', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Barbell OHP 1RM Attempt', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Dumbbell Row Heavy Elbow Back', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Dumbbell Row Light Elbow Wide', category: 'weighted', subCategory: 'Upper Back', difficulty: 'Beginner' },
  { name: 'Dumbbell Row Neutral Mid', category: 'weighted', subCategory: 'Back', difficulty: 'Beginner' },
  { name: 'Dumbbell Row Supported on Bench', category: 'weighted', subCategory: 'Back', difficulty: 'Beginner' },
  { name: 'Cable Row Elbows Flared', category: 'weighted', subCategory: 'Upper Back', difficulty: 'Intermediate' },
  { name: 'Cable Row Elbows Tucked', category: 'weighted', subCategory: 'Lats', difficulty: 'Intermediate' },
  { name: 'Cable Row Seated Pause at Peak', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Barbell Squat to Hip Thrust Giant Set', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Barbell Deadlift to Row Giant Set', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Barbell Bench to Fly Giant Set', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Barbell Press to Lateral Raise Giant Set', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Barbell Curl to Hammer Curl Giant Set', category: 'weighted', subCategory: 'Biceps', difficulty: 'Intermediate' },
  { name: 'Dumbbell Incline Press Fly Superset', category: 'weighted', subCategory: 'Upper Chest', difficulty: 'Intermediate' },
  { name: 'Dumbbell Row Face Pull Superset', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Cable Pulldown Straight-Arm Superset', category: 'weighted', subCategory: 'Lats', difficulty: 'Intermediate' },
  { name: 'Cable Curl Pushdown Superset', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Machine Chest Cable Fly Superset', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Loaded Carry Circuit Farmer-Suitcase-OH', category: 'weighted', subCategory: 'Grip', difficulty: 'Advanced' },
  { name: 'Loaded Carry Circuit KB Rack-Overhead', category: 'weighted', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Loaded Carry Circuit Plate Overhead-Hug', category: 'weighted', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Loaded Carry Circuit Sandbag-D-Ball', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Battle Rope HIIT 6 Patterns', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Battle Rope Strength Heavy Anchor', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Battle Rope Speed Light Anchor', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Battle Rope Seated Waves', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Resistance Band Full-Body Circuit', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Resistance Band Lower Body Circuit', category: 'weighted', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Resistance Band Upper Body Circuit', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Resistance Band Core Circuit', category: 'weighted', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'BFR Full Body Circuit', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'BFR Upper Body Circuit', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'BFR Lower Body Circuit', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Velocity-Based Training Squat Block', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Velocity-Based Training Bench Block', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Velocity-Based Training Deadlift Block', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Eccentric Overload Squat', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Eccentric Overload Bench', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Eccentric Overload Row', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Accommodating Resistance Squat Chains', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Accommodating Resistance Bench Chains', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Accommodating Resistance OHP Bands', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Accommodating Resistance Hip Thrust', category: 'weighted', subCategory: 'Glutes', difficulty: 'Advanced' },
  { name: 'Partial ROM Squat Top Third', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Partial ROM Deadlift Top Third', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Partial ROM Bench Top Third', category: 'weighted', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Full ROM Back Squat Deep', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Full ROM Deadlift Max Stretch', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Full ROM Bench Press Deep Stretch', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Full ROM Overhead Press Deep Stretch', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Dumbbell Press Full ROM Floor', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Dumbbell Lateral Raise Full ROM Slow', category: 'weighted', subCategory: 'Lateral Deltoid', difficulty: 'Intermediate' },
  { name: 'Rest-Pause Squat Heavy', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Rest-Pause Deadlift Heavy', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Rest-Pause Bench Heavy', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Rest-Pause OHP Heavy', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Myo-Rep Hip Thrust', category: 'weighted', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Myo-Rep Romanian Deadlift', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Myo-Rep Dumbbell Row', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Myo-Rep Cable Fly', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Cluster Set Bulgarian Split Squat', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Cluster Set Romanian Deadlift', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Advanced' },
  { name: 'Cluster Set Hip Thrust', category: 'weighted', subCategory: 'Glutes', difficulty: 'Advanced' },
  { name: 'Cluster Set Dumbbell Row', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Cluster Set Lateral Raise', category: 'weighted', subCategory: 'Lateral Deltoid', difficulty: 'Intermediate' },
  { name: '5-3-1 Squat Week 1 Joker Set', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: '5-3-1 Deadlift Week 2 Joker Set', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: '5-3-1 Bench Week 3 Joker Set', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: '5-3-1 OHP Week 4 Joker Set', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: '5-3-1 First Set Last (FSL)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: '5-3-1 Boring But Big Squat', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: '5-3-1 Boring But Big Deadlift', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: '5-3-1 Boring But Big Bench', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: '5-3-1 Boring But Big OHP', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'PHUL Upper Power Day', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'PHUL Lower Power Day', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'PHUL Upper Hypertrophy Day', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'PHUL Lower Hypertrophy Day', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'PHAT Upper Power Day', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'PHAT Lower Power Day', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'PHAT Upper Hypertrophy Day', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'PHAT Lower Hypertrophy Day', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'PPL Push Day A', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'PPL Pull Day A', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'PPL Legs Day A', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'PPL Push Day B', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'PPL Pull Day B', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'PPL Legs Day B', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Upper Lower Split Upper Day A', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Upper Lower Split Lower Day A', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Upper Lower Split Upper Day B', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Upper Lower Split Lower Day B', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Full Body Day A Classic', category: 'weighted', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Full Body Day B Classic', category: 'weighted', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Full Body Day C Classic', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Morning Mobility Sun Salutation Flow', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Barbell Row Supinated 3x10', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Dumbbell Pullover Lat Focused', category: 'weighted', subCategory: 'Lats', difficulty: 'Intermediate' },
  { name: 'Cable Single-Arm Lat Stretch Pulldown', category: 'weighted', subCategory: 'Lats', difficulty: 'Intermediate' },
  { name: 'Machine Row Iso Hold at Peak', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Barbell Hip Thrust Eccentric 3s', category: 'weighted', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Dumbbell RDL Slow Eccentric 5s', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
];