// CSV Exercise Pool Batch 6 — exercises 5001–6000
export const CSV_EXERCISES_BATCH6 = [
  { name: 'Dead Bug with Arm Reach Only', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Dead Bug with Leg Extend Only', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Dead Bug with Arm + Leg Extend', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Dead Bug with Band Resist', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Pallof Press ISO Hold (No Weight)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'McGill Curl-Up (Hands Under Back)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'McGill Side Bridge (Short)', category: 'bodyweight', subCategory: 'Obliques', difficulty: 'Beginner' },
  { name: 'McGill Side Bridge (Long)', category: 'bodyweight', subCategory: 'Obliques', difficulty: 'Intermediate' },
  { name: 'McGill Bird Dog (Slow)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'McGill Bird Dog (3-Point)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Segmental Rolling Drill', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Hip Hinge with Dowel (Wall)', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Beginner' },
  { name: 'Thoracic Extension over Roller', category: 'bodyweight', subCategory: 'Thoracic Spine', difficulty: 'Beginner' },
  { name: 'Seated Thoracic Rotation (Hands Behind Head)', category: 'bodyweight', subCategory: 'Thoracic Spine', difficulty: 'Beginner' },
  { name: 'Open Book Stretch (Side-Lying)', category: 'bodyweight', subCategory: 'Thoracic Spine', difficulty: 'Beginner' },
  { name: 'Apley Scratch Test Mobility', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Neck Half Circle (Safe)', category: 'bodyweight', subCategory: 'Neck', difficulty: 'Beginner' },
  { name: 'Neck Lateral Tilt + Rotation', category: 'bodyweight', subCategory: 'Neck', difficulty: 'Beginner' },
  { name: 'Lumbar Rotation (Knees Together)', category: 'bodyweight', subCategory: 'Lower Back', difficulty: 'Beginner' },
  { name: 'Lumbar Side Bend Stretch', category: 'bodyweight', subCategory: 'Lower Back', difficulty: 'Beginner' },
  { name: 'Standing Cat-Cow', category: 'bodyweight', subCategory: 'Lower Back', difficulty: 'Beginner' },
  { name: 'Supported Deep Squat Hold (60s)', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Beginner' },
  { name: 'Squat to Stand Mobilization', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Beginner' },
  { name: 'Shin Box Hip Switch (Controlled)', category: 'bodyweight', subCategory: 'Hip Rotators', difficulty: 'Intermediate' },
  { name: 'Shin Box Hip Switch (Fast)', category: 'bodyweight', subCategory: 'Hip Rotators', difficulty: 'Advanced' },
  { name: 'Band Pull-Apart (Overhand)', category: 'bodyweight', subCategory: 'Rear Deltoid', difficulty: 'Beginner' },
  { name: 'Band Pull-Apart (Underhand)', category: 'bodyweight', subCategory: 'Lower Traps', difficulty: 'Beginner' },
  { name: 'Band Pull-Apart (Overhead)', category: 'bodyweight', subCategory: 'Lower Traps', difficulty: 'Intermediate' },
  { name: 'Prone Snow Angel', category: 'bodyweight', subCategory: 'Lower Traps', difficulty: 'Beginner' },
  { name: 'Prone Blackburn (Full Circuit)', category: 'bodyweight', subCategory: 'Rear Deltoid', difficulty: 'Intermediate' },
  { name: 'Sleeper Stretch', category: 'bodyweight', subCategory: 'Rotator Cuff', difficulty: 'Beginner' },
  { name: 'Cross-Body Shoulder Stretch', category: 'bodyweight', subCategory: 'Rear Deltoid', difficulty: 'Beginner' },
  { name: 'Doorway Pec Stretch', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Beginner' },
  { name: 'Wall Slide (Arms Overhead)', category: 'bodyweight', subCategory: 'Lower Traps', difficulty: 'Beginner' },
  { name: 'Wall Angel (Foam Roller)', category: 'bodyweight', subCategory: 'Thoracic Spine', difficulty: 'Intermediate' },
  { name: 'Overhead Reach + Rib Depression', category: 'bodyweight', subCategory: 'Lats', difficulty: 'Beginner' },
  { name: 'Serratus Punch (Wall)', category: 'bodyweight', subCategory: 'Serratus Anterior', difficulty: 'Beginner' },
  { name: 'Serratus Punch (Floor, Prone)', category: 'bodyweight', subCategory: 'Serratus Anterior', difficulty: 'Intermediate' },
  { name: 'Y-T-W-L Prone on Bench', category: 'bodyweight', subCategory: 'Lower Traps', difficulty: 'Intermediate' },
  { name: 'Shoulder Shrug + Retract + Depress', category: 'bodyweight', subCategory: 'Traps', difficulty: 'Beginner' },
  { name: 'Rotator Cuff ER (Side-Lying)', category: 'bodyweight', subCategory: 'Rotator Cuff', difficulty: 'Beginner' },
  { name: 'Rotator Cuff IR (Side-Lying)', category: 'bodyweight', subCategory: 'Rotator Cuff', difficulty: 'Beginner' },
  { name: 'Pendulum Swing (Codman\'s)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Beginner' },
  { name: 'Shoulder Capsule Distraction', category: 'bodyweight', subCategory: 'Rotator Cuff', difficulty: 'Beginner' },
  { name: 'Bent-Over T-Raise (Arms Straight)', category: 'bodyweight', subCategory: 'Rear Deltoid', difficulty: 'Intermediate' },
  { name: 'Terminal Knee Extension (Band)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Straight-Leg Raise (Floor)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Short Arc Quad (Supine)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Long Arc Quad (Seated)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Quad Set (Supine Isometric)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'VMO Drop Lunge', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Step-Down (Slow Eccentric)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Lateral Step-Down (Eccentric)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Single-Leg Sit-to-Stand (Low Chair)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'ACL Tuck Landing (Safety)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Landing Mechanics Drill (Single-Leg)', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Intermediate' },
  { name: 'Band-Resisted Squat (Knee Cave Fix)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Hip Abduction + Clamshell Combo', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Monster Walk Forward + Back', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Quad Stretch (Standing + Wall)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Gastroc Stretch (Wall)', category: 'bodyweight', subCategory: 'Calves', difficulty: 'Beginner' },
  { name: 'Hip 90/90 External Rotation Hold', category: 'bodyweight', subCategory: 'Hip Rotators', difficulty: 'Beginner' },
  { name: 'Hip 90/90 Internal Rotation Hold', category: 'bodyweight', subCategory: 'Hip Rotators', difficulty: 'Beginner' },
  { name: 'Hip 90/90 Forward Fold', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Hip 90/90 Lift-Off (ER)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Hip 90/90 Lift-Off (IR)', category: 'bodyweight', subCategory: 'Hip Rotators', difficulty: 'Intermediate' },
  { name: 'Hip CARs (Full Circle)', category: 'bodyweight', subCategory: 'Hip Rotators', difficulty: 'Intermediate' },
  { name: 'Hip PAILs and RAILs (Full)', category: 'bodyweight', subCategory: 'Hip Rotators', difficulty: 'Advanced' },
  { name: 'Pancake Stretch (Seated Wide)', category: 'bodyweight', subCategory: 'Inner Thighs', difficulty: 'Intermediate' },
  { name: 'Half-Kneeling Hip Flexor PNF', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Intermediate' },
  { name: 'Pigeon Pose + Hip Twist', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Figure-4 Stretch (Supine)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Modified Hurdler Stretch', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Beginner' },
  { name: 'Active Straight-Leg Lift (Hip Flex)', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Butterfly + Posterior Tilt', category: 'bodyweight', subCategory: 'Inner Thighs', difficulty: 'Beginner' },
  { name: 'Lateral Hip Flexor Stretch', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Intermediate' },
  { name: 'TFL Stretch (Side-Lying)', category: 'bodyweight', subCategory: 'TFL', difficulty: 'Beginner' },
  { name: 'IT Band Foam Roll (Slow)', category: 'bodyweight', subCategory: 'IT Band', difficulty: 'Beginner' },
  { name: 'Piriformis Stretch (Seated Twist)', category: 'bodyweight', subCategory: 'Piriformis', difficulty: 'Beginner' },
  { name: 'Ankle Alphabets (Air Writing)', category: 'bodyweight', subCategory: 'Ankles', difficulty: 'Beginner' },
  { name: 'Ankle Circle CARs', category: 'bodyweight', subCategory: 'Ankles', difficulty: 'Beginner' },
  { name: 'Ankle Dorsiflexion Wall Lunge', category: 'bodyweight', subCategory: 'Ankles', difficulty: 'Beginner' },
  { name: 'Ankle Dorsiflexion (Kneeling)', category: 'bodyweight', subCategory: 'Ankles', difficulty: 'Beginner' },
  { name: 'Ankle Eversion Stretch', category: 'bodyweight', subCategory: 'Peroneal', difficulty: 'Beginner' },
  { name: 'Ankle Inversion Stretch', category: 'bodyweight', subCategory: 'Tibialis Posterior', difficulty: 'Beginner' },
  { name: 'Calf Stretch (Bent Knee, Soleus)', category: 'bodyweight', subCategory: 'Soleus', difficulty: 'Beginner' },
  { name: 'Plantar Fascia Stretch (Sitting)', category: 'bodyweight', subCategory: 'Plantar Fascia', difficulty: 'Beginner' },
  { name: 'Toe Extension Stretch (Kneeling)', category: 'bodyweight', subCategory: 'Plantar Fascia', difficulty: 'Beginner' },
  { name: 'Single-Leg Balance Eyes Closed', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Intermediate' },
  { name: 'Single-Leg Balance on Foam', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Intermediate' },
  { name: 'Leapfrog Jump', category: 'bodyweight', subCategory: 'Plyometrics', difficulty: 'Beginner' },
  { name: 'Hopscotch Pattern', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Beginner' },
  { name: 'Animal Walk Relay', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Jump Rope Basics (Single Under)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Beginner' },
  { name: 'Qi Gong Eight Brocades (Full Set)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Qi Gong Five Animals (Full)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Qi Gong Shaking Practice', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Chest Dip (Forward Lean)', category: 'bodyweight', subCategory: 'Lower Chest', difficulty: 'Intermediate' },
  { name: 'Tricep Dip (Upright Body)', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Beginner' },
  { name: 'Diamond Push-Up (Knees)', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Beginner' },
  { name: 'Close-Grip Incline Push-Up', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Decline Diamond Push-Up', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Advanced' },
  { name: 'Pike Push-Up to Full Extension', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Tuck Planche Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Straddle Planche Push-Up', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Wall-Supported Handstand Dip', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Chin-Up (Full Supination)', category: 'bodyweight', subCategory: 'Biceps', difficulty: 'Intermediate' },
  { name: 'Neutral Grip Pull-Up', category: 'bodyweight', subCategory: 'Brachialis', difficulty: 'Intermediate' },
  { name: 'Behind-Neck Pull-Up (Light)', category: 'bodyweight', subCategory: 'Lats', difficulty: 'Advanced' },
  { name: 'Close-Grip Chin-Up (BW)', category: 'bodyweight', subCategory: 'Biceps', difficulty: 'Intermediate' },
  { name: 'Towel Chin-Up', category: 'bodyweight', subCategory: 'Biceps', difficulty: 'Advanced' },
  { name: 'L-Sit Chin-Up', category: 'bodyweight', subCategory: 'Biceps', difficulty: 'Advanced' },
  { name: 'Ring Chin-Up (Full Supination)', category: 'bodyweight', subCategory: 'Biceps', difficulty: 'Intermediate' },
  { name: 'Ring Wide Pull-Up', category: 'bodyweight', subCategory: 'Lats', difficulty: 'Advanced' },
  { name: 'Ring Archer Row (BW)', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Ring False Grip Pull-Up', category: 'bodyweight', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Reactive Step Tap (Forward)', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Intermediate' },
  { name: 'Reactive Step Tap (Lateral)', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Intermediate' },
  { name: 'Reactive Step Tap (Backward)', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Intermediate' },
  { name: 'Eyes-Closed Tandem Walk', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Advanced' },
  { name: 'Foam Pad Tandem Walk', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Intermediate' },
  { name: 'Figure-8 Walk', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Beginner' },
  { name: 'Clock Reach (Single-Leg)', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Intermediate' },
  { name: 'Star Excursion Balance Test', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Advanced' },
  { name: 'Reach Test (Modified)', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Intermediate' },
  { name: 'Sciatic Nerve Glide (Seated)', category: 'bodyweight', subCategory: 'Sciatic Nerve', difficulty: 'Beginner' },
  { name: 'Sciatic Nerve Glide (Standing)', category: 'bodyweight', subCategory: 'Sciatic Nerve', difficulty: 'Beginner' },
  { name: 'Median Nerve Glide (Arm)', category: 'bodyweight', subCategory: 'Median Nerve', difficulty: 'Beginner' },
  { name: 'Forward Roll to Stand', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Backward Roll to Stand', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Dive Roll (Forward)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Roundoff Rebound', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Front Aerial (One-Arm Cartwheel)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Butterfly Kick (Martial Arts)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: '540 Kick (Martial Arts)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Butterfly Twist', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Murph Workout (Pull-Push-Squat-Run)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Cindy AMRAP 20min', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Barbara (5 Rounds)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Angie (100s Each)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: '100 Burpees For Time', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Lacrosse Ball Glute Smash', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Lacrosse Ball Pec Minor', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Beginner' },
  { name: 'Lacrosse Ball Thoracic Spine', category: 'bodyweight', subCategory: 'Thoracic Spine', difficulty: 'Beginner' },
  { name: 'Lacrosse Ball Calf', category: 'bodyweight', subCategory: 'Calves', difficulty: 'Beginner' },
  { name: 'Lacrosse Ball Plantar Fascia', category: 'bodyweight', subCategory: 'Plantar Fascia', difficulty: 'Beginner' },
  { name: 'Foam Roll Quads (Slow)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Foam Roll IT Band (Slow)', category: 'bodyweight', subCategory: 'IT Band', difficulty: 'Beginner' },
  { name: 'Foam Roll Lats', category: 'bodyweight', subCategory: 'Lats', difficulty: 'Beginner' },
  { name: 'Foam Roll Upper Back (Cross Arms)', category: 'bodyweight', subCategory: 'Thoracic Spine', difficulty: 'Beginner' },
  { name: 'Foam Roll Adductors', category: 'bodyweight', subCategory: 'Inner Thighs', difficulty: 'Beginner' },
  { name: 'Foam Roll Hamstrings', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Beginner' },
  { name: 'Pilates Hundred (Full)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Pilates Roll-Up (Full)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Pilates One-Leg Circle', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Beginner' },
  { name: 'Pilates Rolling Like a Ball', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Pilates Single-Leg Stretch', category: 'bodyweight', subCategory: 'Core', difficulty: 'Beginner' },
  { name: 'Pilates Double-Leg Stretch', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Pilates Scissors', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Pilates Criss-Cross (Oblique)', category: 'bodyweight', subCategory: 'Obliques', difficulty: 'Intermediate' },
  { name: 'Pilates Spine Stretch (Seated)', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Beginner' },
  { name: 'Pilates Saw', category: 'bodyweight', subCategory: 'Obliques', difficulty: 'Intermediate' },
  { name: 'Pilates Swan (Full)', category: 'bodyweight', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Pilates Single-Leg Kick', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Beginner' },
  { name: 'Pilates Double-Leg Kick', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Pilates Leg Pull (Prone)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Ladder: Two In / Two Out', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'Ladder: Icky Shuffle', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'Ladder: In-In-Out-Out (Lateral)', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'Ladder: Ali Shuffle', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Advanced' },
  { name: 'Ladder: One-Leg Hop Through', category: 'bodyweight', subCategory: 'Balance', difficulty: 'Advanced' },
  { name: 'Ladder: Carioca (Crossover)', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'Ladder: Backward Run', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'Ladder: Side Shuffle (Both Ways)', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'Ladder: Hip Turn 90°', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'Cone Drill: 5-10-5 (Pro Agility)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Cone Drill: W-Drill', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Cone Drill: Box (4 Corners)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Cone Drill: Figure-8 Sprint', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Cone Drill: 3-Cone L', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Glute Ham Raise Negative', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Advanced' },
  { name: 'Glute Ham Raise Full ROM', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Advanced' },
  { name: 'Back Extension (45°, Bodyweight)', category: 'bodyweight', subCategory: 'Lower Back', difficulty: 'Beginner' },
  { name: 'Reverse Hyper (BW, Flat Bench)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Hip Circle (Standing, Large)', category: 'bodyweight', subCategory: 'Hip Rotators', difficulty: 'Beginner' },
  { name: 'Hip Circle (Quadruped)', category: 'bodyweight', subCategory: 'Hip Rotators', difficulty: 'Beginner' },
  { name: 'Spine Wave (Standing, Slow)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Pop-Up (Yoga Press)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Handstand Pirouette (Quarter Turn)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Handstand Pirouette (Half Turn)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Press Handstand (From Straddle Sit)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'HS Walk (Staircase Up)', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'One-Arm Push-Up Negative (5s)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'One-Arm Push-Up Assisted (Band)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'One-Arm Push-Up (Full ROM)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Spiderman Reach (Lunge + Reach)', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Intermediate' },
  { name: 'World\'s Greatest Stretch (Circuit)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Deep Squat + Hip Rotation', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Beginner' },
  { name: 'Deep Squat + Overhead Reach', category: 'bodyweight', subCategory: 'Thoracic Spine', difficulty: 'Beginner' },
  { name: 'Ankle Banded Walk (Forward)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Ankle Banded Walk (Lateral)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Standing Hip Flexor Drill (March)', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Beginner' },
  { name: 'Standing Hamstring Curl (BW)', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Standing Leg Swing (Forward-Back)', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Beginner' },
  { name: 'Standing Leg Swing (Lateral)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Standing Hip Extension Pulse', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Standing Hip Abduction Pulse', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Standing Hip Internal Rotation', category: 'bodyweight', subCategory: 'Hip Rotators', difficulty: 'Beginner' },
  { name: 'Standing Hip External Rotation', category: 'bodyweight', subCategory: 'Hip Rotators', difficulty: 'Beginner' },
  { name: 'Standing Thoracic Rotation (Arms Out)', category: 'bodyweight', subCategory: 'Thoracic Spine', difficulty: 'Beginner' },
  { name: 'Standing Side Bend + Reach', category: 'bodyweight', subCategory: 'Obliques', difficulty: 'Beginner' },
  { name: 'Standing Lat Stretch (Overhead)', category: 'bodyweight', subCategory: 'Lats', difficulty: 'Beginner' },
  { name: 'Smith Machine Bench Press (Arch)', category: 'weighted', subCategory: 'Chest', difficulty: 'Beginner' },
  { name: 'Smith Machine Incline (45°)', category: 'weighted', subCategory: 'Upper Chest', difficulty: 'Beginner' },
  { name: 'Smith Machine Decline Press', category: 'weighted', subCategory: 'Lower Chest', difficulty: 'Beginner' },
  { name: 'Smith Machine OHP (Standing)', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Smith Machine Bent-Over Row', category: 'weighted', subCategory: 'Back', difficulty: 'Beginner' },
  { name: 'Smith Machine Underhand Row', category: 'weighted', subCategory: 'Back', difficulty: 'Beginner' },
  { name: 'Smith Machine Good Morning', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Smith Machine Hip Thrust (Wide)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Smith Machine Romanian DL', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Beginner' },
  { name: 'Smith Machine Front Squat', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Smith Machine Drag Curl', category: 'weighted', subCategory: 'Biceps', difficulty: 'Intermediate' },
  { name: 'Smith Machine Close-Grip Bench', category: 'weighted', subCategory: 'Triceps', difficulty: 'Intermediate' },
  { name: 'Smith Machine Inverted Row', category: 'weighted', subCategory: 'Back', difficulty: 'Beginner' },
  { name: 'Cable Chest Press (Single, Pec Flex)', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Cable Fly (Decline Angle, Low to High)', category: 'weighted', subCategory: 'Upper Chest', difficulty: 'Intermediate' },
  { name: 'Cable Fly (Incline Angle, High to Low)', category: 'weighted', subCategory: 'Lower Chest', difficulty: 'Intermediate' },
  { name: 'Cable Cross Fly (Mid, Both Arms)', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Cable Squat (Low Anchor)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Cable Good Morning (Low Anchor)', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Cable Hip Extension (Standing)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Cable Hip Flexion (Standing)', category: 'weighted', subCategory: 'Hip Flexors', difficulty: 'Beginner' },
  { name: 'Cable Adduction (Standing)', category: 'weighted', subCategory: 'Inner Thighs', difficulty: 'Beginner' },
  { name: 'Cable Abduction (Standing)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Cable Crunch (Kneeling, Heavy)', category: 'weighted', subCategory: 'Abs', difficulty: 'Intermediate' },
  { name: 'Cable Crunch (Side-Lying)', category: 'weighted', subCategory: 'Obliques', difficulty: 'Intermediate' },
  { name: 'Cable Oblique Crunch (Kneeling)', category: 'weighted', subCategory: 'Obliques', difficulty: 'Intermediate' },
  { name: 'Cable Wood Chop (High to Low)', category: 'weighted', subCategory: 'Obliques', difficulty: 'Intermediate' },
  { name: 'Cable Wood Chop (Low to High)', category: 'weighted', subCategory: 'Obliques', difficulty: 'Intermediate' },
  { name: 'Cable Pallof Press (Tall Kneeling)', category: 'weighted', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Cable Pallof Press (Half Kneeling)', category: 'weighted', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Cable Anti-Rotation (Walking)', category: 'weighted', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Barbell Squat (1-1/2 Rep Method)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Squat (With Tempo 4-1-1-0)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Barbell Squat (1RM + 3 Drop Sets)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Squat (8x3 Submaximal)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Front Squat + Back Squat Combo', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Safety Bar Hatfield Squat', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Barbell Heel-Elevated Front Squat', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Anderson Squat (From Pins)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Squat Walkout (Overload)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Split Squat (Deficit 2in)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Deadlift (5s Eccentric)', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Barbell Deadlift (Touch-and-Go)', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Barbell Deadlift (Singles)', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Barbell Hip Thrust (American Style)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Barbell Hip Thrust (Pause + Squeeze)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Dumbbell Hip Thrust (Pulse + Full)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Barbell Romanian DL (Double Pause)', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Advanced' },
  { name: 'Barbell Stiff-Leg DL (Full Stretch)', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Barbell Back Squat + Front Squat Combo', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Clean + Front Squat Combo', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Barbell Snatch + Overhead Squat Combo', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Barbell Jerk + Split Squat Combo', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Barbell Bench (Tempo 4-1-1-1)', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Barbell Bench (1-1/2 Rep Method)', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Barbell Bench (Floor, Wide Grip)', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Barbell Bench (With Slingshot)', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Barbell Bench (Reverse Band)', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Barbell Bench (With Mini Bands)', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Barbell Bench (Heavy + Back Off)', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Barbell Bench (10x10 German Vol.)', category: 'weighted', subCategory: 'Chest', difficulty: 'Advanced' },
  { name: 'Barbell Bench (Max Reps at BW)', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Dumbbell Hex Press (Touching)', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Dumbbell Squeeze Press (Floor)', category: 'weighted', subCategory: 'Inner Chest', difficulty: 'Intermediate' },
  { name: 'Dumbbell Pullover + Press Combo', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Dumbbell Incline Hex Press', category: 'weighted', subCategory: 'Upper Chest', difficulty: 'Intermediate' },
  { name: 'Dumbbell Neutral Incline Press + Fly', category: 'weighted', subCategory: 'Upper Chest', difficulty: 'Intermediate' },
  { name: 'Dumbbell Single-Arm Fly (Flat)', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Dumbbell Alternating Chest Press', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Dumbbell RDL + Bent Row Combo', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Dumbbell RDL + Shrug Combo', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Dumbbell Clean + Press (Single)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Dumbbell Swing (KB Style)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Dumbbell Snatch (From Floor)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Dumbbell Turkish Get-Up (Elbow Only)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Dumbbell Turkish Get-Up (To Press)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Dumbbell Lateral Squat (Cossack)', category: 'weighted', subCategory: 'Inner Thighs', difficulty: 'Intermediate' },
  { name: 'Dumbbell Jump Lunge', category: 'weighted', subCategory: 'Plyometrics', difficulty: 'Advanced' },
  { name: 'Dumbbell Reverse Lunge + Press', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Dumbbell Goblet Squat + Curl', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Dumbbell Goblet Squat + Press', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Dumbbell Hip Thrust + Chest Press', category: 'weighted', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Dumbbell Good Morning + Row', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Dumbbell Farmer Hold (Max Time)', category: 'weighted', subCategory: 'Grip', difficulty: 'Intermediate' },
  { name: 'Kettlebell Simple and Sinister (Swing)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Advanced' },
  { name: 'Kettlebell Simple and Sinister (TGU)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Kettlebell Military Press + Pullup', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Kettlebell Double Press (Heavy)', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Kettlebell Bottoms-Up Press', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Advanced' },
  { name: 'Kettlebell Windmill (Heavy)', category: 'weighted', subCategory: 'Obliques', difficulty: 'Advanced' },
  { name: 'Kettlebell Around the Body (Orbit)', category: 'weighted', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Kettlebell Figure-8 to Hold', category: 'weighted', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Kettlebell Renegade Row (Heavy)', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Kettlebell Squat + Press (Heavy)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Kettlebell Dead Snatch', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Kettlebell Gorilla Row', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Kettlebell Deck Squat', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Sled Push Sprint (Full Load)', category: 'weighted', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Sled Push Walk (Active Recovery)', category: 'weighted', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Trap Bar Deadlift (Jump from Floor)', category: 'weighted', subCategory: 'Plyometrics', difficulty: 'Advanced' },
  { name: 'Trap Bar Farmer Walk (Long)', category: 'weighted', subCategory: 'Grip', difficulty: 'Intermediate' },
  { name: 'Trap Bar Single-Leg DL', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Advanced' },
  { name: 'Barbell Hip Thrust + Abductor Press', category: 'weighted', subCategory: 'Glutes', difficulty: 'Intermediate' },
  { name: 'Barbell DL + Nordic Curl Combo', category: 'weighted', subCategory: 'Back', difficulty: 'Advanced' },
  { name: 'Home Dumbbell PPL Full Workout', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Home Resistance Band Full Workout', category: 'weighted', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Hotel Room Workout (Dumbbell Only)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Travel Workout Kettlebell Only', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Standing Scapular Retraction', category: 'bodyweight', subCategory: 'Upper Back', difficulty: 'Beginner' },
  { name: 'Wall Scapular Push-Up', category: 'bodyweight', subCategory: 'Serratus Anterior', difficulty: 'Beginner' },
  { name: 'Floor Scapular Push-Up (Prone)', category: 'bodyweight', subCategory: 'Serratus Anterior', difficulty: 'Intermediate' },
  { name: 'Scapular Pull-Up (Dead Hang)', category: 'bodyweight', subCategory: 'Lats', difficulty: 'Intermediate' },
  { name: 'Thoracic Cat-Cow (Isolated)', category: 'bodyweight', subCategory: 'Thoracic Spine', difficulty: 'Beginner' },
  { name: 'Thoracic Extension (Door Frame)', category: 'bodyweight', subCategory: 'Thoracic Spine', difficulty: 'Beginner' },
  { name: 'Pec Stretch (Corner Wall)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Beginner' },
  { name: 'Lat Stretch (Half-Kneeling)', category: 'bodyweight', subCategory: 'Lats', difficulty: 'Beginner' },
  { name: 'Lat Stretch (Pull-Up Bar Hang)', category: 'bodyweight', subCategory: 'Lats', difficulty: 'Beginner' },
  { name: 'Overhead Tricep Stretch', category: 'bodyweight', subCategory: 'Triceps', difficulty: 'Beginner' },
  { name: 'Cross-Body Bicep Stretch', category: 'bodyweight', subCategory: 'Biceps', difficulty: 'Beginner' },
  { name: 'Forearm Flexor Stretch (Wrist Back)', category: 'bodyweight', subCategory: 'Forearms', difficulty: 'Beginner' },
  { name: 'Forearm Extensor Stretch (Wrist Fwd)', category: 'bodyweight', subCategory: 'Forearms', difficulty: 'Beginner' },
  { name: 'Hip Flexor Lunge Stretch (Deep)', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Beginner' },
  { name: 'Psoas Stretch (90-90 Elevated)', category: 'bodyweight', subCategory: 'Psoas', difficulty: 'Intermediate' },
  { name: 'Adductor Stretch (Side-Lying)', category: 'bodyweight', subCategory: 'Inner Thighs', difficulty: 'Beginner' },
  { name: 'Hamstring Stretch (Standing Fold)', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Beginner' },
  { name: 'Seated Figure-4 Stretch (Floor)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Spinal Decompression Hang', category: 'bodyweight', subCategory: 'Spine', difficulty: 'Beginner' },
  { name: 'Traction Hang (One-Arm)', category: 'bodyweight', subCategory: 'Spine', difficulty: 'Intermediate' },
  { name: 'Jefferson Curl (BW Only)', category: 'bodyweight', subCategory: 'Lower Back', difficulty: 'Intermediate' },
  { name: 'Reverse Jefferson Curl (BW)', category: 'bodyweight', subCategory: 'Lower Back', difficulty: 'Intermediate' },
  { name: 'Segmental Forward Fold (Slow)', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Beginner' },
  { name: 'Piked Hamstring Stretch (Wall)', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Supine Twist (Both Sides)', category: 'bodyweight', subCategory: 'Obliques', difficulty: 'Beginner' },
  { name: 'Quadruped Opposite Arm-Leg ISO', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Quadruped Rock-Back (Hip Flex)', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Beginner' },
  { name: 'Quadruped Thoracic Rotation', category: 'bodyweight', subCategory: 'Thoracic Spine', difficulty: 'Beginner' },
  { name: 'Supine Knee Hug (Both Knees)', category: 'bodyweight', subCategory: 'Lower Back', difficulty: 'Beginner' },
  { name: 'Child\'s Pose with Side Reach', category: 'bodyweight', subCategory: 'Lats', difficulty: 'Beginner' },
  { name: 'Child\'s Pose with Thoracic Twist', category: 'bodyweight', subCategory: 'Thoracic Spine', difficulty: 'Beginner' },
  { name: 'Puppy Pose (Heart Melting)', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Beginner' },
  { name: 'Sphinx Pose', category: 'bodyweight', subCategory: 'Lower Back', difficulty: 'Beginner' },
  { name: 'Cobra Stretch (Full)', category: 'bodyweight', subCategory: 'Lower Back', difficulty: 'Beginner' },
  { name: 'Low Dragon Pose (Deep Hip)', category: 'bodyweight', subCategory: 'Hip Flexors', difficulty: 'Intermediate' },
  { name: 'Half Splits (Hamstring)', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Full Splits Attempt (Right)', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Advanced' },
  { name: 'Full Splits Attempt (Left)', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Advanced' },
  { name: 'Middle Splits Attempt', category: 'bodyweight', subCategory: 'Inner Thighs', difficulty: 'Advanced' },
  { name: 'Bridge + Shoulder Stretch', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Tiger Stretch (Prone Reach)', category: 'bodyweight', subCategory: 'Lats', difficulty: 'Beginner' },
  { name: 'Prone Y-Reach (Active)', category: 'bodyweight', subCategory: 'Lower Traps', difficulty: 'Beginner' },
  { name: 'Prone T-Reach (Active)', category: 'bodyweight', subCategory: 'Rear Deltoid', difficulty: 'Beginner' },
  { name: 'Prone W-Reach (Active)', category: 'bodyweight', subCategory: 'Rotator Cuff', difficulty: 'Beginner' },
  { name: 'Quadruped Elbow Plank (Alt Leg)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Plank + Opposite Shoulder Tap', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Push-Up Position Hip Circle', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Push-Up Position Toe Tap (Lateral)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Push-Up to Inchworm Combo', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Push-Up to Downward Dog Combo', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Push-Up to Pigeon Pose Combo', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Downward Dog to Upward Dog Flow', category: 'bodyweight', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Sun Salutation A (Full)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Beginner' },
  { name: 'Sun Salutation B (Full)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Standing Flow 1 (Warrior Series)', category: 'bodyweight', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Seated Flow (Hip Openers)', category: 'bodyweight', subCategory: 'Hips', difficulty: 'Intermediate' },
  { name: 'Power Yoga Sequence (20min)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Vinyasa Flow (60 min)', category: 'bodyweight', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Jump Rope Freestyle (90 sec)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Jump Rope Criss-Cross', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Jump Rope Triple Under', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Jump Rope Alternate Foot (Fast)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Jump Rope Interval (10x30s)', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Speed Bag Rhythm Pattern', category: 'bodyweight', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Heavy Bag 3-Min Round', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Intermediate' },
  { name: 'Heavy Bag 5-Round Circuit', category: 'bodyweight', subCategory: 'Cardio', difficulty: 'Advanced' },
  { name: 'Reaction Ball Solo Drill', category: 'bodyweight', subCategory: 'Coordination', difficulty: 'Intermediate' },
  { name: 'Sit-Up (Basic, Arms Crossed)', category: 'bodyweight', subCategory: 'Abs', difficulty: 'Beginner' },
  { name: 'Sit-Up (Hands Behind Head)', category: 'bodyweight', subCategory: 'Abs', difficulty: 'Beginner' },
  { name: 'Sit-Up (V-Ups)', category: 'bodyweight', subCategory: 'Abs', difficulty: 'Intermediate' },
  { name: 'Sit-Up (Tuck Crunch)', category: 'bodyweight', subCategory: 'Abs', difficulty: 'Beginner' },
  { name: 'Sit-Up (Bicycle Crunch, Slow)', category: 'bodyweight', subCategory: 'Obliques', difficulty: 'Intermediate' },
  { name: 'Sit-Up (Jack-Knife)', category: 'bodyweight', subCategory: 'Abs', difficulty: 'Intermediate' },
  { name: 'Leg Raise (Flat Bench)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Flutter Kicks (BW, Prone)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Scissor Kicks (Supine)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Windshield Wipers (Floor)', category: 'bodyweight', subCategory: 'Obliques', difficulty: 'Advanced' },
  { name: 'Windshield Wipers (Hanging)', category: 'bodyweight', subCategory: 'Obliques', difficulty: 'Advanced' },
  { name: 'Toes-to-Bar (Strict)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Toes-to-Bar (Kipping)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Hanging Knee Raise (Slow Eccentric)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Hanging Leg Raise (Tuck to Full)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Stability Ball Crunch', category: 'bodyweight', subCategory: 'Abs', difficulty: 'Beginner' },
  { name: 'Stability Ball Rollout', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Stability Ball Pike', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Stability Ball Stir the Pot', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Stability Ball Hamstring Curl', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Ab Wheel Rollout (Kneeling Full)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Ab Wheel V-Roll (Kneeling)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Ab Wheel Single Arm (Kneeling)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Suspension Core Crunch (TRX)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Suspension Pike (TRX)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Advanced' },
  { name: 'Suspension Oblique Crunch (TRX)', category: 'bodyweight', subCategory: 'Obliques', difficulty: 'Advanced' },
  { name: 'Suspension Mountain Climber (TRX)', category: 'bodyweight', subCategory: 'Core', difficulty: 'Intermediate' },
  { name: 'Suspension Hamstring Curl (TRX)', category: 'bodyweight', subCategory: 'Hamstrings', difficulty: 'Intermediate' },
  { name: 'Suspension Glute Bridge (TRX)', category: 'bodyweight', subCategory: 'Glutes', difficulty: 'Beginner' },
  { name: 'Barbell Romanian DL + Hip Thrust Combo', category: 'weighted', subCategory: 'Hamstrings', difficulty: 'Advanced' },
  { name: 'Barbell Squat + Box Jump Combo', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Advanced' },
  { name: 'Barbell Bench + Dumbbell Fly Combo', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'EZ Bar Curl + Overhead Ext Combo', category: 'weighted', subCategory: 'Arms', difficulty: 'Intermediate' },
  { name: 'Dumbbell Press + Lateral Raise Combo', category: 'weighted', subCategory: 'Shoulders', difficulty: 'Intermediate' },
  { name: 'Kettlebell Clean to Press (Double)', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Kettlebell Front Squat (Double)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Intermediate' },
  { name: 'Cable Fly + Push-Up Superset', category: 'weighted', subCategory: 'Chest', difficulty: 'Intermediate' },
  { name: 'Cable Row + Face Pull Superset', category: 'weighted', subCategory: 'Back', difficulty: 'Intermediate' },
  { name: 'Barbell Complex: DL-HPC-Push Press', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Barbell Complex: Squat-Row-Press', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'KB Complex: Swing-Clean-Press-Squat', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Dumbbell Complex: Curl-Press-Row-Squat', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Band Complex: Pull-Press-Squat-Row', category: 'weighted', subCategory: 'Full Body', difficulty: 'Intermediate' },
  { name: 'Sled Complex: Push-Pull-Sprint', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Medicine Ball Complex: Slam-Throw-Press', category: 'weighted', subCategory: 'Full Body', difficulty: 'Advanced' },
  { name: 'Deload: Squat 50% (High Rep)', category: 'weighted', subCategory: 'Quadriceps', difficulty: 'Beginner' },
  { name: 'Deload: Deadlift 50% (High Rep)', category: 'weighted', subCategory: 'Back', difficulty: 'Beginner' },
  { name: 'Deload: Bench 50% (High Rep)', category: 'weighted', subCategory: 'Chest', difficulty: 'Beginner' },
  { name: 'Deload: Full Body Machine Circuit', category: 'weighted', subCategory: 'Full Body', difficulty: 'Beginner' },
];