// 30 Additional Universal Mental Training Routines (91-120)
export const EXTRA_MENTAL_ROUTINES = [
  {
    title: "Deep Work Session Primer",
    category: "focus",
    duration_seconds: 540,
    description: "Prime your mind for a session of deep, uninterrupted focused work.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close all tabs, silence your phone. Create a physical and mental clear space.", duration_seconds: 40 },
      { instruction: "Write down one clear outcome you intend to achieve this session.", duration_seconds: 40 },
      { instruction: "Take 5 deep breaths. Let each exhale clear mental noise.", duration_seconds: 60 },
      { instruction: "Visualise yourself in deep focus — absorbed, making real progress.", duration_seconds: 90 },
      { instruction: "Say: 'For the next [X] minutes, nothing exists except this one task.'", duration_seconds: 50 },
      { instruction: "Set a timer. Commit fully. No switching. No checking.", duration_seconds: 60 },
      { instruction: "Begin. You are ready. Deep work creates real results.", duration_seconds: 40 },
      { instruction: "The world will wait. Your focus cannot.", duration_seconds: 30 },
      { instruction: "Go.", duration_seconds: 30 },
    ]
  },
  {
    title: "Under the Microscope",
    category: "pressure",
    duration_seconds: 480,
    description: "Train your mind to thrive when all eyes are on you and the stakes are highest.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 80,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Picture yourself in a high-visibility moment — people watching, judging, waiting.", duration_seconds: 60 },
      { instruction: "Notice any shrinking, hesitation, or self-consciousness. Acknowledge it.", duration_seconds: 60 },
      { instruction: "Reframe: 'These eyes are witnesses to my best work. I perform for myself, not them.'", duration_seconds: 70 },
      { instruction: "Breathe deeply. Expand your chest. Take up space.", duration_seconds: 60 },
      { instruction: "See yourself delivering with calm authority despite every eye on you.", duration_seconds: 90 },
      { instruction: "The spotlight is a gift — it means you matter in this moment.", duration_seconds: 60 },
      { instruction: "Say: 'I perform best when it matters most.'", duration_seconds: 50 },
      { instruction: "Open your eyes. Bring the spotlight. You're ready.", duration_seconds: 30 },
    ]
  },
  {
    title: "The Detox Breath",
    category: "recovery",
    duration_seconds: 360,
    description: "Rapidly flush stress chemicals from your body with rhythmic breathing.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 55,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit upright. Place hands on your belly.", duration_seconds: 20 },
      { instruction: "Inhale through the nose for 4 counts — belly rises.", duration_seconds: 40 },
      { instruction: "Hold for 1 count. Feel fullness.", duration_seconds: 20 },
      { instruction: "Exhale completely through the mouth for 6 counts — belly falls.", duration_seconds: 50 },
      { instruction: "Repeat this cycle 10 times. With each exhale, release tension.", duration_seconds: 120 },
      { instruction: "After the 10th breath, sit silently. Notice the calm in your system.", duration_seconds: 60 },
      { instruction: "Your nervous system has reset. You are calmer than 4 minutes ago.", duration_seconds: 30 },
      { instruction: "Carry this rhythm into your next activity.", duration_seconds: 20 },
    ]
  },
  {
    title: "The Process Film",
    category: "visualization",
    duration_seconds: 540,
    description: "Rehearse not just the result but every micro-step of your best performance.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 75,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. You are about to shoot a mental film.", duration_seconds: 30 },
      { instruction: "Begin at the very start — your preparation, your mindset entering.", duration_seconds: 60 },
      { instruction: "Watch each step in real time. Preparation → warm-up → first action.", duration_seconds: 90 },
      { instruction: "Pay attention to how your body feels, what you hear, what you see.", duration_seconds: 90 },
      { instruction: "A challenge arises. You pause, breathe, and execute the right response.", duration_seconds: 90 },
      { instruction: "The film ends with a strong finish and proud completion.", duration_seconds: 60 },
      { instruction: "Process film creates process mastery. Watch it daily.", duration_seconds: 60 },
      { instruction: "Open your eyes. The film is ready. Now make it real.", duration_seconds: 30 },
      { instruction: "Action follows vision. Always.", duration_seconds: 30 },
    ]
  },
  {
    title: "Silent Minute Protocol",
    category: "focus",
    duration_seconds: 420,
    description: "Build elite concentration through 7 escalating minutes of intentional silence.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit still. No movement. Eyes closed or softly focused.", duration_seconds: 30 },
      { instruction: "Minute 1: Observe your breathing only. No other input.", duration_seconds: 60 },
      { instruction: "Minute 2: Notice sounds in your environment without labelling them.", duration_seconds: 60 },
      { instruction: "Minute 3: Focus on the sensation of your breath entering and leaving.", duration_seconds: 60 },
      { instruction: "Minute 4: Expand awareness to your whole body simultaneously.", duration_seconds: 60 },
      { instruction: "Minute 5: Narrow again to a single point — the tip of your nose.", duration_seconds: 60 },
      { instruction: "Minute 6+: Stay here. Completely. No thought is more important than this moment.", duration_seconds: 80 },
      { instruction: "Open your eyes. That was elite concentration training.", duration_seconds: 30 },
    ]
  },
  {
    title: "The Why Engine",
    category: "confidence",
    duration_seconds: 480,
    description: "Reconnect to the deepest reason you do what you do — and let it fuel everything.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Ask yourself: 'Why do I work at this? What is the real reason?'", duration_seconds: 60 },
      { instruction: "Dig one layer deeper: 'But WHY does that matter to me?'", duration_seconds: 60 },
      { instruction: "Dig one more layer: 'And what does THAT mean for my life?'", duration_seconds: 60 },
      { instruction: "You've found your core purpose. Sit with it. Feel its weight.", duration_seconds: 90 },
      { instruction: "Connect every action today to this root purpose.", duration_seconds: 60 },
      { instruction: "When effort feels pointless — return here. To the why.", duration_seconds: 60 },
      { instruction: "Say: 'Everything I do is in service of this purpose. It is worth it.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Your why is your engine. Turn the key.", duration_seconds: 30 },
    ]
  },
  {
    title: "The Champion's Setback",
    category: "recovery",
    duration_seconds: 480,
    description: "Every great champion has a comeback story. Write yours starting today.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Name the setback you're facing right now honestly.", duration_seconds: 50 },
      { instruction: "Recall a champion you admire who faced something worse and kept going.", duration_seconds: 60 },
      { instruction: "What did they do? How did they respond? They didn't quit.", duration_seconds: 60 },
      { instruction: "Understand: setbacks are selection events. Only those who continue become champions.", duration_seconds: 80 },
      { instruction: "Ask: 'What is the next single step forward from where I stand right now?'", duration_seconds: 80 },
      { instruction: "Breathe. Decide. The comeback starts with the next step.", duration_seconds: 60 },
      { instruction: "Say: 'My story is not over. The best chapter is still being written.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Take that step. The comeback starts now.", duration_seconds: 30 },
    ]
  },
  {
    title: "Box Breathing Method",
    category: "match-day-calm",
    duration_seconds: 480,
    description: "The box breathing method for instant calm under extreme pressure.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit upright. Spine straight. Shoulders relaxed.", duration_seconds: 20 },
      { instruction: "Exhale fully to empty your lungs completely.", duration_seconds: 20 },
      { instruction: "Inhale slowly for 4 counts. Fill completely.", duration_seconds: 40 },
      { instruction: "Hold for 4 counts. Stay relaxed.", duration_seconds: 40 },
      { instruction: "Exhale for 4 counts. Empty slowly.", duration_seconds: 40 },
      { instruction: "Hold for 4 counts. Empty lungs.", duration_seconds: 40 },
      { instruction: "Repeat this 4-4-4-4 cycle 8 times. Each cycle deepens the calm.", duration_seconds: 180 },
      { instruction: "Notice: your heart rate has slowed. Your mind is clear.", duration_seconds: 60 },
      { instruction: "Use this technique any time tension spikes.", duration_seconds: 30 },
    ]
  },
  {
    title: "Abundance Mindset Shift",
    category: "confidence",
    duration_seconds: 420,
    description: "Break free from scarcity thinking and step into a mindset of abundance and possibility.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Identify one scarcity thought you've had recently. ('I don't have enough...')", duration_seconds: 60 },
      { instruction: "Challenge it: 'Is this absolutely true? Am I missing things I already have?'", duration_seconds: 60 },
      { instruction: "List 10 things you DO have that are valuable. Take time. Be genuine.", duration_seconds: 120 },
      { instruction: "Shift: 'There is enough. There is more coming. I am enough.'", duration_seconds: 60 },
      { instruction: "Abundance is first a perspective, then a reality.", duration_seconds: 60 },
      { instruction: "Say: 'I operate from abundance. I share freely. I receive openly.'", duration_seconds: 40 },
      { instruction: "Open your eyes. One abundant action today — give something without expectation.", duration_seconds: 30 },
      { instruction: "Abundance begets abundance.", duration_seconds: 20 },
    ]
  },
  {
    title: "The 2-Minute Warrior",
    category: "pressure",
    duration_seconds: 300,
    description: "A rapid-fire mental reset for any high-pressure moment — anywhere, any time.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 50,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "30 seconds: close your eyes, breathe deeply 3 times. Slow down.", duration_seconds: 40 },
      { instruction: "30 seconds: acknowledge the pressure. 'This is real. I can handle this.'", duration_seconds: 40 },
      { instruction: "30 seconds: recall one moment you handled pressure like a warrior.", duration_seconds: 40 },
      { instruction: "30 seconds: set one clear intention for the next 10 minutes.", duration_seconds: 40 },
      { instruction: "30 seconds: breathe out all tension. Roll your shoulders. Stand tall.", duration_seconds: 40 },
      { instruction: "30 seconds: say your word or phrase. Walk forward. Begin.", duration_seconds: 40 },
      { instruction: "2 minutes. You just changed your state completely.", duration_seconds: 30 },
      { instruction: "Warriors reset fast. Now go.", duration_seconds: 30 },
    ]
  },
  {
    title: "The Grief Permission",
    category: "recovery",
    duration_seconds: 540,
    description: "A compassionate session to process loss, disappointment, or deep sadness.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 80,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Find privacy. Give yourself permission to feel whatever is present.", duration_seconds: 30 },
      { instruction: "Name the loss or disappointment fully. Say it to yourself honestly.", duration_seconds: 60 },
      { instruction: "Feel the weight of it. Don't rush to fix it or move on.", duration_seconds: 90 },
      { instruction: "Grief is the price of love and caring. It means something mattered.", duration_seconds: 60 },
      { instruction: "Breathe slowly. Let your body process what your mind is feeling.", duration_seconds: 90 },
      { instruction: "Ask: 'What has this experience taught me about what I value?'", duration_seconds: 90 },
      { instruction: "Say: 'I allow myself to grieve. I also allow myself to heal in time.'", duration_seconds: 60 },
      { instruction: "You don't have to be okay immediately. Healing is not linear.", duration_seconds: 40 },
      { instruction: "Be gentle with yourself today.", duration_seconds: 30 },
    ]
  },
  {
    title: "10 Years Forward",
    category: "visualization",
    duration_seconds: 540,
    description: "Project yourself a decade into the future and design the life you intend to live.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 75,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. Breathe slowly. Let time stretch.", duration_seconds: 40 },
      { instruction: "You are now 10 years in the future. The best realistic version.", duration_seconds: 60 },
      { instruction: "What does your life look like? Work, relationships, health, fulfilment.", duration_seconds: 90 },
      { instruction: "Who are you? What do people say about you? What have you built?", duration_seconds: 90 },
      { instruction: "Feel the pride and satisfaction of that life fully realised.", duration_seconds: 90 },
      { instruction: "Now look back to today. What did you do differently starting here?", duration_seconds: 90 },
      { instruction: "Commit to one change, starting today, that moves toward that life.", duration_seconds: 60 },
      { instruction: "Open your eyes. The gap between now and then is filled with daily choices.", duration_seconds: 30 },
      { instruction: "Today's choices are tomorrow's results.", duration_seconds: 30 },
    ]
  },
  {
    title: "Owning Your Uniqueness",
    category: "confidence",
    duration_seconds: 420,
    description: "Discover and deeply accept what makes you specifically, powerfully different.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Ask: 'What 3 things do I bring that are distinctly, authentically mine?'", duration_seconds: 70 },
      { instruction: "Don't list generic strengths. Find the ones that feel peculiarly, deeply YOU.", duration_seconds: 70 },
      { instruction: "Recognise: the world doesn't need a copy of anyone else. It needs the real you.", duration_seconds: 70 },
      { instruction: "Think of a time someone appreciated exactly that thing about you.", duration_seconds: 70 },
      { instruction: "The things that make you feel 'different' are often your greatest assets.", duration_seconds: 70 },
      { instruction: "Say: 'I am not meant to fit a mold. I am meant to be unmistakably myself.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Live from that place today. Fully. Without apology.", duration_seconds: 30 },
      { instruction: "The world needs the specific version of you that only you can offer.", duration_seconds: 30 },
    ]
  },
  {
    title: "Competition as Fuel",
    category: "pressure",
    duration_seconds: 420,
    description: "Reframe competition as a gift that reveals your potential and raises your game.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Think of someone you compete with or compare yourself to.", duration_seconds: 50 },
      { instruction: "Reframe: they are not your enemy. They are a signal of what is possible.", duration_seconds: 60 },
      { instruction: "Ask: 'What does their excellence teach me about my own potential?'", duration_seconds: 70 },
      { instruction: "Use their performance as a target, not a threat.", duration_seconds: 60 },
      { instruction: "Breathe in the energy of competition. It sharpens you.", duration_seconds: 60 },
      { instruction: "Your best performances likely came when the competition was highest.", duration_seconds: 60 },
      { instruction: "Say: 'I love competition. It reveals a better version of me.'", duration_seconds: 50 },
      { instruction: "Open your eyes. Raise your game because of them.", duration_seconds: 30 },
      { instruction: "Iron sharpens iron. Be grateful for those who push you.", duration_seconds: 30 },
    ]
  },
  {
    title: "Joy Audit",
    category: "recovery",
    duration_seconds: 360,
    description: "Deliberately identify and amplify the sources of genuine joy in your life.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 55,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit quietly. Ask: 'When was the last time I felt genuinely, fully joyful?'", duration_seconds: 60 },
      { instruction: "Recall that moment. Where were you? Who was there? What made it so?", duration_seconds: 70 },
      { instruction: "List 3 activities or people that reliably bring you joy.", duration_seconds: 60 },
      { instruction: "Ask: 'How much space do I give these things in my week?'", duration_seconds: 60 },
      { instruction: "Make one commitment: give one of these more space this week.", duration_seconds: 60 },
      { instruction: "Joy is not a reward for hard work. It is the fuel for it.", duration_seconds: 30 },
      { instruction: "Say: 'I prioritise joy because it makes everything else possible.'", duration_seconds: 30 },
      { instruction: "Schedule the joy. Put it in your calendar.", duration_seconds: 30 },
    ]
  },
  {
    title: "Sensory Performance Blueprint",
    category: "visualization",
    duration_seconds: 600,
    description: "Build a hyper-detailed multi-sensory performance rehearsal for peak readiness.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 85,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. Build your performance environment in total detail.", duration_seconds: 60 },
      { instruction: "What do you SEE? Every colour, shape, distance, light.", duration_seconds: 80 },
      { instruction: "What do you HEAR? Crowd, wind, your own breathing, sounds of the game.", duration_seconds: 80 },
      { instruction: "What do you FEEL? Ground beneath you, equipment in hand, temperature.", duration_seconds: 80 },
      { instruction: "What do you SMELL? Cut grass, sweat, the air. Make it utterly real.", duration_seconds: 60 },
      { instruction: "Now perform. Fully immersed. Every sense active.", duration_seconds: 120 },
      { instruction: "When complete, feel the pride and certainty. Your brain has been there.", duration_seconds: 60 },
      { instruction: "Open your eyes. The blueprint is laid. Execute the build.", duration_seconds: 30 },
      { instruction: "Your body doesn't know the difference. It just prepares.", duration_seconds: 30 },
    ]
  },
  {
    title: "The Imposter Dissolve",
    category: "confidence",
    duration_seconds: 480,
    description: "Dismantle imposter syndrome and claim your place with full authority.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Acknowledge: 'I sometimes feel like I don't deserve to be here.'", duration_seconds: 50 },
      { instruction: "Understand: imposter syndrome is most common among high performers. It's self-awareness, not incompetence.", duration_seconds: 70 },
      { instruction: "List the real, earned reasons you have a place at this table.", duration_seconds: 80 },
      { instruction: "Ask: 'Would someone who truly didn't belong have made it this far?'", duration_seconds: 60 },
      { instruction: "Recognise: you are not faking it. You are growing into it. That's called learning.", duration_seconds: 70 },
      { instruction: "Say: 'I belong here. Not because I'm perfect, but because I've earned this moment.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Act from belonging. Not from fear.", duration_seconds: 40 },
      { instruction: "Imposter syndrome fades with each time you show up anyway.", duration_seconds: 30 },
      { instruction: "Show up. Again. And again.", duration_seconds: 30 },
    ]
  },
  {
    title: "Releasing Expectations",
    category: "pressure",
    duration_seconds: 480,
    description: "Free yourself from the weight of others' expectations and perform for yourself.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Name whose expectations you carry most heavily.", duration_seconds: 50 },
      { instruction: "Ask: are these expectations actually theirs, or ones I've assumed they have?", duration_seconds: 60 },
      { instruction: "Understand: you can only control your effort and intention. Not how it lands.", duration_seconds: 70 },
      { instruction: "Breathe out the weight of trying to meet expectations that aren't yours to carry.", duration_seconds: 80 },
      { instruction: "Define your own standard. Based on your values. Your growth. Your journey.", duration_seconds: 80 },
      { instruction: "When you perform for approval, you lose. When you perform from purpose, you win.", duration_seconds: 80 },
      { instruction: "Say: 'I perform for me. That is the only standard that endures.'", duration_seconds: 50 },
      { instruction: "Open your eyes. Put down the expectations. Pick up your purpose.", duration_seconds: 30 },
    ]
  },
  {
    title: "Pre-Sleep Mental Shutdown",
    category: "recovery",
    duration_seconds: 540,
    description: "Systematically close the mental tabs so your body can enter deep sleep.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Lie down. Phone away. Darkness and quiet if possible.", duration_seconds: 20 },
      { instruction: "Mentally list every 'open tab' — unresolved thoughts, worries, tomorrow's tasks.", duration_seconds: 90 },
      { instruction: "For each one, say: 'That is noted. I'll address it tomorrow. Closing it now.'", duration_seconds: 90 },
      { instruction: "Take 5 slow breaths. Each exhale closes another tab.", duration_seconds: 80 },
      { instruction: "Your to-do list is on pause. The world is okay without you for 8 hours.", duration_seconds: 60 },
      { instruction: "Imagine a slow sunset in your mind — beautiful, gradual, peaceful.", duration_seconds: 90 },
      { instruction: "Feel your body getting heavier with every breath.", duration_seconds: 60 },
      { instruction: "Sleep is the best recovery tool available. Use it fully.", duration_seconds: 30 },
      { instruction: "Let go. Drift. Rest deeply.", duration_seconds: 30 },
    ]
  },
  {
    title: "Breaking the Mental Block",
    category: "visualization",
    duration_seconds: 480,
    description: "Identify and dissolve the mental blocks that stop you from performing at your best.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 80,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Name one thing you consistently struggle to do despite having the skill.", duration_seconds: 60 },
      { instruction: "What is the thought that precedes the block? Find it exactly.", duration_seconds: 70 },
      { instruction: "Visualise the block as a physical object. What shape is it? What colour?", duration_seconds: 60 },
      { instruction: "Now in your mind, begin dismantling it. Slowly. Piece by piece.", duration_seconds: 90 },
      { instruction: "In the space where it was — see yourself executing freely. Cleanly. Naturally.", duration_seconds: 90 },
      { instruction: "Replay this 3 times: block gone, execution perfect, feeling free.", duration_seconds: 90 },
      { instruction: "Say: 'The block is a pattern I created. I can create a new one.'", duration_seconds: 50 },
      { instruction: "Open your eyes. The pattern starts shifting with this session.", duration_seconds: 30 },
      { instruction: "Repetition builds the new neural pathway. Return here daily.", duration_seconds: 30 },
    ]
  },
  {
    title: "Freedom from Judgment",
    category: "confidence",
    duration_seconds: 480,
    description: "Dissolve fear of what others think and step into authentic, fearless action.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Identify a situation where you held back because of fear of being judged.", duration_seconds: 60 },
      { instruction: "Ask: 'What is the worst realistic judgment someone could make of me here?'", duration_seconds: 60 },
      { instruction: "Ask: 'Could I survive that judgment? Could I still grow from it?'", duration_seconds: 60 },
      { instruction: "Realise: most people are too focused on themselves to truly notice or remember.", duration_seconds: 70 },
      { instruction: "The cost of not acting is almost always higher than the cost of judgment.", duration_seconds: 80 },
      { instruction: "Take one bold, authentic action this week you've been avoiding out of judgment-fear.", duration_seconds: 70 },
      { instruction: "Say: 'I will not let imagined judgment imprison my real potential.'", duration_seconds: 50 },
      { instruction: "Open your eyes. Act. Judge later — if at all.", duration_seconds: 30 },
    ]
  },
  {
    title: "Choke-Proof Preparation",
    category: "pressure",
    duration_seconds: 540,
    description: "Train your mind to prevent choking by over-learning automation under pressure.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 80,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Understand: choking happens when conscious attention hijacks automatic processes.", duration_seconds: 60 },
      { instruction: "The solution is to practice so deeply that skill becomes automatic and bulletproof.", duration_seconds: 70 },
      { instruction: "Visualise performing your skill while deliberately thinking about something else.", duration_seconds: 90 },
      { instruction: "See your body executing perfectly while your mind is calm and uninvolved.", duration_seconds: 90 },
      { instruction: "Practise trusting your training rather than controlling execution in real time.", duration_seconds: 90 },
      { instruction: "Use a mantra during performance to occupy the conscious mind and let the body work.", duration_seconds: 90 },
      { instruction: "Say: 'My body knows. I trust the training. I get out of my own way.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Trust is the antidote to choking. Build it daily.", duration_seconds: 30 },
      { instruction: "The training is the protection. Trust it.", duration_seconds: 30 },
    ]
  },
  {
    title: "Life Balance Audit",
    category: "recovery",
    duration_seconds: 540,
    description: "Honestly review the key areas of your life and take action toward genuine balance.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 75,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Rate these areas of your life 1-10: health, relationships, purpose, finances, growth, joy.", duration_seconds: 90 },
      { instruction: "Which area scored lowest? That is where life is sending you a message.", duration_seconds: 60 },
      { instruction: "Ask: What one action this week would move that score from X to X+1?", duration_seconds: 80 },
      { instruction: "Lasting performance requires balance over time. Not just sprints in one lane.", duration_seconds: 80 },
      { instruction: "Commit to one specific action for your lowest area this week.", duration_seconds: 60 },
      { instruction: "Say: 'I am not just a performer. I am a whole person. I invest in all of me.'", duration_seconds: 60 },
      { instruction: "Open your eyes. One action. One area. This week.", duration_seconds: 30 },
      { instruction: "Balance is intentional investment, not perfection.", duration_seconds: 30 },
      { instruction: "Begin.", duration_seconds: 30 },
    ]
  },
  {
    title: "The Vivid Goal Map",
    category: "visualization",
    duration_seconds: 600,
    description: "Transform vague goals into a vivid, emotionally-charged mental map you can act on daily.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 80,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Choose your most important current goal. Make it specific and measurable.", duration_seconds: 60 },
      { instruction: "Close your eyes. See yourself having achieved it fully. What does it look like?", duration_seconds: 90 },
      { instruction: "What do you feel? Pride, relief, joy, freedom? Stay in that feeling.", duration_seconds: 90 },
      { instruction: "Now trace backward: what was the last step before achieving it?", duration_seconds: 70 },
      { instruction: "And the step before that? Build the path backward to today.", duration_seconds: 90 },
      { instruction: "You now have a map from today to the goal. Each step is real and doable.", duration_seconds: 70 },
      { instruction: "Return to the feeling of achieving it. Anchor that emotion.", duration_seconds: 60 },
      { instruction: "Say: 'I know where I'm going. I know the next step. I begin.'", duration_seconds: 50 },
      { instruction: "Open your eyes. What is the very next step? Do it today.", duration_seconds: 30 },
      { instruction: "The map is in you now. Trust it.", duration_seconds: 30 },
    ]
  },
  {
    title: "Morning Clarity Protocol",
    category: "focus",
    duration_seconds: 420,
    description: "Start every day with complete mental clarity on your priorities and inner state.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Before checking anything, sit quietly for 2 minutes. Just exist.", duration_seconds: 60 },
      { instruction: "Ask: 'What is the single most important thing I need to do today?'", duration_seconds: 60 },
      { instruction: "Ask: 'How do I want to show up today? What kind of person will I be?'", duration_seconds: 60 },
      { instruction: "Set a 3-word intention for the day: e.g. calm, focused, generous.", duration_seconds: 50 },
      { instruction: "Take 5 deep, slow breaths. Each one sets the tone for the day.", duration_seconds: 70 },
      { instruction: "Say: 'Today I begin with clarity, not chaos. I lead my day.'", duration_seconds: 50 },
      { instruction: "Open your eyes. Do the important thing first. Before anything else.", duration_seconds: 40 },
      { instruction: "The morning sets the tone for everything that follows. Own it.", duration_seconds: 30 },
    ]
  },
  {
    title: "Vocal and Physical Presence",
    category: "confidence",
    duration_seconds: 360,
    description: "Train your voice, posture and presence so that you command respect before you speak.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Stand up. Take up full space. Feet wide. Back straight. Chin level.", duration_seconds: 40 },
      { instruction: "Take 5 deep, slow breaths into your chest and belly.", duration_seconds: 60 },
      { instruction: "Speak your name out loud, slowly, with full conviction. Own it.", duration_seconds: 30 },
      { instruction: "Speak one sentence about your goal with full voice, full volume, full confidence.", duration_seconds: 40 },
      { instruction: "Notice how your body feels when you inhabit it fully. This is available always.", duration_seconds: 60 },
      { instruction: "Presence is not loud. It is grounded, unhurried, unconditional.", duration_seconds: 60 },
      { instruction: "Say: 'I take up the space I deserve. Fully. Without apology.'", duration_seconds: 40 },
      { instruction: "Walk confidently into your next interaction. Presence first.", duration_seconds: 30 },
    ]
  },
  {
    title: "Embrace the Discomfort",
    category: "pressure",
    duration_seconds: 420,
    description: "Learn to sit with discomfort instead of escaping it — and find growth on the other side.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Identify a discomfort you've been avoiding. Physical, emotional, or situational.", duration_seconds: 50 },
      { instruction: "Deliberately sit with the discomfort now. Don't escape it. Just breathe into it.", duration_seconds: 70 },
      { instruction: "Notice: discomfort rarely kills. It is survivable. You are surviving it right now.", duration_seconds: 70 },
      { instruction: "Ask: 'What becomes available to me on the other side of this discomfort?'", duration_seconds: 70 },
      { instruction: "Every great outcome lives beyond a discomfort you had to endure.", duration_seconds: 70 },
      { instruction: "Say: 'I lean into discomfort. It is the gateway to my growth.'", duration_seconds: 50 },
      { instruction: "Breathe deeply. Stay present. The discomfort will pass. Your strength will remain.", duration_seconds: 70 },
      { instruction: "Open your eyes. Face one uncomfortable thing today. On purpose.", duration_seconds: 30 },
      { instruction: "Growth lives outside comfort. Choose growth.", duration_seconds: 30 },
    ]
  },
  {
    title: "Closing the Loop",
    category: "recovery",
    duration_seconds: 420,
    description: "Find mental closure on unfinished emotional business so it stops draining your energy.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Name one thing from the past that still lives rent-free in your mind.", duration_seconds: 50 },
      { instruction: "Write it out mentally: what happened, what you feel, what you wish had been different.", duration_seconds: 80 },
      { instruction: "Acknowledge what was in your control, and what wasn't. Be honest.", duration_seconds: 70 },
      { instruction: "If action is still possible — plan it. If not — consciously choose to release it.", duration_seconds: 80 },
      { instruction: "Say: 'This chapter is complete. I learned from it. I'm releasing it.'", duration_seconds: 60 },
      { instruction: "Breathe. Feel the space that opens when you let something go.", duration_seconds: 60 },
      { instruction: "Open loops consume your mental RAM. Close them deliberately.", duration_seconds: 40 },
      { instruction: "Open your eyes. A loop is closed. Energy is freed.", duration_seconds: 30 },
    ]
  },
  // ---- 20 NEW ROUTINES ----
  {
    title: "Anchoring Your Peak State",
    category: "confidence",
    duration_seconds: 360,
    description: "Create a powerful internal anchor to instantly access your peak performance state.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Recall the single best moment you have ever felt in your sport or life. Live it fully.", duration_seconds: 70 },
      { instruction: "Turn up the brightness, sounds, and feelings of that memory. Make it vivid.", duration_seconds: 60 },
      { instruction: "When the feeling peaks — press two fingers together and hold. This is your anchor.", duration_seconds: 60 },
      { instruction: "Release. Breathe normally. Clear the state.", duration_seconds: 40 },
      { instruction: "Press the anchor again. Notice the feeling returns. This is a real neurological tool.", duration_seconds: 60 },
      { instruction: "Say: 'My best state is available to me at any time. I choose it now.'", duration_seconds: 50 },
      { instruction: "Open your eyes. Use this anchor before any high-stakes moment.", duration_seconds: 30 },
    ]
  },
  {
    title: "Noise Cancellation Focus",
    category: "focus",
    duration_seconds: 420,
    description: "Train your mind to filter out external distractions and maintain laser-like focus.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit in a place with ambient noise. Do not try to block it.", duration_seconds: 30 },
      { instruction: "Choose one point of focus — a breath, a word, an object.", duration_seconds: 40 },
      { instruction: "Every time a sound pulls your attention, notice it, label it 'sound', and return.", duration_seconds: 80 },
      { instruction: "Notice how quickly you can redirect. This speed is your focus muscle.", duration_seconds: 60 },
      { instruction: "Repeat: every distraction is a rep. 10 returns = 10 reps of focus strength.", duration_seconds: 70 },
      { instruction: "Say: 'Distractions make me stronger. I choose where my attention goes.'", duration_seconds: 60 },
      { instruction: "Open your eyes. External noise no longer owns your mind.", duration_seconds: 40 },
      { instruction: "Elite focus is trained here — in the noise, not from it.", duration_seconds: 40 },
    ]
  },
  {
    title: "Releasing Outcome Attachment",
    category: "pressure",
    duration_seconds: 480,
    description: "Reduce performance anxiety by focusing fully on process rather than uncontrollable outcomes.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 75,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Name the outcome you are most attached to right now. Say it clearly.", duration_seconds: 50 },
      { instruction: "Ask: 'Which parts of this outcome are truly in my control?'", duration_seconds: 70 },
      { instruction: "Write mentally: effort yes. Execution yes. Result? Partly. Judges? No.", duration_seconds: 70 },
      { instruction: "Breathe into the parts you cannot control. Release them consciously.", duration_seconds: 70 },
      { instruction: "Redirect: 'What is the one process behavior I can commit to fully right now?'", duration_seconds: 80 },
      { instruction: "When you focus on process, outcomes tend to take care of themselves.", duration_seconds: 70 },
      { instruction: "Say: 'I release what I cannot control. I fully own what I can.'", duration_seconds: 50 },
      { instruction: "Open your eyes. Do the process. Let the outcome follow.", duration_seconds: 30 },
    ]
  },
  {
    title: "The Micro-Win Review",
    category: "recovery",
    duration_seconds: 300,
    description: "Shift from dwelling on mistakes to celebrating the small, real wins of your day.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 50,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Forget the big picture for 5 minutes. Ask: what went right today, no matter how small?", duration_seconds: 60 },
      { instruction: "List at least 5 micro-wins. They can be tiny: woke up on time, showed up, tried.", duration_seconds: 80 },
      { instruction: "Acknowledge each one. Small wins compound. They are not nothing.", duration_seconds: 60 },
      { instruction: "Feel genuine pride for each win. Pride fuels momentum.", duration_seconds: 50 },
      { instruction: "Say: 'I am making progress. Every day I move forward, even if just a little.'", duration_seconds: 50 },
    ]
  },
  {
    title: "Grounding for Instant Presence",
    category: "match-day-calm",
    duration_seconds: 360,
    description: "A powerful technique to bring yourself fully into the present moment and calm anxiety instantly.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 55,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Stop. Place both feet flat on the ground. Feel the contact.", duration_seconds: 30 },
      { instruction: "Name 5 things you can SEE right now. Say each one silently.", duration_seconds: 50 },
      { instruction: "Name 4 things you can FEEL right now. Temperature, texture, weight.", duration_seconds: 50 },
      { instruction: "Name 3 things you can HEAR. Don't label them good or bad. Just notice.", duration_seconds: 50 },
      { instruction: "Name 2 things you can SMELL or TASTE. Even subtle.", duration_seconds: 40 },
      { instruction: "Name 1 thing you are grateful for in this exact moment.", duration_seconds: 40 },
      { instruction: "You are now 100% here. Anxiety lives in the future. You are in the present.", duration_seconds: 50 },
      { instruction: "Say: 'I am here. Now. This is enough.'", duration_seconds: 30 },
    ]
  },
  {
    title: "Embrace the Arena",
    category: "visualization",
    duration_seconds: 420,
    description: "Visualize and mentally own the entire playing environment so you feel at home anywhere.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. Picture the venue where you will perform. Walk in.", duration_seconds: 60 },
      { instruction: "Look around slowly. The field, the crowd, the sky, the light. Take it all in.", duration_seconds: 70 },
      { instruction: "Instead of feeling small — expand. This arena belongs to you as much as anyone.", duration_seconds: 70 },
      { instruction: "Walk to your position. Plant your feet. Claim your space.", duration_seconds: 60 },
      { instruction: "See yourself completely at ease. Calm. Focused. Dominant.", duration_seconds: 80 },
      { instruction: "Say: 'I own this space. I belong here. This is my arena.'", duration_seconds: 50 },
      { instruction: "Open your eyes. You've already been there. Now go make it real.", duration_seconds: 30 },
    ]
  },
  {
    title: "Inner Critic Translator",
    category: "confidence",
    duration_seconds: 480,
    description: "Transform harsh self-talk into useful feedback and compassionate self-coaching.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Write down the harshest thing your inner critic says about you.", duration_seconds: 60 },
      { instruction: "Ask: would I say this exact thing to a teammate or close friend? No. Why not?", duration_seconds: 70 },
      { instruction: "The critic is trying to protect you — but its delivery is destructive.", duration_seconds: 60 },
      { instruction: "Translate it: 'You're terrible' → 'I want to improve at this specific thing.'", duration_seconds: 80 },
      { instruction: "Rephrase 3 more critical thoughts into growth-focused coaching statements.", duration_seconds: 90 },
      { instruction: "Say: 'My inner voice now coaches me. It is honest, kind, and actionable.'", duration_seconds: 60 },
      { instruction: "The goal is not silence — it's translation. Use the critic. Don't fight it.", duration_seconds: 30 },
      { instruction: "Open your eyes. You are now your own best coach.", duration_seconds: 30 },
    ]
  },
  {
    title: "Post-Performance Debrief",
    category: "recovery",
    duration_seconds: 540,
    description: "A structured mental debrief to extract lessons and find emotional closure from any performance.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Find quiet. You've just performed. Whatever happened, this is now the debrief.", duration_seconds: 30 },
      { instruction: "What went well? Identify at least 3 specific positives, no matter the result.", duration_seconds: 90 },
      { instruction: "What would you do differently? Not criticism — honest, specific improvement notes.", duration_seconds: 90 },
      { instruction: "What is the single most important thing to practise before next time?", duration_seconds: 80 },
      { instruction: "Close the performance mentally: 'That session is complete. I learned from it.'", duration_seconds: 80 },
      { instruction: "Say: 'I review, extract, and move forward. I don't carry it. I use it.'", duration_seconds: 60 },
      { instruction: "Breathe. The debrief is done. Step into recovery now.", duration_seconds: 30 },
      { instruction: "Champions review their performances. Now you do too.", duration_seconds: 30 },
    ]
  },
  {
    title: "Strategic Pause Activation",
    category: "pressure",
    duration_seconds: 360,
    description: "Learn to intentionally pause in high-stakes moments to instantly regain composure and clarity.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "When pressure spikes — PAUSE. Don't react. Create one second of space.", duration_seconds: 40 },
      { instruction: "Take one slow breath in for 4 counts. Hold for 2.", duration_seconds: 50 },
      { instruction: "Exhale slowly for 6. Feel your nervous system slow.", duration_seconds: 50 },
      { instruction: "Ask: 'What is the single most important thing I can do in the next 10 seconds?'", duration_seconds: 70 },
      { instruction: "That question replaces panic with intention.", duration_seconds: 50 },
      { instruction: "Act from intention, not from fear.", duration_seconds: 40 },
      { instruction: "Say: 'The pause is my power. It gives me choice.'", duration_seconds: 40 },
      { instruction: "Practise this pause daily so it becomes automatic under pressure.", duration_seconds: 30 },
    ]
  },
  {
    title: "Energy Source Identification",
    category: "focus",
    duration_seconds: 420,
    description: "Identify and consciously connect with your personal sources of deep positive energy.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Ask: when do I feel most alive, energized, and fully myself?", duration_seconds: 70 },
      { instruction: "Identify 3 specific activities or situations that consistently replenish you.", duration_seconds: 70 },
      { instruction: "Now identify 3 things that consistently drain your energy.", duration_seconds: 60 },
      { instruction: "Notice: are you currently getting enough of your energy sources?", duration_seconds: 70 },
      { instruction: "Make one commitment to increase energy sources this week.", duration_seconds: 60 },
      { instruction: "Energy is not random. It is a result of how you spend your time.", duration_seconds: 50 },
      { instruction: "Say: 'I protect my energy. I invest it intentionally.'", duration_seconds: 40 },
    ]
  },
  {
    title: "Growth Mindset Fuel",
    category: "pro-mental",
    duration_seconds: 480,
    description: "Strengthen your belief that abilities are developed through effort, strategy, and dedication.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Name one skill you currently have that you once did not. You grew that.", duration_seconds: 70 },
      { instruction: "Understand: talent is a starting point. Skill is built through deliberate work.", duration_seconds: 70 },
      { instruction: "Identify one area you currently label as a fixed weakness. Now challenge that.", duration_seconds: 80 },
      { instruction: "Ask: 'If I worked specifically on this for 90 days, how different might it be?'", duration_seconds: 80 },
      { instruction: "Replace 'I can't do this' with 'I can't do this YET.'", duration_seconds: 60 },
      { instruction: "Say: 'I am not the finished product. I am always becoming better.'", duration_seconds: 60 },
      { instruction: "Open your eyes. The belief in growth is itself the engine of growth.", duration_seconds: 30 },
      { instruction: "Begin the work. The mindset only matters if it leads to action.", duration_seconds: 30 },
    ]
  },
  {
    title: "The 'What If' Neutralizer",
    category: "pro-mental",
    duration_seconds: 420,
    description: "Address and dissolve paralyzing 'what if' thoughts before they spiral into anxiety.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Name your top 'what if' fear right now. Say it fully without editing.", duration_seconds: 60 },
      { instruction: "Ask: 'How likely is this, really? 1 in 10? 1 in 100?'", duration_seconds: 60 },
      { instruction: "Ask: 'If it did happen, could I survive it? Have I survived hard things before?'", duration_seconds: 70 },
      { instruction: "Replace each 'what if it goes wrong' with 'what if it goes RIGHT?'", duration_seconds: 70 },
      { instruction: "Notice: both are equally possible. You choose which to rehearse.", duration_seconds: 70 },
      { instruction: "Say: 'I prepare for the best. I can handle the worst. I fear neither.'", duration_seconds: 60 },
      { instruction: "Open your eyes. You just defused a fear spiral. Do this whenever it starts.", duration_seconds: 30 },
    ]
  },
  {
    title: "Patience Cultivation",
    category: "focus",
    duration_seconds: 540,
    description: "Develop genuine patience and trust in the process, especially when results are delayed.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 80,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit with the discomfort of wanting results NOW. Don't rush it. Just sit.", duration_seconds: 60 },
      { instruction: "Recall a time you wanted something immediately but had to wait — and then got it.", duration_seconds: 80 },
      { instruction: "Growth follows the law of the harvest: you plant, tend, and wait. The season determines timing.", duration_seconds: 90 },
      { instruction: "Ask: 'Am I doing the daily work required? If yes — then patience is the only missing piece.'", duration_seconds: 90 },
      { instruction: "Trust is not passive. It is active faith based on evidence of your own effort.", duration_seconds: 80 },
      { instruction: "Say: 'I am planting every day. The harvest is coming. I trust the process.'", duration_seconds: 60 },
      { instruction: "Breathe slowly. Let patience become a strength, not just a virtue.", duration_seconds: 50 },
      { instruction: "Open your eyes. Show up again today. The timing is working.", duration_seconds: 30 },
    ]
  },
  {
    title: "Learning from Opponents",
    category: "pro-mental",
    duration_seconds: 360,
    description: "Shift perspective to see opponents as teachers who reveal your next level of capability.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Think of the opponent or rival who challenges you most.", duration_seconds: 50 },
      { instruction: "Instead of viewing them as a threat, ask: what specific quality do they have that I respect?", duration_seconds: 70 },
      { instruction: "That quality exists in you too — it just hasn't been fully developed yet.", duration_seconds: 70 },
      { instruction: "Ask: what would I need to do to develop that quality over the next 60 days?", duration_seconds: 80 },
      { instruction: "Thank your opponent mentally. They are your free coach.", duration_seconds: 50 },
      { instruction: "Say: 'My greatest rivals teach me what my next level looks like.'", duration_seconds: 50 },
      { instruction: "Open your eyes. Use the competition as a mirror, not a wall.", duration_seconds: 30 },
    ]
  },
  {
    title: "Self-Compassion Break",
    category: "recovery",
    duration_seconds: 300,
    description: "Offer yourself the same kindness and understanding you would give to a good friend in pain.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 50,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Acknowledge: this is a moment of struggle. It is real and it is okay.", duration_seconds: 50 },
      { instruction: "Remember: struggle is part of being human. You are not alone in this.", duration_seconds: 50 },
      { instruction: "Place one hand on your heart. Feel its warmth. You are alive, and that matters.", duration_seconds: 60 },
      { instruction: "Say the words you would say to your best friend right now. Say them to yourself.", duration_seconds: 70 },
      { instruction: "Say: 'I am worthy of my own kindness. I am on my side.'", duration_seconds: 70 },
    ]
  },
  {
    title: "Decision-Making Clarity",
    category: "focus",
    duration_seconds: 480,
    description: "A mental process to approach decisions with calm logic, clear values, and quiet intuition.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Name the decision you face. State it simply and clearly in one sentence.", duration_seconds: 50 },
      { instruction: "List the options. Not all solutions, just the realistic 2 or 3 that actually matter.", duration_seconds: 80 },
      { instruction: "For each option, ask: 'Does this align with my values and long-term goals?'", duration_seconds: 80 },
      { instruction: "Check your gut: which option do you keep returning to instinctively?", duration_seconds: 70 },
      { instruction: "Ask: 'Which choice will I respect myself for making in 5 years?'", duration_seconds: 80 },
      { instruction: "Make the decision. Commit fully to it. Doubt after deciding is optional — choose not to.", duration_seconds: 70 },
      { instruction: "Say: 'I make clear decisions from clear values. I commit and move forward.'", duration_seconds: 50 },
    ]
  },
  {
    title: "Detaching from Perfectionism",
    category: "pressure",
    duration_seconds: 540,
    description: "Release the burden of perfectionism and embrace the productive power of 'good enough to grow'.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 80,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Name one area where perfectionism is holding you back from starting or finishing.", duration_seconds: 70 },
      { instruction: "Ask: 'Is perfect even achievable here? Or is it an ever-moving goalpost?'", duration_seconds: 70 },
      { instruction: "Understand: perfectionism protects the ego by never risking real judgment.", duration_seconds: 80 },
      { instruction: "Reframe: 'Done and imperfect is infinitely more valuable than perfect and never attempted.'", duration_seconds: 80 },
      { instruction: "Set a standard of excellence — high, but achievable. That is the new target.", duration_seconds: 90 },
      { instruction: "Say: 'I pursue excellence, not perfection. Excellence is achievable. Perfection is a trap.'", duration_seconds: 80 },
      { instruction: "Open your eyes. Start. Iterate. Improve. Ship. That is the real standard.", duration_seconds: 40 },
      { instruction: "Progress is perfect. Perfection is not progress.", duration_seconds: 30 },
    ]
  },
  {
    title: "Embracing Change",
    category: "pro-mental",
    duration_seconds: 300,
    description: "Build mental flexibility to adapt gracefully and powerfully to unexpected change.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 50,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Name a change you are currently resisting, even slightly.", duration_seconds: 60 },
      { instruction: "Ask: 'What specifically am I afraid of losing in this change?'", duration_seconds: 60 },
      { instruction: "Ask: 'What might I gain that I haven't considered yet?'", duration_seconds: 60 },
      { instruction: "Understand: resistance to change costs energy. Acceptance frees it.", duration_seconds: 60 },
      { instruction: "Say: 'Change is not happening TO me. It is happening FOR me, or through me. I adapt.'", duration_seconds: 60 },
    ]
  },
  {
    title: "Future-Pacing Success",
    category: "visualization",
    duration_seconds: 420,
    description: "Project yourself vividly into a future where you have achieved your most important goal.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. Set a specific date 6 months from now.", duration_seconds: 40 },
      { instruction: "You have achieved your most important goal. Step fully into that moment.", duration_seconds: 70 },
      { instruction: "What does it look like? Who is around you? What are people saying?", duration_seconds: 80 },
      { instruction: "What does it FEEL like? Let the emotion be real and vivid.", duration_seconds: 80 },
      { instruction: "Look back from that moment — what were the 3 key decisions that got you here?", duration_seconds: 90 },
      { instruction: "Bring that feeling back to the present. This is your direction.", duration_seconds: 60 },
      { instruction: "Say: 'I have already seen where I am going. Now I just have to get there.'", duration_seconds: 30 },
    ]
  },
  {
    title: "Active Listening for Insight",
    category: "focus",
    duration_seconds: 480,
    description: "Develop deep listening skills to gain real insights from feedback, coaches, and conversations.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Most people listen to reply. Elite performers listen to understand. Which are you?", duration_seconds: 60 },
      { instruction: "In your next conversation or feedback session, commit to 100% presence.", duration_seconds: 70 },
      { instruction: "Notice when your mind starts composing a response mid-sentence. That is the habit to break.", duration_seconds: 80 },
      { instruction: "Practice today: imagine you will be tested on what the other person said. Listen that carefully.", duration_seconds: 90 },
      { instruction: "Ask one genuine follow-up question before you respond. Just one. Always.", duration_seconds: 80 },
      { instruction: "The insights that change your game often come from listening you weren't doing.", duration_seconds: 60 },
      { instruction: "Say: 'I listen with full presence. I hear what is actually being said.'", duration_seconds: 40 },
    ]
  },
  // ---- 10 MORE ROUTINES ----
  {
    title: "Pre-Game Activation",
    category: "match-day-calm",
    duration_seconds: 300,
    description: "A quick routine to energize your mind and body just before a match or performance.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 50,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Take 3 fast, sharp breaths. Exhale forcefully. Wake your whole system up.", duration_seconds: 30 },
      { instruction: "Shake out your hands, arms, and shoulders. Release every last bit of tension.", duration_seconds: 20 },
      { instruction: "Say your name and role out loud: 'I am here. I am ready. I am focused.'", duration_seconds: 30 },
      { instruction: "Recall your most powerful performance moment. Feel that energy now in your body.", duration_seconds: 60 },
      { instruction: "Set your one clear intention for this performance. One word. Say it out loud.", duration_seconds: 40 },
      { instruction: "Take one deep breath. Hold for 3 counts. Release fully. You are activated.", duration_seconds: 30 },
      { instruction: "Everything you need, you already have. Go.", duration_seconds: 30 },
      { instruction: "Begin now.", duration_seconds: 20 },
    ]
  },
  {
    title: "The Reset Button",
    category: "recovery",
    duration_seconds: 240,
    description: "A rapid mental reset technique to instantly clear mistakes and refocus for the next action.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 45,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "The last moment is over. Completely done. You cannot change it. Accept this.", duration_seconds: 40 },
      { instruction: "Take one slow, deep breath in. Hold for 2 seconds. Exhale completely.", duration_seconds: 40 },
      { instruction: "Physical reset: roll shoulders, plant feet firmly, look directly forward.", duration_seconds: 40 },
      { instruction: "Say: 'That was then. This is now. I start completely fresh from here.'", duration_seconds: 40 },
      { instruction: "Focus only on your very next specific action. Not the game. Not the result. Just this.", duration_seconds: 50 },
      { instruction: "Reset complete. Begin again.", duration_seconds: 30 },
    ]
  },
  {
    title: "The Mental Highlight Reel",
    category: "confidence",
    duration_seconds: 360,
    description: "Build and replay a mental compilation of your greatest moments to instantly boost self-belief.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. You are about to watch your personal greatest-hits reel.", duration_seconds: 30 },
      { instruction: "Recall your first great moment — feel exactly what you felt when it happened.", duration_seconds: 70 },
      { instruction: "Bring in your second highlight. Vivid, real, proud. Live it in real time.", duration_seconds: 70 },
      { instruction: "A third moment — one where you surprised even yourself.", duration_seconds: 70 },
      { instruction: "Feel what all three moments share: your capability, your effort, your results.", duration_seconds: 70 },
      { instruction: "Say: 'These are mine. This is what I am capable of. I do this.'", duration_seconds: 50 },
    ]
  },
  {
    title: "Decision Clarity Under Pressure",
    category: "match-day-calm",
    duration_seconds: 420,
    description: "Train yourself to make calm, committed decisions quickly when the stakes are highest.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Picture a high-stakes decision moment in your sport. Slow it down completely.", duration_seconds: 60 },
      { instruction: "What is the real choice? Strip absolutely everything else away.", duration_seconds: 70 },
      { instruction: "Your body knows. What does your gut say first — before the overthinking starts?", duration_seconds: 70 },
      { instruction: "Check: is this decision based on fear, or on performance? Fear or purpose?", duration_seconds: 70 },
      { instruction: "Commit to the decision. Hesitation is the real enemy — not a wrong choice.", duration_seconds: 80 },
      { instruction: "Say: 'I decide fast. I commit fully. I adjust as I go.'", duration_seconds: 50 },
      { instruction: "Open your eyes. Decisive action is a trainable skill. You just trained it.", duration_seconds: 30 },
    ]
  },
  {
    title: "Gratitude for the Journey",
    category: "recovery",
    duration_seconds: 300,
    description: "Shift perspective to deeply appreciate the entire journey of development, not just the results.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 50,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Think of one specific challenge you've overcome in your journey. Name it clearly.", duration_seconds: 60 },
      { instruction: "What specific skills or strength did you gain because of that exact challenge?", duration_seconds: 60 },
      { instruction: "Think of one person who helped you, even in a small way, on your path.", duration_seconds: 60 },
      { instruction: "The struggles made the skills possible. The journey created who you are today.", duration_seconds: 60 },
      { instruction: "Say: 'I am grateful for my whole journey — the easy parts and the hard ones equally.'", duration_seconds: 60 },
    ]
  },
  {
    title: "Cultivating Beginner's Mind",
    category: "pro-mental",
    duration_seconds: 360,
    description: "Approach every session with curiosity and openness — as if learning everything for the first time.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Before today's session: 'What if I knew nothing and had to learn this completely fresh?'", duration_seconds: 60 },
      { instruction: "Set aside all past performance — good or bad. Today is an entirely new page.", duration_seconds: 60 },
      { instruction: "Find one thing you haven't consciously noticed before in your practice. Actively look for it.", duration_seconds: 80 },
      { instruction: "Approach all feedback and struggle today as a curious student, not a judged performer.", duration_seconds: 80 },
      { instruction: "Say: 'I am always a student. There is always more to discover.'", duration_seconds: 50 },
      { instruction: "Begin with fresh eyes. Curiosity is the most underrated performance tool there is.", duration_seconds: 30 },
    ]
  },
  {
    title: "Vision Board Visualization",
    category: "visualization",
    duration_seconds: 480,
    description: "Mentally construct and inhabit a vivid vision board of your future achievements and ideal life.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. You are standing in front of a blank board. This space is entirely yours.", duration_seconds: 30 },
      { instruction: "Place your cricket goal on the board. See it as a vivid, specific, real image.", duration_seconds: 70 },
      { instruction: "Add your life vision — who you want to become, not just what you want to achieve.", duration_seconds: 80 },
      { instruction: "Fill in the people, places, and feelings. Make it complete, full, and real.", duration_seconds: 80 },
      { instruction: "Step into the board. Feel what it feels like to be living that vision fully.", duration_seconds: 90 },
      { instruction: "Identify one thing on the board you can actively move toward this week.", duration_seconds: 70 },
      { instruction: "Say: 'I see where I am going. I take one step every day.' Open your eyes.", duration_seconds: 40 },
      { instruction: "The vision is alive. Keep feeding it daily.", duration_seconds: 20 },
    ]
  },
  {
    title: "Responding to Unfairness",
    category: "pressure",
    duration_seconds: 420,
    description: "Develop mental resilience to maintain composure and peak performance when facing unfair situations.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Think of a moment you felt genuinely treated unfairly in your performance life.", duration_seconds: 60 },
      { instruction: "Acknowledge the frustration fully. It is valid. You are allowed to feel it.", duration_seconds: 60 },
      { instruction: "Ask: is fighting this serving my performance right now, or costing me more?", duration_seconds: 70 },
      { instruction: "Separate the injustice from your response. You can't always control what happens. You own how you respond.", duration_seconds: 80 },
      { instruction: "Channel the emotion: let it sharpen your focus, not scatter your attention.", duration_seconds: 80 },
      { instruction: "Say: 'Unfairness does not get to decide how I perform. Only I decide that.'", duration_seconds: 50 },
      { instruction: "Open your eyes. Your response to adversity is your real competitive edge.", duration_seconds: 30 },
    ]
  },
  {
    title: "Deep Focus Anchor",
    category: "focus",
    duration_seconds: 360,
    description: "Establish a physical trigger to instantly access a state of deep, laser-sharp concentration.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Recall a moment of total flow — completely absorbed, performing at your absolute best.", duration_seconds: 70 },
      { instruction: "Rebuild every detail: your breathing, posture, inner stillness, what you heard and felt.", duration_seconds: 70 },
      { instruction: "When the feeling peaks — press your thumb and middle finger together firmly. Hold 5 seconds.", duration_seconds: 60 },
      { instruction: "Release. Breathe normally. Allow the state to fully fade.", duration_seconds: 40 },
      { instruction: "Press the anchor again. Notice the focus returns. This is neurologically real — it works.", duration_seconds: 60 },
      { instruction: "Use this anchor before every training session or match. Repetition builds its strength.", duration_seconds: 30 },
      { instruction: "Say: 'When I press this anchor, I am instantly focused. Always.'", duration_seconds: 30 },
    ]
  },
  // ---- 6 FINAL UNIQUE ROUTINES ----
  {
    title: "Handling the Unplayable Ball",
    category: "pressure",
    duration_seconds: 420,
    description: "Train your mind to stay composed after getting out to a ball you couldn't have played differently.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Recall a dismissal that wasn't your fault — great delivery, bad luck, umpire call.", duration_seconds: 60 },
      { instruction: "Acknowledge: you could not have changed that outcome. Accept it fully.", duration_seconds: 60 },
      { instruction: "Ask: Am I carrying blame for something outside my control?", duration_seconds: 60 },
      { instruction: "Understand: top players get out to unplayable balls. That's cricket. It's not failure.", duration_seconds: 70 },
      { instruction: "Release the event. Extract zero self-criticism from it.", duration_seconds: 70 },
      { instruction: "Say: 'Some balls cannot be played. I cannot be beaten by what I cannot control.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Walk off with your head up. You did nothing wrong.", duration_seconds: 40 },
    ]
  },
  {
    title: "Deep Calm Breathing",
    category: "match-day-calm",
    duration_seconds: 300,
    description: "A pure, minimalist 5-minute breathing session to instantly restore calm before or during any match.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 50,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit or stand straight. Close your eyes if safe to do so.", duration_seconds: 20 },
      { instruction: "Breathe in slowly for 5 counts. Fill your lungs completely.", duration_seconds: 50 },
      { instruction: "Hold gently for 2 counts. Stay relaxed.", duration_seconds: 20 },
      { instruction: "Breathe out slowly for 7 counts. Let everything go.", duration_seconds: 60 },
      { instruction: "Repeat this cycle 5 more times. Each breath settles you deeper.", duration_seconds: 90 },
      { instruction: "Say: 'I am calm. I am ready. I belong here.'", duration_seconds: 40 },
      { instruction: "Open your eyes. The calm stays with you.", duration_seconds: 20 },
    ]
  },
  {
    title: "Batting Through the Hard Session",
    category: "visualization",
    duration_seconds: 480,
    description: "Mentally rehearse grinding out a difficult batting session under tough conditions to build resilience.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. The conditions are hard — seaming pitch, hostile bowlers, noisy crowd.", duration_seconds: 60 },
      { instruction: "See yourself defending early. Patient. Disciplined. Not trying to be a hero.", duration_seconds: 70 },
      { instruction: "A ball beats you. You let it go. Reset. Next ball.", duration_seconds: 60 },
      { instruction: "Overs pass. You're still there. Building your innings brick by brick.", duration_seconds: 80 },
      { instruction: "Feel the satisfaction of earning every single run through grit and patience.", duration_seconds: 80 },
      { instruction: "Understand: the hard session survived is worth more than a fluent fifty.", duration_seconds: 70 },
      { instruction: "Say: 'I can bat through anything. Patience is my weapon.'", duration_seconds: 50 },
      { instruction: "Open your eyes. That innings is inside you now.", duration_seconds: 30 },
    ]
  },
  {
    title: "Bowling Under Pressure",
    category: "focus",
    duration_seconds: 420,
    description: "Mentally rehearse bowling a perfect over in a pressure moment — final overs, death bowling, match on the line.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. Last over. 15 runs needed. You're bowling.", duration_seconds: 60 },
      { instruction: "Mark your run-up. Breathe. This is what you trained for.", duration_seconds: 60 },
      { instruction: "See your action — smooth, repeatable, perfectly grooved.", duration_seconds: 70 },
      { instruction: "One ball at a time. Block out the crowd, the scoreboard, the pressure.", duration_seconds: 70 },
      { instruction: "Each ball is its own moment. Nail your line. Nail your length.", duration_seconds: 70 },
      { instruction: "Say: 'I bowl one ball at a time. I trust my action completely.'", duration_seconds: 50 },
      { instruction: "Open your eyes. You've been in that moment. You'll handle it.", duration_seconds: 40 },
    ]
  },
  {
    title: "The Stillness Practice",
    category: "recovery",
    duration_seconds: 360,
    description: "A quiet 6-minute practice of pure stillness to clear mental fatigue and restore inner silence.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 55,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit or lie completely still. Set an intention: I am doing nothing for 6 minutes.", duration_seconds: 30 },
      { instruction: "Breathe naturally. Do not control it. Just let your body breathe itself.", duration_seconds: 60 },
      { instruction: "When thoughts arrive — notice them, label them 'thinking', and return to stillness.", duration_seconds: 80 },
      { instruction: "Let your nervous system fully downshift. You are not solving anything right now.", duration_seconds: 80 },
      { instruction: "Rest in the silence between thoughts. Even 1 second of stillness is enough.", duration_seconds: 70 },
      { instruction: "Say: 'I have found stillness. It is always available. I return here whenever I need.'", duration_seconds: 40 },
    ]
  },
  {
    title: "Post-Game Emotional Release",
    category: "recovery",
    duration_seconds: 480,
    description: "A guided session to fully process and release strong emotions after any significant performance.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Find somewhere quiet. Let the adrenaline settle. There is absolutely no rush here.", duration_seconds: 40 },
      { instruction: "Name the emotion you feel most strongly right now. Just one honest word.", duration_seconds: 50 },
      { instruction: "Allow it completely. Don't push it away or make it bigger. Just let it be present.", duration_seconds: 70 },
      { instruction: "Breathe deeply into the emotion. Then tense your whole body. Release everything at once.", duration_seconds: 70 },
      { instruction: "Ask: what is one thing I can genuinely be proud of from today's performance?", duration_seconds: 80 },
      { instruction: "Ask: what is the single most important lesson I take forward from today?", duration_seconds: 80 },
      { instruction: "Say: 'The performance is done. I gave what I had. I learn and I move forward.'", duration_seconds: 60 },
      { instruction: "Three slow, complete breaths. Step forward into your recovery.", duration_seconds: 30 },
    ]
  },
];