// 11 Unique Additional Mental Training Routines (duplicates removed from previous version)
export const EXTRA_MENTAL_ROUTINES_2 = [
  {
    title: "The Accountability Mirror",
    category: "confidence",
    duration_seconds: 360,
    description: "Hold yourself to your highest standard with honest self-accountability and clear commitment.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit quietly. Ask: Where am I not living up to my own standards this week?", duration_seconds: 70 },
      { instruction: "Be completely honest. No excuses. Just truth.", duration_seconds: 60 },
      { instruction: "Ask: What would the best version of me have done differently?", duration_seconds: 70 },
      { instruction: "Now choose: commit to one specific change you will make starting now.", duration_seconds: 70 },
      { instruction: "Accountability without action is just guilt. Action is the answer.", duration_seconds: 50 },
      { instruction: "Say: 'I hold myself to the standard I set. I close the gap today.'", duration_seconds: 40 },
    ]
  },
  {
    title: "Deep Breathing for Anxiety",
    category: "match-day-calm",
    duration_seconds: 300,
    description: "Diaphragmatic belly breathing to reduce anxiety at the physiological level within minutes.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 50,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit or lie down. Place one hand on your chest, one on your belly.", duration_seconds: 20 },
      { instruction: "Breathe in slowly through the nose for 4 counts. Feel your belly rise, not your chest.", duration_seconds: 40 },
      { instruction: "Hold gently for 2 counts.", duration_seconds: 20 },
      { instruction: "Exhale slowly through the mouth for 6 counts. Belly falls.", duration_seconds: 50 },
      { instruction: "Repeat this cycle 6 times. Let each exhale be a deliberate release.", duration_seconds: 100 },
      { instruction: "Notice the anxiety reducing with each breath. This is physiology, not willpower.", duration_seconds: 40 },
      { instruction: "You control your nervous system. Use this tool anytime.", duration_seconds: 30 },
    ]
  },
  {
    title: "Overcome Overthinking",
    category: "focus",
    duration_seconds: 420,
    description: "Break the overthinking loop and return to clear, decisive, present-moment thinking.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Notice you are overthinking. Name it out loud: 'I am overthinking right now.'", duration_seconds: 40 },
      { instruction: "Take 3 sharp exhales. Push the mental clutter out.", duration_seconds: 30 },
      { instruction: "Ask: What is the one thing I need to know or do right now?", duration_seconds: 60 },
      { instruction: "If action is needed: take it. If not: let it go. Binary clarity only.", duration_seconds: 60 },
      { instruction: "Overthinking is a loop. Break it with movement — stand up, change rooms, stretch.", duration_seconds: 60 },
      { instruction: "Say: 'I trust my instincts. I act on clarity. I release what I cannot control.'", duration_seconds: 60 },
      { instruction: "Return your attention to the present. Right here. This moment only.", duration_seconds: 60 },
      { instruction: "You do not need to solve everything at once.", duration_seconds: 30 },
    ]
  },
  {
    title: "Winning the Inner Battle",
    category: "pressure",
    duration_seconds: 480,
    description: "Master the conversation between your doubting mind and your performance self.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Identify the loudest negative voice in your head right now. What is it saying?", duration_seconds: 60 },
      { instruction: "Recognise: that voice is not truth. It is a pattern. It is not you.", duration_seconds: 60 },
      { instruction: "Counter each negative statement with a factual, grounded response.", duration_seconds: 90 },
      { instruction: "Now activate your performance voice: What does your best self say?", duration_seconds: 90 },
      { instruction: "The inner battle is won by which voice you feed. Choose deliberately.", duration_seconds: 60 },
      { instruction: "Say: 'I choose the voice of strength. I dismiss the voice of fear.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Act from strength, not fear.", duration_seconds: 30 },
      { instruction: "The inner battle is the real one. Win it first.", duration_seconds: 30 },
    ]
  },
  {
    title: "Cold Pressure Simulation",
    category: "pressure",
    duration_seconds: 360,
    description: "Mentally simulate extreme cold-start pressure to desensitise your response to it.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 75,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. You are cold-starting in the highest-pressure situation imaginable.", duration_seconds: 60 },
      { instruction: "No warm-up. No preparation. You must perform immediately. Feel the activation.", duration_seconds: 60 },
      { instruction: "Breathe through it. Your body activates within seconds if you allow it.", duration_seconds: 60 },
      { instruction: "See yourself performing — not perfectly, but competently and bravely.", duration_seconds: 70 },
      { instruction: "You did not collapse. You adapted. This is elite readiness.", duration_seconds: 60 },
      { instruction: "Say: 'I am ready at any moment. I need no perfect conditions to perform.'", duration_seconds: 50 },
    ]
  },
  {
    title: "Full Body Relaxation",
    category: "recovery",
    duration_seconds: 540,
    description: "Progressive muscle relaxation — systematically tense and release every muscle group for deep restoration.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Lie flat. Arms at sides. Close your eyes.", duration_seconds: 20 },
      { instruction: "Tense your feet hard for 5 seconds. Release. Feel the difference.", duration_seconds: 40 },
      { instruction: "Tense your calves and thighs. Hold 5 seconds. Release completely.", duration_seconds: 50 },
      { instruction: "Tense your core and glutes. Hold. Release. Breathe.", duration_seconds: 50 },
      { instruction: "Tense your hands into fists. Arms rigid. Hold. Release. Exhale.", duration_seconds: 50 },
      { instruction: "Tense your shoulders up to your ears. Hold. Drop completely.", duration_seconds: 50 },
      { instruction: "Scrunch your face. Hold every facial muscle. Release fully.", duration_seconds: 50 },
      { instruction: "Your whole body is relaxed. Feel the weight of complete ease.", duration_seconds: 90 },
      { instruction: "Stay here for one minute. Breathe slowly. You are fully restored.", duration_seconds: 100 },
    ]
  },
  {
    title: "Pre-Match Ritual Builder",
    category: "match-day-calm",
    duration_seconds: 480,
    description: "Build a consistent, personalised pre-match mental ritual that primes your best performance every single time.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Your ritual has 3 stages: physical prep, mental prime, focus lock. We build all three now.", duration_seconds: 40 },
      { instruction: "Physical: shake out tension, roll your shoulders, take 5 power breaths.", duration_seconds: 70 },
      { instruction: "Mental: recall your biggest performance moment. Stay in that feeling for 30 seconds.", duration_seconds: 90 },
      { instruction: "Mental: visualise the first 5 minutes of your performance going exactly right.", duration_seconds: 90 },
      { instruction: "Focus lock: choose your anchor cue — a word, phrase, or physical gesture.", duration_seconds: 60 },
      { instruction: "Execute your cue now. Feel the state shift.", duration_seconds: 60 },
      { instruction: "Run this same ritual before every performance. Consistency is power.", duration_seconds: 50 },
      { instruction: "Your ritual is set. Trust it. Use it. Every time.", duration_seconds: 40 },
    ]
  },
  {
    title: "Visualization for Skill Building",
    category: "visualization",
    duration_seconds: 540,
    description: "Use science-backed mental rehearsal to accelerate technical skill development between physical sessions.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 75,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Choose one specific skill you are currently developing.", duration_seconds: 30 },
      { instruction: "Close your eyes. See yourself performing it from the inside — your own perspective.", duration_seconds: 90 },
      { instruction: "Feel the muscle memory: the grip, the movement, the timing.", duration_seconds: 90 },
      { instruction: "Execute it perfectly 5 times in a row in your mind. Slow motion.", duration_seconds: 120 },
      { instruction: "Now at real speed. Still perfect. Still fluid.", duration_seconds: 70 },
      { instruction: "The brain fires the same neurons during vivid mental rehearsal as physical practice.", duration_seconds: 70 },
      { instruction: "Say: 'I have practised this perfectly. My body knows how.'", duration_seconds: 50 },
      { instruction: "Open your eyes. You just added a high-quality rep without moving.", duration_seconds: 20 },
    ]
  },
  {
    title: "Identity-Based Goal Setting",
    category: "pro-mental",
    duration_seconds: 540,
    description: "Set goals from the inside out — based on who you are becoming, not just what you want.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 75,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Ask: What kind of person achieves the goal I want? Define their identity.", duration_seconds: 90 },
      { instruction: "Ask: What daily habits does that person maintain without exception?", duration_seconds: 90 },
      { instruction: "Understand: goals come and go. Identity is permanent. Become the person first.", duration_seconds: 90 },
      { instruction: "Rewrite your goal as an identity statement. Not 'I want X' but 'I am someone who does X daily.'", duration_seconds: 90 },
      { instruction: "List 3 identity-based actions you will take this week.", duration_seconds: 90 },
      { instruction: "Say: 'I do not chase goals. I become the person who achieves them naturally.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Start becoming. Today.", duration_seconds: 30 },
    ]
  },
  {
    title: "Gratitude Before the Game",
    category: "match-day-calm",
    duration_seconds: 300,
    description: "Use deliberate gratitude to shift from anxiety to appreciation before any performance.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 50,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Pause. Before the pressure takes over, take 2 slow breaths.", duration_seconds: 30 },
      { instruction: "Name 3 things you are genuinely grateful for right in this moment.", duration_seconds: 70 },
      { instruction: "You are healthy enough to compete. Many would trade places with you.", duration_seconds: 50 },
      { instruction: "Gratitude and anxiety cannot fully coexist. Choose which to feed.", duration_seconds: 60 },
      { instruction: "Say: 'I am grateful to be here. I am grateful to compete. I give everything.'", duration_seconds: 50 },
      { instruction: "Perform with joy, not desperation. This is a privilege.", duration_seconds: 40 },
    ]
  },
  {
    title: "The 1% Better Mindset",
    category: "focus",
    duration_seconds: 360,
    description: "Adopt the compound growth mindset that turns small daily improvements into exceptional results over time.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 55,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Ask: What is one small thing I can do 1% better today than yesterday?", duration_seconds: 60 },
      { instruction: "Just 1%. Not 100%. Not a transformation. One small improvement.", duration_seconds: 50 },
      { instruction: "Understand: 1% better every day means you are 37 times better in one year.", duration_seconds: 60 },
      { instruction: "Compound growth is invisible in the short term and unstoppable in the long term.", duration_seconds: 60 },
      { instruction: "Identify your 1% for today. Make it specific.", duration_seconds: 60 },
      { instruction: "Say: 'I improve by 1% today. That is enough. That is everything.'", duration_seconds: 40 },
      { instruction: "Small is not small. Small is how all great things are built.", duration_seconds: 30 },
    ]
  },
];