import { EXTRA_MENTAL_ROUTINES } from './MentalRoutinesExtra';

// 90 Universal Mental Training Sessions
// Designed for any person seeking self-improvement — with cricket subtly in mind

const BASE_MENTAL_ROUTINES = [
  // ===== FOCUS (1-10) =====
  {
    title: "5-4-3-2-1 Grounding",
    category: "focus",
    duration_seconds: 300,
    description: "A sensory grounding technique to anchor your mind to the present moment.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 50,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit comfortably. Take 3 slow, deep breaths.", duration_seconds: 30 },
      { instruction: "Name 5 things you can SEE right now. Look slowly around you.", duration_seconds: 45 },
      { instruction: "Name 4 things you can TOUCH. Feel each texture.", duration_seconds: 40 },
      { instruction: "Name 3 things you can HEAR. Listen carefully.", duration_seconds: 35 },
      { instruction: "Name 2 things you can SMELL (or like the smell of).", duration_seconds: 30 },
      { instruction: "Name 1 thing you can TASTE right now.", duration_seconds: 20 },
      { instruction: "Take 3 final deep breaths. Notice how grounded and calm you feel.", duration_seconds: 30 },
      { instruction: "You are here. You are present. You are ready.", duration_seconds: 30 },
    ]
  },
  {
    title: "Single-Point Focus Drill",
    category: "focus",
    duration_seconds: 480,
    description: "Train your attention like a muscle by fixing it on a single point.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 55,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Choose a single point — a dot on the wall, a candle flame, or a still object.", duration_seconds: 20 },
      { instruction: "Fix your gaze there. Allow your breathing to slow naturally.", duration_seconds: 60 },
      { instruction: "When your mind wanders, gently return your gaze without judgment.", duration_seconds: 120 },
      { instruction: "Notice thoughts passing like clouds. Let them drift without following.", duration_seconds: 120 },
      { instruction: "Bring your attention back each time. This IS the practice.", duration_seconds: 120 },
      { instruction: "Close your eyes. Recreate the point in your mind.", duration_seconds: 40 },
    ]
  },
  {
    title: "The 4-7-8 Breath Lock",
    category: "focus",
    duration_seconds: 360,
    description: "Use rhythmic breathing to create calm, focused energy for performance.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 50,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit upright, hands on knees. Close your eyes.", duration_seconds: 20 },
      { instruction: "Inhale through the nose for 4 counts.", duration_seconds: 30 },
      { instruction: "Hold the breath for 7 counts.", duration_seconds: 40 },
      { instruction: "Exhale fully through the mouth for 8 counts. Repeat 4 times.", duration_seconds: 120 },
      { instruction: "Let your breathing return to normal. Notice the stillness.", duration_seconds: 60 },
      { instruction: "Set one clear intention for your next activity.", duration_seconds: 50 },
      { instruction: "Open your eyes slowly. You are locked in.", duration_seconds: 20 },
    ]
  },
  {
    title: "Distraction Shield",
    category: "focus",
    duration_seconds: 420,
    description: "Build mental resilience to external noise and internal distractions.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. Imagine a golden shield forming around your mind.", duration_seconds: 40 },
      { instruction: "Acknowledge any distractions you are aware of — noise, stress, worry.", duration_seconds: 40 },
      { instruction: "Visualise each distraction bouncing off the shield harmlessly.", duration_seconds: 60 },
      { instruction: "Breathe in: shield strengthens. Breathe out: distractions fade.", duration_seconds: 90 },
      { instruction: "Direct your full attention to your breathing — nothing else exists.", duration_seconds: 90 },
      { instruction: "Define the one thing that deserves your full attention right now.", duration_seconds: 60 },
      { instruction: "Your shield is active. Step into your world with full focus.", duration_seconds: 40 },
    ]
  },
  {
    title: "Flow State Trigger",
    category: "focus",
    duration_seconds: 600,
    description: "A ritual to enter the flow state — where time disappears and performance peaks.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 75,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit or stand in your performance posture. Own the space.", duration_seconds: 30 },
      { instruction: "Recall a time you were 'in the zone'. Feel the clarity and ease.", duration_seconds: 60 },
      { instruction: "Recreate the physical sensation — loose muscles, sharp eyes, quiet mind.", duration_seconds: 60 },
      { instruction: "Let your breathing become automatic. Trust your body.", duration_seconds: 90 },
      { instruction: "Visualise yourself performing effortlessly, fully absorbed.", duration_seconds: 120 },
      { instruction: "Say internally: 'I don't force flow. I allow it.'", duration_seconds: 60 },
      { instruction: "Take one deep breath. Step forward. Flow follows you.", duration_seconds: 60 },
      { instruction: "Hold the state for 2 more minutes. Let it deepen.", duration_seconds: 120 },
    ]
  },
  {
    title: "Countdown to Clarity",
    category: "focus",
    duration_seconds: 300,
    description: "A quick 5-minute pre-task ritual to clear mental fog instantly.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 50,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Stand or sit tall. Take 5 deep breaths.", duration_seconds: 60 },
      { instruction: "Count backward from 10 to 1, releasing a worry with each number.", duration_seconds: 60 },
      { instruction: "On 1 — your mind is blank and clear, like a fresh page.", duration_seconds: 30 },
      { instruction: "State your task or goal for the next hour out loud or in your head.", duration_seconds: 30 },
      { instruction: "Commit to zero multitasking. One thing. Full attention.", duration_seconds: 40 },
      { instruction: "Go. The timer is your signal.", duration_seconds: 30 },
      { instruction: "Final reset breath. Begin.", duration_seconds: 30 },
    ]
  },
  {
    title: "Body Scan Focus Reset",
    category: "focus",
    duration_seconds: 540,
    description: "Use a body scan to release physical tension and unlock mental sharpness.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Lie or sit comfortably. Close your eyes.", duration_seconds: 20 },
      { instruction: "Bring attention to your feet. Relax them completely.", duration_seconds: 40 },
      { instruction: "Move to your calves and knees. Release any holding.", duration_seconds: 40 },
      { instruction: "Thighs, hips, and lower back. Let go of weight.", duration_seconds: 50 },
      { instruction: "Stomach and chest. Breathe into any tightness.", duration_seconds: 50 },
      { instruction: "Shoulders and arms. Drop them down. Soften.", duration_seconds: 50 },
      { instruction: "Neck, jaw, and face. Unclench. Smooth out.", duration_seconds: 50 },
      { instruction: "Your whole body is relaxed. Your mind is sharp and free.", duration_seconds: 60 },
      { instruction: "Take three energising breaths. Open your eyes. Begin.", duration_seconds: 60 },
    ]
  },
  {
    title: "The Attention Anchor",
    category: "focus",
    duration_seconds: 480,
    description: "Create a personal mental anchor word that snaps you back to focus instantly.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Choose your anchor word — something powerful like 'NOW', 'HERE', or 'LOCK'.", duration_seconds: 30 },
      { instruction: "Close your eyes. Take 5 slow breaths.", duration_seconds: 60 },
      { instruction: "Repeat your anchor word silently 10 times with growing intensity.", duration_seconds: 60 },
      { instruction: "Notice your mind sharpen each time you say it.", duration_seconds: 60 },
      { instruction: "Practise deliberately losing focus, then using the anchor to return.", duration_seconds: 90 },
      { instruction: "Repeat 3 times. Each return makes the anchor stronger.", duration_seconds: 90 },
      { instruction: "This word is now wired to your focused state. Use it anytime.", duration_seconds: 30 },
    ]
  },
  {
    title: "Deep Work Preparation",
    category: "focus",
    duration_seconds: 600,
    description: "A complete mental preparation session before any demanding focused task.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 75,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Clear your workspace and close all distractions.", duration_seconds: 30 },
      { instruction: "Set a clear intention: what will you achieve in the next session?", duration_seconds: 40 },
      { instruction: "Do 10 deep breaths to move from passive to active mind state.", duration_seconds: 80 },
      { instruction: "Visualise completing the work — how it feels, what it looks like.", duration_seconds: 90 },
      { instruction: "Commit to the session. No interruptions. Full presence.", duration_seconds: 60 },
      { instruction: "Take 5 minutes of silence — no input. Let the mind settle.", duration_seconds: 300 },
    ]
  },
  {
    title: "Micro Focus Burst",
    category: "focus",
    duration_seconds: 180,
    description: "A 3-minute quick-fire focus reset you can use anywhere, anytime.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 35,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Stop. Wherever you are. Close your eyes if possible.", duration_seconds: 15 },
      { instruction: "Take 3 long, slow exhales. Let tension escape.", duration_seconds: 45 },
      { instruction: "Focus only on the sound of your breathing for 60 seconds.", duration_seconds: 60 },
      { instruction: "Name the one most important thing right now.", duration_seconds: 30 },
      { instruction: "Open your eyes. Engage completely. Go.", duration_seconds: 30 },
    ]
  },

  // ===== CONFIDENCE (11-20) =====
  {
    title: "The Power Pose Reset",
    category: "confidence",
    duration_seconds: 300,
    description: "Use body language and physiology to instantly access your confident self.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 50,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Stand with feet shoulder-width apart. Chest forward. Chin level.", duration_seconds: 30 },
      { instruction: "Place hands on hips or raise them above your head. Hold for 2 minutes.", duration_seconds: 120 },
      { instruction: "Breathe slowly and deeply. Own the space you're in.", duration_seconds: 60 },
      { instruction: "Say these words internally: 'I belong here. I am ready.'", duration_seconds: 30 },
      { instruction: "Lower your arms. Keep the posture. Walk forward with intention.", duration_seconds: 30 },
      { instruction: "You carry this with you. Confidence is physical first.", duration_seconds: 30 },
    ]
  },
  {
    title: "Evidence of Strength",
    category: "confidence",
    duration_seconds: 420,
    description: "Recall real moments of competence and success to build unshakeable self-belief.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit quietly and close your eyes.", duration_seconds: 20 },
      { instruction: "Recall 3 specific moments when you performed well or overcame something hard.", duration_seconds: 120 },
      { instruction: "For each memory — feel the pride, the satisfaction, the confidence.", duration_seconds: 90 },
      { instruction: "Remind yourself: those qualities still live in you. They never left.", duration_seconds: 60 },
      { instruction: "Say slowly: 'I have done hard things. I can do this too.'", duration_seconds: 40 },
      { instruction: "Carry this feeling into your day.", duration_seconds: 30 },
      { instruction: "Open your eyes. You have evidence. Use it.", duration_seconds: 30 },
      { instruction: "Final deep breath. Step forward.", duration_seconds: 30 },
    ]
  },
  {
    title: "The Inner Champion",
    category: "confidence",
    duration_seconds: 480,
    description: "Build an internal mentor — your strongest, calmest, most capable self.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. Imagine your most confident version of yourself.", duration_seconds: 60 },
      { instruction: "What does this person look like? How do they stand and move?", duration_seconds: 60 },
      { instruction: "What would they say to you right now? Listen carefully.", duration_seconds: 90 },
      { instruction: "Step into their body. Adopt their posture, their calm, their certainty.", duration_seconds: 90 },
      { instruction: "You are not performing confidence — you ARE confident. Feel the difference.", duration_seconds: 90 },
      { instruction: "Open your eyes. That person is you.", duration_seconds: 30 },
      { instruction: "Take one action from that place of strength today.", duration_seconds: 30 },
    ]
  },
  {
    title: "Self-Talk Rewrite",
    category: "confidence",
    duration_seconds: 360,
    description: "Identify and replace negative self-talk with accurate, empowering language.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 55,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Write or think of 3 things you often say negatively about yourself.", duration_seconds: 60 },
      { instruction: "For each one, ask: 'Is this absolutely true? Is it always true?'", duration_seconds: 60 },
      { instruction: "Replace each with a balanced, truthful statement.", duration_seconds: 60 },
      { instruction: "E.g. 'I always mess up' becomes 'I make mistakes, and I keep improving.'", duration_seconds: 60 },
      { instruction: "Repeat your new statements with conviction 5 times each.", duration_seconds: 60 },
      { instruction: "Notice the shift. Language shapes reality. Choose words with care.", duration_seconds: 30 },
      { instruction: "Commit to catching negative talk this week. Replace. Repeat.", duration_seconds: 30 },
    ]
  },
  {
    title: "Confidence Countdown",
    category: "confidence",
    duration_seconds: 300,
    description: "A fast-access confidence routine for right before a challenging moment.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 50,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Stand tall. Roll your shoulders back. Take a breath.", duration_seconds: 30 },
      { instruction: "Count down: 5 — recall a win. 4 — a skill you have. 3 — someone who believes in you.", duration_seconds: 60 },
      { instruction: "2 — your biggest strength. 1 — the reason you're doing this.", duration_seconds: 60 },
      { instruction: "On 0 — exhale completely. Reset. You are prepared.", duration_seconds: 40 },
      { instruction: "Say: 'I've got this.' Mean it.", duration_seconds: 30 },
      { instruction: "Walk forward. Don't look back.", duration_seconds: 30 },
      { instruction: "You've done the preparation. Trust it.", duration_seconds: 30 },
    ]
  },
  {
    title: "Comparison Detox",
    category: "confidence",
    duration_seconds: 540,
    description: "Break the habit of unhelpful comparison and reconnect with your own progress.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. Name a situation where you compared yourself unfavourably.", duration_seconds: 60 },
      { instruction: "Notice how this comparison makes you feel. Where does it live in your body?", duration_seconds: 60 },
      { instruction: "Understand that you see someone else's highlight, not their full story.", duration_seconds: 60 },
      { instruction: "Redirect: 'How have I grown compared to who I was 6 months ago?'", duration_seconds: 90 },
      { instruction: "List 3 real improvements, no matter how small.", duration_seconds: 60 },
      { instruction: "Your only competition is yesterday's version of yourself.", duration_seconds: 60 },
      { instruction: "Breathe. Appreciate your unique path. It is enough.", duration_seconds: 60 },
      { instruction: "Open your eyes. Run your race.", duration_seconds: 30 },
    ]
  },
  {
    title: "Affirmation Immersion",
    category: "confidence",
    duration_seconds: 420,
    description: "Deep repetition of personalised affirmations to rebuild self-belief at the core.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Choose 3 affirmations that feel true and empowering. Write them if possible.", duration_seconds: 60 },
      { instruction: "Close your eyes. Breathe in deeply.", duration_seconds: 30 },
      { instruction: "Repeat affirmation 1 — slowly, powerfully, 10 times.", duration_seconds: 80 },
      { instruction: "Repeat affirmation 2 — feel it in your chest as you say it.", duration_seconds: 80 },
      { instruction: "Repeat affirmation 3 — this one changes how you act today.", duration_seconds: 80 },
      { instruction: "Sit with the feeling for 30 seconds. Let it soak in.", duration_seconds: 30 },
      { instruction: "You believe what you repeatedly tell yourself. Choose well.", duration_seconds: 30 },
    ]
  },
  {
    title: "Courage Over Comfort",
    category: "confidence",
    duration_seconds: 480,
    description: "Build confidence by mentally rehearsing doing the hard, uncomfortable thing.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Identify one thing you've been avoiding out of fear.", duration_seconds: 60 },
      { instruction: "Visualise doing that thing, despite the fear, with calm determination.", duration_seconds: 90 },
      { instruction: "Notice how it feels on the other side — pride, relief, growth.", duration_seconds: 60 },
      { instruction: "Understand: confidence is not absence of fear. It's action despite fear.", duration_seconds: 60 },
      { instruction: "Name one small step toward facing this thing this week.", duration_seconds: 60 },
      { instruction: "Breathe. Feel your willingness to grow.", duration_seconds: 60 },
      { instruction: "Commit. One step. That's all it takes to begin.", duration_seconds: 30 },
      { instruction: "Open your eyes. You are braver than you think.", duration_seconds: 30 },
    ]
  },
  {
    title: "The Rejection Bounce",
    category: "confidence",
    duration_seconds: 360,
    description: "Process rejection or criticism quickly and emerge stronger from it.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Think of a recent rejection, failure, or critical comment.", duration_seconds: 60 },
      { instruction: "Allow yourself to feel the sting fully for 60 seconds. Don't suppress it.", duration_seconds: 60 },
      { instruction: "Ask: Is there useful feedback hidden here? Extract it honestly.", duration_seconds: 60 },
      { instruction: "Separate the feedback from your worth. Failure is not identity.", duration_seconds: 60 },
      { instruction: "Recall that every expert has been rejected countless times.", duration_seconds: 40 },
      { instruction: "Commit to one improvement based on the lesson.", duration_seconds: 30 },
      { instruction: "Breathe. Bounce. You're still here. That's everything.", duration_seconds: 30 },
    ]
  },
  {
    title: "Own the Room",
    category: "confidence",
    duration_seconds: 420,
    description: "A pre-social confidence ritual to feel grounded and authoritative in any setting.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Find a quiet space. Stand tall. Close your eyes.", duration_seconds: 30 },
      { instruction: "Breathe in for 4 counts, hold 4, out for 4. Repeat 4 times.", duration_seconds: 80 },
      { instruction: "Imagine the room, space, or meeting you're about to enter.", duration_seconds: 60 },
      { instruction: "See yourself entering calmly, speaking clearly, connecting easily.", duration_seconds: 60 },
      { instruction: "Feel the ease in your body. You have something to offer.", duration_seconds: 60 },
      { instruction: "Say: 'I add value to every space I enter.'", duration_seconds: 30 },
      { instruction: "Open your eyes. Walk in. You belong.", duration_seconds: 30 },
      { instruction: "Be curious about others — confidence grows through genuine connection.", duration_seconds: 30 },
    ]
  },

  // ===== PRESSURE & RESILIENCE (21-30) =====
  {
    title: "Pressure Is Privilege",
    category: "pressure",
    duration_seconds: 420,
    description: "Reframe pressure as a sign that you are trusted and capable.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Think of the pressure you're currently under. Let it be present.", duration_seconds: 60 },
      { instruction: "Ask: Why is there pressure? Because something matters. Because you're in the game.", duration_seconds: 60 },
      { instruction: "Pressure means stakes are real. That's not a problem — that's life.", duration_seconds: 60 },
      { instruction: "Breathe. Notice the adrenaline. Use it. It's fuel.", duration_seconds: 60 },
      { instruction: "Say: 'I was built for this. Pressure reveals my best self.'", duration_seconds: 40 },
      { instruction: "List 3 times you thrived under pressure before.", duration_seconds: 60 },
      { instruction: "The person who can handle the pressure earns the outcome.", duration_seconds: 40 },
      { instruction: "Breathe out. Step in. You're ready.", duration_seconds: 40 },
    ]
  },
  {
    title: "Storm and Stillness",
    category: "pressure",
    duration_seconds: 480,
    description: "Find your inner calm beneath the storm of high-pressure situations.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit. Imagine a storm raging around you — chaos, noise, pressure.", duration_seconds: 60 },
      { instruction: "Now go deeper — below the storm is stillness. Find it.", duration_seconds: 90 },
      { instruction: "The storm cannot reach the depths. Your core is always calm.", duration_seconds: 60 },
      { instruction: "Breathe into that deep stillness. Anchor there.", duration_seconds: 90 },
      { instruction: "From stillness, you can see clearly. Act wisely.", duration_seconds: 60 },
      { instruction: "Say: 'The storm is outside me. Peace is within me.'", duration_seconds: 40 },
      { instruction: "Carry this stillness into your challenge.", duration_seconds: 40 },
      { instruction: "Open your eyes. The storm is still there. So is your stillness.", duration_seconds: 40 },
    ]
  },
  {
    title: "The Reset Button",
    category: "pressure",
    duration_seconds: 300,
    description: "A fast, reliable ritual to mentally reset after making a mistake.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 50,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Acknowledge the mistake. Say internally: 'That happened. It's done.'", duration_seconds: 40 },
      { instruction: "Take one slow breath in. On the exhale — let it go completely.", duration_seconds: 40 },
      { instruction: "Shake hands, clap, tap the ground — a physical reset cue.", duration_seconds: 30 },
      { instruction: "Say: 'Next ball. Next moment. Now.'", duration_seconds: 30 },
      { instruction: "Focus on the very next action. Nothing else.", duration_seconds: 60 },
      { instruction: "You are only ever as good as your next move. Make it.", duration_seconds: 30 },
      { instruction: "Reset complete. Go again.", duration_seconds: 30 },
      { instruction: "Breathe. Present. Go.", duration_seconds: 30 },
    ]
  },
  {
    title: "Mental Toughness Builder",
    category: "pressure",
    duration_seconds: 600,
    description: "Develop the ability to keep going when everything in you wants to quit.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 85,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Think of the hardest thing you've ever pushed through. Really feel it.", duration_seconds: 60 },
      { instruction: "Recognise that you survived it. You proved something to yourself.", duration_seconds: 60 },
      { instruction: "Think of your current challenge. Is it harder than what you've survived? Maybe. But you're stronger now.", duration_seconds: 90 },
      { instruction: "Sit with discomfort deliberately — don't move, don't adjust for 2 minutes.", duration_seconds: 120 },
      { instruction: "Notice the urge to quit or escape. Breathe through it.", duration_seconds: 90 },
      { instruction: "Say: 'I am tougher than my thoughts of giving up.'", duration_seconds: 60 },
      { instruction: "Toughness is not absence of struggle. It is choosing to continue despite it.", duration_seconds: 60 },
      { instruction: "Open your eyes. You are tougher than yesterday.", duration_seconds: 60 },
    ]
  },
  {
    title: "Nervous Energy Converter",
    category: "pressure",
    duration_seconds: 360,
    description: "Transform pre-performance nerves into focused, positive energy.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 55,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Notice the nervous feeling in your body. Butterflies, heart rate, tight chest.", duration_seconds: 50 },
      { instruction: "Label it: not anxiety. Just energy. Your body preparing.", duration_seconds: 50 },
      { instruction: "Say: 'I am not nervous. I am excited. Same feeling. Different meaning.'", duration_seconds: 40 },
      { instruction: "Channel it: 5 deep breaths, shake out your arms, roll your neck.", duration_seconds: 60 },
      { instruction: "Redirect the energy into intention — what are you here to do?", duration_seconds: 60 },
      { instruction: "The energy is fuel. Step on the accelerator.", duration_seconds: 40 },
      { instruction: "Breathe. Convert. Perform.", duration_seconds: 30 },
      { instruction: "Go. The nerves confirm you care. That's perfect.", duration_seconds: 30 },
    ]
  },
  {
    title: "Adversity as Advantage",
    category: "pressure",
    duration_seconds: 480,
    description: "Learn to see setbacks and obstacles as accelerators of growth.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Name one major adversity you have faced. Sit with it without judgment.", duration_seconds: 60 },
      { instruction: "Ask: What did I learn that I could not have learned any other way?", duration_seconds: 90 },
      { instruction: "Ask: Who did I become because of this experience?", duration_seconds: 90 },
      { instruction: "Understand: the people who handle adversity best are those who find meaning in it.", duration_seconds: 60 },
      { instruction: "Find one thing you're grateful for because of this difficulty.", duration_seconds: 60 },
      { instruction: "Say: 'This happened FOR me, not TO me.'", duration_seconds: 40 },
      { instruction: "Breathe. Let the lesson become your superpower.", duration_seconds: 40 },
      { instruction: "Open your eyes. Your adversity is your advantage.", duration_seconds: 40 },
    ]
  },
  {
    title: "High Stakes Rehearsal",
    category: "pressure",
    duration_seconds: 600,
    description: "Mentally rehearse performing at your best in the highest-pressure scenarios.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 85,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. Create the highest-pressure version of your upcoming challenge.", duration_seconds: 60 },
      { instruction: "Feel the weight of it. The eyes watching. The stakes. The moment.", duration_seconds: 90 },
      { instruction: "Now perform. See yourself calm, decisive, skilled.", duration_seconds: 120 },
      { instruction: "When the imagined pressure spikes — breathe through it. Continue.", duration_seconds: 90 },
      { instruction: "See the successful outcome. Feel the relief, pride, satisfaction.", duration_seconds: 90 },
      { instruction: "Return to present. Your brain has now done this. It knows the path.", duration_seconds: 60 },
      { instruction: "You've trained for the worst and performed your best.", duration_seconds: 60 },
      { instruction: "Open your eyes. You've already been there. You'll be fine.", duration_seconds: 30 },
    ]
  },
  {
    title: "The Unshakeable Foundation",
    category: "pressure",
    duration_seconds: 540,
    description: "Connect to your core values to stay grounded under any external pressure.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 75,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. Go inward.", duration_seconds: 30 },
      { instruction: "Ask: What are my 3 most important core values? Take time to find real ones.", duration_seconds: 90 },
      { instruction: "For each value, recall a time you lived it fully. Feel that integrity.", duration_seconds: 120 },
      { instruction: "Understand: as long as you act in line with your values, external results do not define you.", duration_seconds: 90 },
      { instruction: "Breathe into your values. They are your foundation.", duration_seconds: 60 },
      { instruction: "Say: 'No pressure can shake what I stand for.'", duration_seconds: 40 },
      { instruction: "Open your eyes. Your foundation is solid. Build from here.", duration_seconds: 30 },
      { instruction: "Today, find one opportunity to act from your deepest values.", duration_seconds: 30 },
    ]
  },
  {
    title: "Let It Go Protocol",
    category: "pressure",
    duration_seconds: 420,
    description: "Release what is not within your control and focus only on what is.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Draw a mental circle. Inside = what you control. Outside = everything else.", duration_seconds: 60 },
      { instruction: "Name 3 things outside your control that you have been worrying about.", duration_seconds: 60 },
      { instruction: "Acknowledge: 'This is not mine to carry.' Breathe it out.", duration_seconds: 60 },
      { instruction: "Now name 3 things inside your control today.", duration_seconds: 60 },
      { instruction: "Place all your energy there. Water what you can grow.", duration_seconds: 60 },
      { instruction: "Release the rest with a full exhale.", duration_seconds: 60 },
      { instruction: "Open your eyes. Do one thing in your control. Right now.", duration_seconds: 30 },
      { instruction: "Peace comes from controlling what is yours.", duration_seconds: 30 },
    ]
  },
  {
    title: "10-Second Rule",
    category: "pressure",
    duration_seconds: 300,
    description: "Train yourself to pause, breathe, and choose your response in any pressure moment.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 50,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Think of a recent moment you reacted badly under pressure.", duration_seconds: 50 },
      { instruction: "Imagine: what if you had paused for 10 seconds before responding?", duration_seconds: 50 },
      { instruction: "Practice that pause now. Breathe slowly for 10 counts.", duration_seconds: 60 },
      { instruction: "In that pause: you choose your response. Stimulus → Pause → Response.", duration_seconds: 50 },
      { instruction: "Commit to using the 10-second rule at least once today.", duration_seconds: 40 },
      { instruction: "The pause is power. The pause is wisdom.", duration_seconds: 30 },
      { instruction: "Breathe. Choose. Act with intention.", duration_seconds: 30 },
    ]
  },

  // ===== RECOVERY & SELF-COMPASSION (31-40) =====
  {
    title: "Breathe Through the Bad Day",
    category: "recovery",
    duration_seconds: 420,
    description: "A compassionate session to process a tough day and restore your balance.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit somewhere comfortable. Give yourself full permission to be here.", duration_seconds: 30 },
      { instruction: "Name what happened today without judgment. Just facts.", duration_seconds: 60 },
      { instruction: "Name how it made you feel. Fully, honestly.", duration_seconds: 60 },
      { instruction: "Take 5 long, slow breaths. Exhale longer than the inhale.", duration_seconds: 80 },
      { instruction: "Ask: What is one small thing I can appreciate from today?", duration_seconds: 60 },
      { instruction: "Say: 'One hard day does not define my path.'", duration_seconds: 40 },
      { instruction: "Tomorrow is a new start. Tonight, you rest. You've earned it.", duration_seconds: 40 },
      { instruction: "Close your eyes for 30 seconds. Let your body soften.", duration_seconds: 30 },
      { instruction: "You are more than your worst day.", duration_seconds: 30 },
    ]
  },
  {
    title: "Self-Compassion Practice",
    category: "recovery",
    duration_seconds: 480,
    description: "Treat yourself with the kindness you would give a friend in the same situation.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Think of something you've been criticising yourself for.", duration_seconds: 60 },
      { instruction: "Imagine a close friend came to you with this exact problem. What would you say?", duration_seconds: 90 },
      { instruction: "Now say that same thing to yourself. With the same warmth.", duration_seconds: 90 },
      { instruction: "Place your hand on your heart. Feel the warmth.", duration_seconds: 60 },
      { instruction: "Say: 'I am doing my best. That is enough. I deserve kindness too.'", duration_seconds: 60 },
      { instruction: "Breathe into the kindness. Let it in.", duration_seconds: 60 },
      { instruction: "You cannot pour from an empty cup. Fill yours first.", duration_seconds: 30 },
      { instruction: "Breathe. You are worthy of your own compassion.", duration_seconds: 30 },
    ]
  },
  {
    title: "Failure as Feedback",
    category: "recovery",
    duration_seconds: 420,
    description: "Reframe failure as information and extract the growth from any setback.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Name a recent failure or disappointment.", duration_seconds: 40 },
      { instruction: "Ask: What information does this failure contain?", duration_seconds: 60 },
      { instruction: "Ask: What did I learn that I would not have learned if I'd succeeded?", duration_seconds: 60 },
      { instruction: "Ask: What is the next specific step to improve?", duration_seconds: 60 },
      { instruction: "Separate the result from your identity. You failed at something. You are not a failure.", duration_seconds: 90 },
      { instruction: "Say: 'Every attempt makes me better. Even the ugly ones.'", duration_seconds: 40 },
      { instruction: "Breathe. Extract. Move forward.", duration_seconds: 30 },
      { instruction: "Failure is not the opposite of success. It's part of it.", duration_seconds: 30 },
    ]
  },
  {
    title: "Sleep and Recovery Reset",
    category: "recovery",
    duration_seconds: 600,
    description: "A full wind-down session to prepare mind and body for deep, restorative sleep.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Lie down comfortably. Put the phone away after this step.", duration_seconds: 30 },
      { instruction: "Review your day with gratitude — 3 things you're grateful for.", duration_seconds: 90 },
      { instruction: "Release the day. It is done. You've done what you could.", duration_seconds: 60 },
      { instruction: "Take 10 deep, slow breaths. With each exhale, your body gets heavier.", duration_seconds: 120 },
      { instruction: "Scan from head to feet. Release every muscle.", duration_seconds: 120 },
      { instruction: "Imagine a warm, golden light filling your body as you breathe in.", duration_seconds: 90 },
      { instruction: "Say slowly: 'I am safe. I am rested. Tomorrow is ready for me.'", duration_seconds: 60 },
      { instruction: "Let yourself drift. Sleep is recovery. Recovery is performance.", duration_seconds: 30 },
    ]
  },
  {
    title: "Emotional Drain Release",
    category: "recovery",
    duration_seconds: 480,
    description: "Process and release built-up emotional tension without suppressing or exploding.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Find a private space. Give yourself full permission to feel.", duration_seconds: 30 },
      { instruction: "Name the dominant emotion: frustration, sadness, anger, disappointment.", duration_seconds: 60 },
      { instruction: "Where does it live in your body? Chest, throat, shoulders?", duration_seconds: 60 },
      { instruction: "Breathe directly into that space. Expand it. Don't fight it.", duration_seconds: 90 },
      { instruction: "Let the feeling peak and then — exhale it out slowly.", duration_seconds: 90 },
      { instruction: "You are bigger than any emotion. You contain it — it doesn't contain you.", duration_seconds: 60 },
      { instruction: "Take 3 deep cleansing breaths. Feel the release.", duration_seconds: 60 },
      { instruction: "Emotions are not weakness. Processing them is strength.", duration_seconds: 30 },
    ]
  },
  {
    title: "The Gratitude Anchor",
    category: "recovery",
    duration_seconds: 360,
    description: "Use gratitude deliberately to shift your mental state from depleted to restored.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 55,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. Think of 5 things you're genuinely grateful for right now.", duration_seconds: 90 },
      { instruction: "Don't rush. For each one, pause and feel real appreciation.", duration_seconds: 90 },
      { instruction: "Breathe into that feeling of gratitude. It is abundant.", duration_seconds: 60 },
      { instruction: "Notice how your state shifts. This is not denial — it's perspective.", duration_seconds: 60 },
      { instruction: "Say: 'There is enough. I am enough. Life has given me gifts.'", duration_seconds: 30 },
      { instruction: "Carry one grateful thought into the next hour.", duration_seconds: 30 },
    ]
  },
  {
    title: "Boundaries and Burnout Prevention",
    category: "recovery",
    duration_seconds: 480,
    description: "Protect your energy and establish clear limits to sustain long-term performance.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Check in honestly: are you running on empty? What has depleted you?", duration_seconds: 60 },
      { instruction: "Name 2 things you are currently doing that drain your energy unnecessarily.", duration_seconds: 60 },
      { instruction: "Name 2 things that restore you. How often do you do them?", duration_seconds: 60 },
      { instruction: "Understand: saying no to what drains you IS saying yes to your best self.", duration_seconds: 90 },
      { instruction: "Commit to protecting one block of recovery time this week.", duration_seconds: 60 },
      { instruction: "You cannot sustain output without input. Rest is not weakness.", duration_seconds: 60 },
      { instruction: "Breathe. Slow down. Protect your energy like your most valuable asset.", duration_seconds: 60 },
      { instruction: "You perform best when you're replenished. Protect that.", duration_seconds: 30 },
    ]
  },
  {
    title: "Forgiveness and Forward Movement",
    category: "recovery",
    duration_seconds: 540,
    description: "Release guilt, regret, or resentment and choose freedom through forgiveness.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 80,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Identify something you're struggling to forgive — yourself or someone else.", duration_seconds: 60 },
      { instruction: "Understand: forgiveness is not condoning. It is freeing yourself.", duration_seconds: 60 },
      { instruction: "Feel the weight of holding it. What does that cost you every day?", duration_seconds: 90 },
      { instruction: "Take 5 deep breaths. On each exhale, loosen your grip on it.", duration_seconds: 90 },
      { instruction: "Say: 'I choose to set this down. Not for them — for me.'", duration_seconds: 60 },
      { instruction: "Imagine walking forward without that weight. Lighter. Clearer.", duration_seconds: 90 },
      { instruction: "Forgiveness is a process. Begin it here. Return to it as needed.", duration_seconds: 60 },
      { instruction: "Open your eyes. Move forward. You deserve that lightness.", duration_seconds: 30 },
    ]
  },
  {
    title: "Celebrate the Small Wins",
    category: "recovery",
    duration_seconds: 300,
    description: "Build momentum and restore motivation by honouring your incremental progress.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 50,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "List 5 small wins from this week. No win is too small.", duration_seconds: 80 },
      { instruction: "For each one, pause and genuinely acknowledge: 'I did that.'", duration_seconds: 80 },
      { instruction: "Feel the satisfaction. You are moving forward.", duration_seconds: 60 },
      { instruction: "Understand: small wins compound into big results.", duration_seconds: 40 },
      { instruction: "Say: 'Progress is progress. I honour every step.'", duration_seconds: 40 },
    ]
  },
  {
    title: "Intentional Rest",
    category: "recovery",
    duration_seconds: 600,
    description: "Actively rest — a conscious, deliberate recovery session for mind and body.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Lie or sit completely still. No screens. No tasks. Just be.", duration_seconds: 60 },
      { instruction: "Give yourself full permission to do nothing for these minutes.", duration_seconds: 30 },
      { instruction: "Breathe naturally. Don't control it. Just observe.", duration_seconds: 120 },
      { instruction: "Let your mind wander freely. Don't guide it.", duration_seconds: 120 },
      { instruction: "Feel your body getting heavier. Your nervous system is resetting.", duration_seconds: 120 },
      { instruction: "When you're ready, wiggle your fingers and toes.", duration_seconds: 60 },
      { instruction: "Rest is not laziness. Rest is how champions recharge.", duration_seconds: 60 },
      { instruction: "Rise refreshed. You've earned this.", duration_seconds: 30 },
    ]
  },

  // ===== VISUALIZATION (41-50) =====
  {
    title: "The Perfect Performance",
    category: "visualization",
    duration_seconds: 540,
    description: "Mentally rehearse your ideal performance from start to finish in vivid detail.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 75,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. Breathe in deeply 5 times.", duration_seconds: 60 },
      { instruction: "See the environment of your performance — every detail. Where are you?", duration_seconds: 60 },
      { instruction: "Feel your body — grounded, ready, alive.", duration_seconds: 60 },
      { instruction: "Begin performing. See every move in slow-motion clarity.", duration_seconds: 120 },
      { instruction: "When a challenge arises, handle it with calm mastery.", duration_seconds: 90 },
      { instruction: "See the successful finish. The feeling. The achievement.", duration_seconds: 60 },
      { instruction: "Your brain cannot distinguish a vividly imagined experience from a real one.", duration_seconds: 60 },
      { instruction: "You've performed this. Now do it for real.", duration_seconds: 30 },
    ]
  },
  {
    title: "Goal Movie",
    category: "visualization",
    duration_seconds: 600,
    description: "Create a vivid mental film of your future self achieving your biggest goal.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 80,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. Set the scene — 12 months from now.", duration_seconds: 60 },
      { instruction: "You have achieved your biggest current goal. Where are you?", duration_seconds: 60 },
      { instruction: "What do you see? What does success look like, concretely?", duration_seconds: 90 },
      { instruction: "How do you feel? Pride? Freedom? Relief? Stay there.", duration_seconds: 90 },
      { instruction: "Who is with you? What are they saying?", duration_seconds: 60 },
      { instruction: "Play the full movie. Let it be rich and emotional.", duration_seconds: 120 },
      { instruction: "Say: 'This is where I am going. Every action I take today moves me here.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Your future is pulling you toward it.", duration_seconds: 30 },
      { instruction: "What one action can you take today toward this vision?", duration_seconds: 30 },
    ]
  },
  {
    title: "Master Skill Replay",
    category: "visualization",
    duration_seconds: 480,
    description: "Mentally rehearse a specific skill or technique to hardwire it into your memory.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Choose one specific skill you want to improve.", duration_seconds: 40 },
      { instruction: "Close your eyes. See yourself performing it perfectly.", duration_seconds: 90 },
      { instruction: "Go through every element in slow motion. Feel the sensation.", duration_seconds: 90 },
      { instruction: "Replay it 5 times. Each time cleaner, more effortless.", duration_seconds: 120 },
      { instruction: "Speed it up to real time. Still perfect. Still yours.", duration_seconds: 60 },
      { instruction: "Say: 'This is natural for me. My body knows this.'", duration_seconds: 50 },
      { instruction: "Open your eyes. The brain pattern is strengthened.", duration_seconds: 30 },
    ]
  },
  {
    title: "Best Self Morning",
    category: "visualization",
    duration_seconds: 420,
    description: "Begin your day by visualising the ideal version of how it will unfold.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit up in bed or a chair. Eyes closed. Take 5 deep breaths.", duration_seconds: 60 },
      { instruction: "See today unfolding — from morning to evening at its best.", duration_seconds: 90 },
      { instruction: "Who are you in this day? How do you show up for yourself and others?", duration_seconds: 90 },
      { instruction: "Identify the 3 most important things you will accomplish today.", duration_seconds: 60 },
      { instruction: "See yourself completing them with focus and calm.", duration_seconds: 60 },
      { instruction: "Say: 'Today I show up as my best self.'", duration_seconds: 30 },
      { instruction: "Open your eyes. Begin.", duration_seconds: 30 },
    ]
  },
  {
    title: "Future Memory",
    category: "visualization",
    duration_seconds: 480,
    description: "Imagine your future self looking back on this moment as a turning point.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. Project yourself 5 years forward.", duration_seconds: 60 },
      { instruction: "See your future self — wiser, stronger, further along.", duration_seconds: 60 },
      { instruction: "This future self is looking back at you — right now, today.", duration_seconds: 60 },
      { instruction: "What would they say? What advice do they offer?", duration_seconds: 90 },
      { instruction: "What did they do, starting today, that made the difference?", duration_seconds: 90 },
      { instruction: "Hear their words. Take them seriously.", duration_seconds: 60 },
      { instruction: "Say: 'I trust the path. I begin now.'", duration_seconds: 30 },
      { instruction: "Open your eyes. Your future self is cheering you on.", duration_seconds: 30 },
    ]
  },
  {
    title: "Obstacle Visualisation",
    category: "visualization",
    duration_seconds: 480,
    description: "Prepare for challenges by mentally rehearsing navigating through them.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Identify your most likely obstacle or resistance for your next challenge.", duration_seconds: 60 },
      { instruction: "See it vividly. Don't avoid it — look at it clearly.", duration_seconds: 60 },
      { instruction: "Now see yourself encountering it and responding with skill and calm.", duration_seconds: 90 },
      { instruction: "Watch yourself navigate around, through, or over it.", duration_seconds: 90 },
      { instruction: "Success is not the absence of obstacles. It's consistent navigation past them.", duration_seconds: 60 },
      { instruction: "Replay this 3 times. Each time, feel more capable.", duration_seconds: 90 },
      { instruction: "Open your eyes. You have a plan. You've seen the path.", duration_seconds: 30 },
    ]
  },
  {
    title: "The Champion Mindset Simulation",
    category: "visualization",
    duration_seconds: 600,
    description: "Inhabit the mind and body of someone who has achieved what you are working toward.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 85,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Think of a person — real or imagined — who represents your ideal performance.", duration_seconds: 60 },
      { instruction: "Close your eyes. Step inside their perspective.", duration_seconds: 60 },
      { instruction: "How do they see challenges? How do they prepare? How do they recover?", duration_seconds: 90 },
      { instruction: "How does it feel to operate from that level?", duration_seconds: 90 },
      { instruction: "Now step back into yourself — carrying those qualities.", duration_seconds: 90 },
      { instruction: "You don't need to be them. You need to activate those qualities within yourself.", duration_seconds: 90 },
      { instruction: "Say: 'I choose to operate at my highest level starting now.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Walk like that person.", duration_seconds: 30 },
      { instruction: "You already have what it takes. Step into it.", duration_seconds: 30 },
    ]
  },
  {
    title: "Calm Under Pressure Visualisation",
    category: "visualization",
    duration_seconds: 480,
    description: "Mentally rehearse staying calm and effective during your most stressful moments.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. Create the most pressure-filled version of an upcoming situation.", duration_seconds: 60 },
      { instruction: "Feel the tension rising. Don't suppress it.", duration_seconds: 60 },
      { instruction: "Now see yourself: breathing. Steady. Clear-headed.", duration_seconds: 90 },
      { instruction: "See yourself making a great decision in that moment.", duration_seconds: 90 },
      { instruction: "Replay 3 more high-pressure moments — in each one, you remain calm.", duration_seconds: 120 },
      { instruction: "Calm is a skill. You are training it now.", duration_seconds: 40 },
      { instruction: "Open your eyes. You've been here before. You handled it.", duration_seconds: 30 },
    ]
  },
  {
    title: "Healing Visualisation",
    category: "visualization",
    duration_seconds: 540,
    description: "Support physical and mental recovery through guided healing imagery.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Lie comfortably. Close your eyes. Breathe slowly.", duration_seconds: 40 },
      { instruction: "Bring awareness to any area of pain, tension, or injury.", duration_seconds: 60 },
      { instruction: "Breathe healing energy into that area with each inhale.", duration_seconds: 90 },
      { instruction: "Visualise warm light flowing to the area, soothing and restoring.", duration_seconds: 90 },
      { instruction: "With each exhale, see the tension or pain dissolving.", duration_seconds: 90 },
      { instruction: "See yourself healthy, strong, and moving freely.", duration_seconds: 90 },
      { instruction: "Your mind is a powerful part of your recovery. Use it.", duration_seconds: 60 },
      { instruction: "Breathe. Heal. Trust the process.", duration_seconds: 30 },
    ]
  },
  {
    title: "New Identity Visualisation",
    category: "visualization",
    duration_seconds: 600,
    description: "Shift how you see yourself by actively visualising a new, upgraded identity.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 85,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Ask: Who do I need to become to achieve what I want?", duration_seconds: 60 },
      { instruction: "Define that identity: disciplined, calm, skilled, resilient, consistent.", duration_seconds: 90 },
      { instruction: "Close your eyes. Step into that identity fully.", duration_seconds: 60 },
      { instruction: "See your day through their eyes — how they move, decide, respond.", duration_seconds: 120 },
      { instruction: "Feel the difference between who you are and who you're becoming.", duration_seconds: 90 },
      { instruction: "Make that gap smaller with each breath.", duration_seconds: 90 },
      { instruction: "Say: 'I am already becoming this person. Each day, more.'", duration_seconds: 60 },
      { instruction: "Open your eyes. The identity shift begins with belief.", duration_seconds: 30 },
    ]
  },

  // ===== MATCH DAY & PRE-PERFORMANCE (51-60) =====
  {
    title: "Game Day Activation",
    category: "match-day-calm",
    duration_seconds: 420,
    description: "A complete mental warm-up to prime mind and body for peak performance.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Find a quiet moment. Sit or stand alone. Breathe.", duration_seconds: 30 },
      { instruction: "Connect to your purpose: why are you doing this today?", duration_seconds: 60 },
      { instruction: "Run through your routine: physical warm-up, mental preparation, focus cue.", duration_seconds: 60 },
      { instruction: "See your best performance. Feel it in your body.", duration_seconds: 90 },
      { instruction: "Release the outcome. Focus only on the process.", duration_seconds: 60 },
      { instruction: "Take one powerful breath. Let it out slowly.", duration_seconds: 40 },
      { instruction: "Say your performance cue word. You're activated.", duration_seconds: 30 },
      { instruction: "Step out. Trust yourself.", duration_seconds: 30 },
    ]
  },
  {
    title: "Pre-Performance Calm",
    category: "match-day-calm",
    duration_seconds: 360,
    description: "Settle your mind and slow your heart rate before any performance.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 55,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit or stand in a quiet space. Close your eyes.", duration_seconds: 20 },
      { instruction: "Breathe in for 4 counts. Out for 6 counts. Repeat 6 times.", duration_seconds: 120 },
      { instruction: "Feel your heart rate slowing. Your thoughts quieting.", duration_seconds: 60 },
      { instruction: "Visualise a calm lake inside your chest. Still and clear.", duration_seconds: 60 },
      { instruction: "Nothing outside can disturb that inner lake.", duration_seconds: 40 },
      { instruction: "Say: 'I am calm. I am ready. I am focused.'", duration_seconds: 30 },
      { instruction: "Open your eyes. The calm goes with you.", duration_seconds: 30 },
    ]
  },
  {
    title: "Letting Go of Last Time",
    category: "match-day-calm",
    duration_seconds: 420,
    description: "Release the memory of past poor performance so it cannot contaminate the present.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Acknowledge the previous performance honestly. Don't suppress it.", duration_seconds: 60 },
      { instruction: "Extract one lesson. That's all it owed you.", duration_seconds: 60 },
      { instruction: "Now place that performance in an imaginary box and seal it.", duration_seconds: 60 },
      { instruction: "Today is a blank page. Fresh score. New moment.", duration_seconds: 60 },
      { instruction: "You are not your last result. You are your next action.", duration_seconds: 60 },
      { instruction: "Breathe. Clear the cache. Start fresh.", duration_seconds: 60 },
      { instruction: "This moment is all you have. Use it fully.", duration_seconds: 30 },
      { instruction: "Open your eyes. The past has released you.", duration_seconds: 30 },
    ]
  },
  {
    title: "Team Energy Alignment",
    category: "match-day-calm",
    duration_seconds: 360,
    description: "Align mentally with the collective energy and shared purpose of a team.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 55,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Think about every person on your team. Their faces. Their effort.", duration_seconds: 60 },
      { instruction: "Feel the connection. You are all working toward the same thing.", duration_seconds: 60 },
      { instruction: "Your individual performance lifts everyone.", duration_seconds: 60 },
      { instruction: "Visualise doing your role brilliantly — for the team.", duration_seconds: 60 },
      { instruction: "Feel the collective energy like a current you can plug into.", duration_seconds: 60 },
      { instruction: "Say: 'I show up for my team. My best helps everyone.'", duration_seconds: 30 },
      { instruction: "Open your eyes. You're part of something bigger.", duration_seconds: 30 },
    ]
  },
  {
    title: "Focus Lock-In",
    category: "match-day-calm",
    duration_seconds: 300,
    description: "A 5-minute lock-in session to eliminate external thoughts before performance.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 50,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Step away from all distractions. Headphones in if possible.", duration_seconds: 20 },
      { instruction: "Eyes closed. 10 deep breaths.", duration_seconds: 80 },
      { instruction: "Empty your mind of everything outside this moment.", duration_seconds: 60 },
      { instruction: "Visualise yourself performing your first action perfectly.", duration_seconds: 60 },
      { instruction: "Lock in. You are here. You are ready.", duration_seconds: 50 },
      { instruction: "Open eyes. Game face on. Go.", duration_seconds: 30 },
    ]
  },
  {
    title: "Dealing With Crowd and Environment",
    category: "match-day-calm",
    duration_seconds: 420,
    description: "Train your mind to stay focused despite noise, weather, or an intimidating environment.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Imagine your most challenging environment — noise, opposition, adverse conditions.", duration_seconds: 60 },
      { instruction: "Feel the discomfort. Don't resist it.", duration_seconds: 60 },
      { instruction: "Understand: you cannot control the environment. You can control your response.", duration_seconds: 60 },
      { instruction: "Create an internal bubble of calm. The chaos is outside.", duration_seconds: 90 },
      { instruction: "Perform inside the bubble. External conditions become irrelevant.", duration_seconds: 90 },
      { instruction: "Say: 'My focus is unconditional. Conditions cannot break it.'", duration_seconds: 30 },
      { instruction: "Open your eyes. The environment has no power over you.", duration_seconds: 30 },
    ]
  },
  {
    title: "Morning of the Big Day",
    category: "match-day-calm",
    duration_seconds: 540,
    description: "A complete morning ritual for the most important performance day of the season.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 75,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Rise quietly. This day is important. Honour it with presence.", duration_seconds: 40 },
      { instruction: "Five deep breaths. Fill every corner of your lungs.", duration_seconds: 60 },
      { instruction: "Recall all the training and preparation that brought you here.", duration_seconds: 90 },
      { instruction: "You have earned your place on this day.", duration_seconds: 60 },
      { instruction: "Visualise yourself performing with mastery and ease.", duration_seconds: 90 },
      { instruction: "Eat well. Move slowly. Protect your mental space.", duration_seconds: 60 },
      { instruction: "Say: 'I am ready. I have prepared. Today I execute.'", duration_seconds: 40 },
      { instruction: "Trust everything you've done. The preparation is complete.", duration_seconds: 40 },
      { instruction: "Go be great.", duration_seconds: 30 },
    ]
  },
  {
    title: "The Process Over the Result",
    category: "match-day-calm",
    duration_seconds: 420,
    description: "Refocus away from outcome anxiety and into process-driven performance.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Name the result you desperately want today.", duration_seconds: 40 },
      { instruction: "Now — deliberately let go of needing it. Results are never fully in your control.", duration_seconds: 60 },
      { instruction: "What IS in your control? Your effort, focus, decisions, preparation.", duration_seconds: 60 },
      { instruction: "Focus only on doing the process brilliantly — one action at a time.", duration_seconds: 90 },
      { instruction: "Results are the by-product of a great process, executed consistently.", duration_seconds: 60 },
      { instruction: "Say: 'I control the process. The result takes care of itself.'", duration_seconds: 40 },
      { instruction: "Open your eyes. Execute the next action. Just that.", duration_seconds: 40 },
      { instruction: "The process is the performance.", duration_seconds: 30 },
    ]
  },
  {
    title: "Post-Performance Review",
    category: "match-day-calm",
    duration_seconds: 480,
    description: "A structured mental debrief to extract learning from any performance.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Find a quiet moment after your performance. Give yourself 30 minutes.", duration_seconds: 30 },
      { instruction: "Ask: What went well? Be specific and generous.", duration_seconds: 90 },
      { instruction: "Ask: What would I do differently next time? Be honest, not harsh.", duration_seconds: 90 },
      { instruction: "Ask: What is one key lesson from today?", duration_seconds: 60 },
      { instruction: "Write these down if possible. The act of writing deepens learning.", duration_seconds: 60 },
      { instruction: "Close the performance in your mind. Release it.", duration_seconds: 60 },
      { instruction: "Say: 'I reviewed. I learned. I'm better now than before.'", duration_seconds: 40 },
      { instruction: "Rest. The next preparation begins tomorrow.", duration_seconds: 30 },
    ]
  },
  {
    title: "Composed Under Fire",
    category: "match-day-calm",
    duration_seconds: 480,
    description: "Train yourself to slow down and make clear decisions in the middle of chaos.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 80,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Recall a high-pressure in-performance moment. Where things went fast and messy.", duration_seconds: 60 },
      { instruction: "In your mind, slow time right down in that moment.", duration_seconds: 90 },
      { instruction: "See yourself breathing. Looking. Choosing deliberately.", duration_seconds: 90 },
      { instruction: "The world around you is fast. Inside you is slow, clear, decisive.", duration_seconds: 90 },
      { instruction: "This is composure: the ability to operate in slow-motion clarity amid fast chaos.", duration_seconds: 60 },
      { instruction: "Practise this 3 times with different scenarios.", duration_seconds: 60 },
      { instruction: "Open your eyes. Composure is trainable. You're training it now.", duration_seconds: 30 },
    ]
  },

  // ===== PRO MENTAL (Advanced/Premium) (61-70) =====
  {
    title: "Flow State Architecture",
    category: "pro-mental",
    duration_seconds: 900,
    description: "A comprehensive pro-level session to architect and enter flow states consistently.",
    difficulty: "advanced",
    is_premium: true,
    xp_value: 120,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Establish your optimal environment. Light, sound, temperature — everything controlled.", duration_seconds: 60 },
      { instruction: "Define a clear, challenging but achievable goal for this session.", duration_seconds: 60 },
      { instruction: "Warm up your mind: 10 deep breaths, body scan, one minute of silence.", duration_seconds: 120 },
      { instruction: "Set your mental cue: a phrase, song, or movement that signals deep focus.", duration_seconds: 60 },
      { instruction: "Begin. Fully immersed. No interruptions. No clock-watching.", duration_seconds: 300 },
      { instruction: "If pulled out of flow — reset cue. Return without judgment.", duration_seconds: 60 },
      { instruction: "End with a deliberate shutdown ritual: note wins, close session.", duration_seconds: 120 },
      { instruction: "Flow is a design, not an accident. Repeat this until it becomes automatic.", duration_seconds: 60 },
      { instruction: "You are building the architecture of elite performance.", duration_seconds: 60 },
    ]
  },
  {
    title: "Identity Leverage",
    category: "pro-mental",
    duration_seconds: 720,
    description: "Use identity-based belief shifts to change behaviour from the inside out.",
    difficulty: "advanced",
    is_premium: true,
    xp_value: 110,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Ask: What beliefs do I hold about myself that limit my potential?", duration_seconds: 90 },
      { instruction: "For each belief, trace where it came from. Is it true? Was it always true?", duration_seconds: 90 },
      { instruction: "Replace each limiting belief with an identity statement: 'I am someone who...'", duration_seconds: 90 },
      { instruction: "Understand: you don't change behaviour first. You change identity first.", duration_seconds: 90 },
      { instruction: "List 3 actions that your new identity would naturally take today.", duration_seconds: 90 },
      { instruction: "Every action you take either casts a vote for your old identity or new one.", duration_seconds: 90 },
      { instruction: "Choose your vote deliberately. Repeatedly.", duration_seconds: 90 },
      { instruction: "Open your eyes. You are who you decide to be. Decide now.", duration_seconds: 30 },
      { instruction: "Live in alignment with your chosen identity from this moment.", duration_seconds: 30 },
    ]
  },
  {
    title: "Zone of Genius Activation",
    category: "pro-mental",
    duration_seconds: 720,
    description: "Identify and operate exclusively from your zone of highest unique ability.",
    difficulty: "advanced",
    is_premium: true,
    xp_value: 110,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Identify your top 3 unique strengths. What comes effortlessly to you that others struggle with?", duration_seconds: 90 },
      { instruction: "Recall the last time you operated from these strengths. How did it feel?", duration_seconds: 90 },
      { instruction: "Understand: your zone of genius is not where you're merely competent. It's where you're brilliant.", duration_seconds: 90 },
      { instruction: "Visualise operating from this zone in your next challenge.", duration_seconds: 120 },
      { instruction: "Identify what activities take you OUT of this zone. Plan to minimise them.", duration_seconds: 90 },
      { instruction: "Say: 'I do what only I can do at my highest level.'", duration_seconds: 60 },
      { instruction: "Your genius serves others. Use it without apology.", duration_seconds: 60 },
      { instruction: "Open your eyes. Stay in your genius today.", duration_seconds: 30 },
    ]
  },
  {
    title: "Deliberate Practice Mindset",
    category: "pro-mental",
    duration_seconds: 600,
    description: "Develop the mental framework that separates elite from average practice.",
    difficulty: "advanced",
    is_premium: true,
    xp_value: 100,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Understand: volume of practice alone does not create expertise. Quality does.", duration_seconds: 60 },
      { instruction: "Define the weakest part of your current skill. Be brutally honest.", duration_seconds: 60 },
      { instruction: "Design a practice session aimed directly at that weakness.", duration_seconds: 90 },
      { instruction: "Commit to practising this specific weakness with full attention.", duration_seconds: 60 },
      { instruction: "Build in immediate feedback: what went well, what to adjust.", duration_seconds: 90 },
      { instruction: "Understand: discomfort during practice signals growth. Embrace it.", duration_seconds: 90 },
      { instruction: "Say: 'I practise what I'm worst at. That's why I'm the best.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Plan your next deliberate session.", duration_seconds: 60 },
      { instruction: "Greatness is built at the edges of your comfort zone.", duration_seconds: 30 },
    ]
  },
  {
    title: "Elite Competitor Analysis",
    category: "pro-mental",
    duration_seconds: 720,
    description: "Decode the mental and physical patterns of elite performers to extract applicable lessons.",
    difficulty: "advanced",
    is_premium: true,
    xp_value: 110,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Choose one elite performer in your field. Someone at the very top.", duration_seconds: 60 },
      { instruction: "Analyse: How do they prepare mentally and physically?", duration_seconds: 90 },
      { instruction: "Analyse: How do they respond to failure and adversity?", duration_seconds: 90 },
      { instruction: "Analyse: What routines, habits, and beliefs enable their performance?", duration_seconds: 90 },
      { instruction: "Extract 3 principles you can immediately apply to your own development.", duration_seconds: 90 },
      { instruction: "This is modelling — not copying their style, but learning their principles.", duration_seconds: 90 },
      { instruction: "Say: 'I learn from the best. I apply immediately. I evolve constantly.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Begin implementing today.", duration_seconds: 60 },
      { instruction: "Every elite performer studied those before them.", duration_seconds: 30 },
    ]
  },
  {
    title: "Mastery Over Perfection",
    category: "pro-mental",
    duration_seconds: 600,
    description: "Break free from perfectionism and embrace the path of continuous mastery.",
    difficulty: "advanced",
    is_premium: true,
    xp_value: 100,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Honestly examine: where does perfectionism hold you back?", duration_seconds: 90 },
      { instruction: "Understand: perfectionism is the enemy of progress. Nothing is ever shipped perfectly.", duration_seconds: 90 },
      { instruction: "Mastery means: relentless improvement in an imperfect, ongoing process.", duration_seconds: 90 },
      { instruction: "Identify one thing you've been delaying because it's 'not good enough yet'.", duration_seconds: 60 },
      { instruction: "Commit to releasing it, submitting it, doing it — imperfect but complete.", duration_seconds: 60 },
      { instruction: "Say: 'Done is better than perfect. Progress is better than paralysis.'", duration_seconds: 60 },
      { instruction: "Breathe. Release. Act.", duration_seconds: 60 },
      { instruction: "Mastery is built by imperfect reps done consistently.", duration_seconds: 30 },
      { instruction: "Start. Adjust. Repeat. That is the path.", duration_seconds: 30 },
    ]
  },
  {
    title: "Inner Dialogue Mastery",
    category: "pro-mental",
    duration_seconds: 720,
    description: "Gain complete command over the voice inside your head during performance.",
    difficulty: "advanced",
    is_premium: true,
    xp_value: 110,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Listen to your inner voice right now. What is it saying?", duration_seconds: 60 },
      { instruction: "Classify each thought: Helpful, Neutral, or Harmful.", duration_seconds: 90 },
      { instruction: "For harmful thoughts — dispute them with evidence. Are they actually true?", duration_seconds: 90 },
      { instruction: "Develop a performance-specific internal script. Words that sharpen you.", duration_seconds: 90 },
      { instruction: "During a visualised performance, run your internal script in parallel.", duration_seconds: 120 },
      { instruction: "Your self-talk IS your coaching. You have it available 24/7. Use it well.", duration_seconds: 90 },
      { instruction: "Say: 'I am my own best coach. I speak to myself with power and accuracy.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Catch the next negative thought. Rewrite it.", duration_seconds: 30 },
      { instruction: "Train your inner dialogue like you train your body — daily, with intention.", duration_seconds: 30 },
    ]
  },
  {
    title: "Performance Rituals Design",
    category: "pro-mental",
    duration_seconds: 660,
    description: "Design your personal pre-performance ritual for maximum consistency and control.",
    difficulty: "advanced",
    is_premium: true,
    xp_value: 105,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Understand why rituals matter: they create consistency in an inconsistent environment.", duration_seconds: 60 },
      { instruction: "Map your current pre-performance habits. Are they intentional or random?", duration_seconds: 90 },
      { instruction: "Design a 15-minute ritual: physical, mental, and focus components.", duration_seconds: 120 },
      { instruction: "Physical: movement, posture, breathing.", duration_seconds: 60 },
      { instruction: "Mental: visualisation, affirmation, intention-setting.", duration_seconds: 60 },
      { instruction: "Focus: anchor cue, distraction cutoff, lock-in phrase.", duration_seconds: 60 },
      { instruction: "Commit to the same ritual before every performance for 30 days.", duration_seconds: 90 },
      { instruction: "Rituals signal to your brain: it's time. They automate excellence.", duration_seconds: 60 },
      { instruction: "Open your eyes. Write your ritual down. Begin tomorrow.", duration_seconds: 60 },
    ]
  },
  {
    title: "Elite Endurance Mindset",
    category: "pro-mental",
    duration_seconds: 720,
    description: "Develop the mental framework to maintain elite performance over long competition seasons.",
    difficulty: "advanced",
    is_premium: true,
    xp_value: 110,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Understand: elite performance across a season requires recovery as much as output.", duration_seconds: 60 },
      { instruction: "Map your current energy management: how do you protect performance over time?", duration_seconds: 90 },
      { instruction: "Identify your current energy leaks: what is draining you unnecessarily?", duration_seconds: 90 },
      { instruction: "Design 3 recovery practices you will protect every single week.", duration_seconds: 90 },
      { instruction: "Reframe rest as part of performance — not a break from it.", duration_seconds: 90 },
      { instruction: "Understand that sustainable consistency beats occasional brilliance.", duration_seconds: 90 },
      { instruction: "Say: 'I am built for the long game. I protect my excellence.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Start your recovery plan today.", duration_seconds: 60 },
      { instruction: "Champions manage their energy season after season.", duration_seconds: 30 },
    ]
  },
  {
    title: "Psychological Safety and Risk-Taking",
    category: "pro-mental",
    duration_seconds: 660,
    description: "Develop the mental safety to take bold risks and play freely without fear.",
    difficulty: "advanced",
    is_premium: true,
    xp_value: 105,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Ask: Where are you playing it safe when you should be bold?", duration_seconds: 90 },
      { instruction: "Understand: fear of failure creates conservative, predictable performance.", duration_seconds: 90 },
      { instruction: "The greatest performers give themselves permission to fail and still stay open.", duration_seconds: 90 },
      { instruction: "Visualise taking your boldest action and it not working — and being okay with it.", duration_seconds: 90 },
      { instruction: "Visualise the same bold action succeeding. Feel the upside.", duration_seconds: 90 },
      { instruction: "The expected value of bold performance exceeds conservative performance.", duration_seconds: 60 },
      { instruction: "Say: 'I give myself permission to be brave. Fully. Without apology.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Take the bold move. Today.", duration_seconds: 60 },
      { instruction: "Safety never created greatness.", duration_seconds: 30 },
    ]
  },

  // ===== ADDITIONAL UNIVERSAL PART 1 (71-90) =====
  {
    title: "Morning Mindset Ritual",
    category: "focus",
    duration_seconds: 480,
    description: "Set the tone for a powerful, intentional day in just 8 minutes each morning.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Wake and immediately resist the urge to check your phone.", duration_seconds: 30 },
      { instruction: "Sit up. Take 5 deep breaths. Let your mind wake gently.", duration_seconds: 60 },
      { instruction: "State what you are grateful for. One thing. Really feel it.", duration_seconds: 60 },
      { instruction: "Set your intention: who will you be today? Calm? Bold? Focused?", duration_seconds: 60 },
      { instruction: "Visualise the most important thing you will accomplish.", duration_seconds: 90 },
      { instruction: "Say your daily mantra. Own it.", duration_seconds: 30 },
      { instruction: "Rise. The day is already shaped by how you began it.", duration_seconds: 60 },
      { instruction: "You choose the tone. You set the standard. Go.", duration_seconds: 30 },
      { instruction: "Today is a gift. Use every minute of it.", duration_seconds: 30 },
    ]
  },
  {
    title: "Evening Review and Unwind",
    category: "recovery",
    duration_seconds: 420,
    description: "Process the day, extract lessons, and release the weight before sleep.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit in a quiet space. No screens. Just you and the day.", duration_seconds: 30 },
      { instruction: "Review 3 things that went well today.", duration_seconds: 60 },
      { instruction: "Review one thing that could have gone better — and what you'll do differently.", duration_seconds: 60 },
      { instruction: "Release what cannot be undone. The day is done.", duration_seconds: 60 },
      { instruction: "Express gratitude for the day as a whole — including the difficulties.", duration_seconds: 60 },
      { instruction: "Breathe deeply. Feel your body relax.", duration_seconds: 60 },
      { instruction: "Tomorrow begins fresh. Rest now.", duration_seconds: 50 },
      { instruction: "You did your best today. That is always enough.", duration_seconds: 30 },
    ]
  },
  {
    title: "Stress Inoculation",
    category: "pressure",
    duration_seconds: 480,
    description: "Deliberately expose yourself to controlled stress to build psychological immunity.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 80,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Deliberately hold a stressful thought or scenario in mind. Don't escape it.", duration_seconds: 60 },
      { instruction: "Notice the physical stress response: heart rate, tension, shallow breathing.", duration_seconds: 60 },
      { instruction: "Now — regulate it deliberately. Slow breath. Loosen muscles. Lower heart rate.", duration_seconds: 90 },
      { instruction: "Stay in the stressful scenario. Regulate again. Repeat.", duration_seconds: 120 },
      { instruction: "You are teaching your nervous system that stress is manageable.", duration_seconds: 60 },
      { instruction: "Each time you do this, your threshold rises.", duration_seconds: 60 },
      { instruction: "Open your eyes. You just became more stress-resistant.", duration_seconds: 30 },
    ]
  },
  {
    title: "Resilience Story",
    category: "confidence",
    duration_seconds: 480,
    description: "Rewrite your personal narrative to emphasise resilience, not victimhood.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Think of the hardest period of your life. The one that tested you most.", duration_seconds: 60 },
      { instruction: "Write or narrate it mentally — but this time, you are the resilient hero.", duration_seconds: 90 },
      { instruction: "Highlight: what did you do to survive and move forward?", duration_seconds: 90 },
      { instruction: "This is not denial of difficulty. It is recognising your strength within it.", duration_seconds: 60 },
      { instruction: "Your story is a resilience story — not a victim story. You get to decide the framing.", duration_seconds: 90 },
      { instruction: "Say: 'I have been through fire and I am still here. That makes me powerful.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Carry this narrative with pride.", duration_seconds: 30 },
    ]
  },
  {
    title: "Emotional Intelligence Check-In",
    category: "recovery",
    duration_seconds: 420,
    description: "Develop self-awareness and emotional regulation through deliberate inner reflection.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Pause and check in: what emotions are present right now?", duration_seconds: 60 },
      { instruction: "Name them precisely: not just 'bad', but frustrated, disappointed, uncertain.", duration_seconds: 60 },
      { instruction: "Ask: why is this emotion here? What triggered it?", duration_seconds: 60 },
      { instruction: "Ask: is this emotion useful right now, or is it distorting my thinking?", duration_seconds: 90 },
      { instruction: "Choose how to respond — not react — to what you're feeling.", duration_seconds: 60 },
      { instruction: "Breathe. Acknowledge. Regulate. Respond wisely.", duration_seconds: 60 },
      { instruction: "Emotional intelligence is the skill that makes all other skills work.", duration_seconds: 30 },
      { instruction: "You are in control. Always.", duration_seconds: 30 },
    ]
  },
  {
    title: "Patience and Long-Game Thinking",
    category: "pro-mental",
    duration_seconds: 480,
    description: "Develop the rare ability to stay committed to long-term goals under short-term pressure.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Think of a goal that feels slow or stalled. Frustration is natural.", duration_seconds: 60 },
      { instruction: "Zoom out to a 5-year view. How significant is today's frustration from there?", duration_seconds: 90 },
      { instruction: "Understand: elite results are built from thousands of unglamorous consistent actions.", duration_seconds: 90 },
      { instruction: "Every day you show up adds compound interest to your development.", duration_seconds: 60 },
      { instruction: "The person who stays the course longest wins. Can you outlast the doubt?", duration_seconds: 90 },
      { instruction: "Say: 'I am playing the long game. Today's effort is an investment.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Do today's thing. Trust tomorrow's result.", duration_seconds: 30 },
    ]
  },
  {
    title: "Discipline Over Motivation",
    category: "focus",
    duration_seconds: 420,
    description: "Build the mental infrastructure of discipline to perform even when motivation disappears.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Acknowledge: motivation fluctuates. Discipline doesn't. Which do you rely on?", duration_seconds: 60 },
      { instruction: "Identify your current most important commitment.", duration_seconds: 60 },
      { instruction: "Connect that commitment to your core identity — not a feeling.", duration_seconds: 90 },
      { instruction: "Say: 'I do this not because I feel like it, but because I committed to it.'", duration_seconds: 60 },
      { instruction: "Visualise showing up on your worst day and still doing the work.", duration_seconds: 90 },
      { instruction: "That version of you is the most powerful.", duration_seconds: 30 },
      { instruction: "Breathe. Choose discipline. Every time.", duration_seconds: 30 },
      { instruction: "The secret of the elite: they do it on the bad days too.", duration_seconds: 30 },
    ]
  },
  {
    title: "The Present Moment Is Enough",
    category: "match-day-calm",
    duration_seconds: 360,
    description: "A mindfulness session to fully inhabit the present moment and release past and future anxiety.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 55,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Stop everything. Sit. Breathe.", duration_seconds: 30 },
      { instruction: "Feel the ground beneath you. Feel your weight. You are here.", duration_seconds: 60 },
      { instruction: "The past is memory. The future is imagination. Only now is real.", duration_seconds: 60 },
      { instruction: "What can you sense right now? Sounds, sensations, smells.", duration_seconds: 60 },
      { instruction: "Breathe into this moment. Nothing is missing right now.", duration_seconds: 90 },
      { instruction: "Say: 'Right here. Right now. This is where I live.'", duration_seconds: 30 },
      { instruction: "Open your eyes. Stay here. This moment is enough.", duration_seconds: 30 },
    ]
  },
  {
    title: "The Decision Maker",
    category: "focus",
    duration_seconds: 480,
    description: "Build mental clarity and decisiveness for better decision-making under any condition.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Identify a decision you've been avoiding or delaying.", duration_seconds: 60 },
      { instruction: "Gather the real information: what do you know? What don't you know?", duration_seconds: 60 },
      { instruction: "Reduce the options to a maximum of 2. More than that creates paralysis.", duration_seconds: 60 },
      { instruction: "Ask: which choice aligns best with my values and long-term goals?", duration_seconds: 90 },
      { instruction: "Make the decision. Own it. Commit fully.", duration_seconds: 60 },
      { instruction: "Understand: a good decision executed fully beats a perfect one executed hesitantly.", duration_seconds: 60 },
      { instruction: "Breathe. Decide. Act.", duration_seconds: 60 },
      { instruction: "Decisiveness is a muscle. Use it or lose it.", duration_seconds: 30 },
    ]
  },
  {
    title: "Relationship with Effort",
    category: "confidence",
    duration_seconds: 420,
    description: "Build a healthy, sustainable relationship with hard work that energises rather than depletes.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Reflect: do you see effort as a burden or as a privilege?", duration_seconds: 60 },
      { instruction: "Consider: the ability to work hard is itself a gift. Not everyone has it.", duration_seconds: 60 },
      { instruction: "Connect your effort today to something meaningful — your purpose or growth.", duration_seconds: 90 },
      { instruction: "Feel the satisfaction that comes from genuine effort — not results.", duration_seconds: 90 },
      { instruction: "The effort IS the point. The result is just a score.", duration_seconds: 60 },
      { instruction: "Say: 'I love the work. I love the process. I love who I become through effort.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Go and work with full heart.", duration_seconds: 30 },
      { instruction: "Effort is its own reward. Remember this.", duration_seconds: 30 },
    ]
  },
];

export const ALL_MENTAL_ROUTINES = [...BASE_MENTAL_ROUTINES, ...EXTRA_MENTAL_ROUTINES];

export default ALL_MENTAL_ROUTINES;