// 52 Brand-New Mental Training Routines (includes restored 4-7-8 & Box Breathing standalone sessions)
// Zero repetition with previous files. All 11 focus areas covered.
export const EXTRA_MENTAL_ROUTINES_3 = [

  // ===== FOCUS =====
  {
    title: "The Breath as Anchor",
    category: "focus",
    duration_seconds: 480,
    description: "Train your attention to return to your breath as the ultimate anchor whenever the mind wanders.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit upright with your spine tall. Close your eyes gently.", duration_seconds: 20 },
      { instruction: "Bring all attention to the physical sensation of breathing — air entering the nostrils.", duration_seconds: 60 },
      { instruction: "When a thought pulls your attention away, simply notice: 'thinking.' Return to breath.", duration_seconds: 90 },
      { instruction: "You are not trying to stop thoughts. You are choosing where attention lives.", duration_seconds: 90 },
      { instruction: "Every return is a win. Ten returns means ten reps of focus.", duration_seconds: 90 },
      { instruction: "Slow your exhale slightly longer than your inhale. This deepens calm.", duration_seconds: 90 },
      { instruction: "Say: 'My breath is always here. So is my focus.'", duration_seconds: 30 },
      { instruction: "Open your eyes. Your attention muscle is stronger than it was 8 minutes ago.", duration_seconds: 18 },
    ]
  },
  {
    title: "Two-Minute Intention Sprint",
    category: "focus",
    duration_seconds: 120,
    description: "Set a razor-sharp intention before any task in just two powerful minutes.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 30,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Stop completely. Put everything down for 2 minutes.", duration_seconds: 10 },
      { instruction: "Ask: What is the single most valuable outcome of the next session?", duration_seconds: 30 },
      { instruction: "State your intention in one sentence. Concrete. Specific. Achievable.", duration_seconds: 30 },
      { instruction: "Take 3 deep breaths, each one committing you more deeply to that intention.", duration_seconds: 30 },
      { instruction: "Open your eyes. Begin only that one thing.", duration_seconds: 20 },
    ]
  },
  {
    title: "Sensory Narrowing",
    category: "focus",
    duration_seconds: 360,
    description: "Learn to deliberately narrow your sensory field to create tunnel-vision focus on what matters.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Open your eyes wide. Take in your entire surroundings — all sounds, all sights.", duration_seconds: 30 },
      { instruction: "Now slowly narrow your gaze to a single object directly in front of you.", duration_seconds: 40 },
      { instruction: "Let peripheral vision blur. Sounds fade to background. Only this point exists.", duration_seconds: 60 },
      { instruction: "Breathe slowly. Hold this narrow focus without blinking for 30 seconds.", duration_seconds: 60 },
      { instruction: "Expand awareness fully. Take it all back in. Then narrow again. Repeat 3 times.", duration_seconds: 90 },
      { instruction: "This on/off toggle is your focus switch. You now control it.", duration_seconds: 50 },
      { instruction: "Say: 'I can narrow my world to the one thing that matters. On command.'", duration_seconds: 30 },
    ]
  },
  {
    title: "The Worry Drawer",
    category: "focus",
    duration_seconds: 300,
    description: "Contain distracting worries in a mental drawer so you can focus now and address them later.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 50,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "List every worry currently competing for your attention. Name them clearly.", duration_seconds: 70 },
      { instruction: "Visualise a heavy wooden drawer. Place each worry inside it gently.", duration_seconds: 60 },
      { instruction: "Close the drawer firmly. It is locked. Those worries are safe — they haven't disappeared.", duration_seconds: 40 },
      { instruction: "You will open that drawer at a scheduled time to address them. Not now.", duration_seconds: 40 },
      { instruction: "Notice the mental space that just opened. That space is yours for the next hour.", duration_seconds: 50 },
      { instruction: "Say: 'My worries are stored safely. Right now, I am completely free to focus.'", duration_seconds: 40 },
    ]
  },

  // ===== CONFIDENCE =====
  {
    title: "The Trusted Teammate Lens",
    category: "confidence",
    duration_seconds: 360,
    description: "See yourself through the honest, appreciative eyes of someone who trusts and believes in you.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 55,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Think of one person who genuinely believes in your potential. See their face.", duration_seconds: 50 },
      { instruction: "Now see yourself through their eyes. What do they notice about you?", duration_seconds: 70 },
      { instruction: "They see your effort. Your growth. Your character. Not your worst day.", duration_seconds: 70 },
      { instruction: "That accurate, supportive view of you — it exists. It is real.", duration_seconds: 60 },
      { instruction: "Now hold that same view about yourself for the next 60 seconds.", duration_seconds: 60 },
      { instruction: "Say: 'I deserve to be seen at my best. I choose to see myself that way.'", duration_seconds: 50 },
    ]
  },
  {
    title: "Worst-Case Freedom",
    category: "confidence",
    duration_seconds: 420,
    description: "Eliminate the paralysing grip of worst-case thinking by fully walking through it — and surviving.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Name the thing you are most afraid of happening. Say it completely.", duration_seconds: 60 },
      { instruction: "Walk through the worst case fully. Really feel it. Don't flinch.", duration_seconds: 80 },
      { instruction: "Ask: would I still be alive? Would I recover? Almost certainly yes.", duration_seconds: 60 },
      { instruction: "Now ask: what is the realistic, probable case? Not the worst one.", duration_seconds: 70 },
      { instruction: "And the best case? If things go well, what does that look like?", duration_seconds: 60 },
      { instruction: "You have now mapped the full range. The worst is survivable. The best is possible.", duration_seconds: 50 },
      { instruction: "Say: 'I am free to try. I have already survived the worst in my mind.'", duration_seconds: 40 },
    ]
  },
  {
    title: "Confidence Through Preparation",
    category: "confidence",
    duration_seconds: 420,
    description: "Build rock-solid confidence by deliberately reviewing all the preparation you have already done.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit quietly. Begin to mentally list everything you have prepared for this challenge.", duration_seconds: 80 },
      { instruction: "Every training session, every rep, every lesson, every hard day you showed up.", duration_seconds: 80 },
      { instruction: "The preparation is done. It is inside you. You cannot lose it now.", duration_seconds: 70 },
      { instruction: "Confidence built on preparation is real confidence — not arrogance.", duration_seconds: 60 },
      { instruction: "Say: 'I have done the work. My preparation is my permission to perform.'", duration_seconds: 50 },
      { instruction: "Open your eyes. You have already earned what you are about to do.", duration_seconds: 40 },
      { instruction: "Trust the thousands of hours behind you now.", duration_seconds: 40 },
    ]
  },
  {
    title: "The Name Your Strength Challenge",
    category: "confidence",
    duration_seconds: 300,
    description: "Practice speaking your genuine strengths out loud to build the habit of honest self-recognition.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 50,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "This exercise requires honesty and courage. No false modesty allowed.", duration_seconds: 20 },
      { instruction: "Name one technical strength you genuinely possess. Say it clearly.", duration_seconds: 40 },
      { instruction: "Name one mental or character strength. Something you have earned.", duration_seconds: 40 },
      { instruction: "Name one thing about your approach that makes you different or better.", duration_seconds: 40 },
      { instruction: "These are not opinions. They are facts. Repeat all three with conviction.", duration_seconds: 70 },
      { instruction: "Say: 'These are my strengths. I bring them to every performance.'", duration_seconds: 50 },
      { instruction: "Practice this daily. Confidence grows in the speaking of truth.", duration_seconds: 40 },
    ]
  },

  // ===== HANDLING PRESSURE =====
  {
    title: "Pressure Rehearsal: The Crucial Over",
    category: "pressure",
    duration_seconds: 480,
    description: "Simulate the most pressure-filled cricket moment imaginable and navigate it with composure.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 80,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. Final over. 12 needed. You are bowling or batting — choose your role.", duration_seconds: 60 },
      { instruction: "The entire team is watching. Every ball matters. Feel the full weight of it.", duration_seconds: 60 },
      { instruction: "Notice your body: rapid heartbeat, dry mouth, tight chest. This is normal. Work with it.", duration_seconds: 60 },
      { instruction: "Ball 1. Breathe. Choose your action. Execute. See it go perfectly.", duration_seconds: 70 },
      { instruction: "Ball 2. Stay present. Not the result — just this ball.", duration_seconds: 70 },
      { instruction: "See yourself through all 6 balls. Composed. Decisive. Skilled.", duration_seconds: 80 },
      { instruction: "Say: 'I have been in this moment. I know how to handle it.'", duration_seconds: 50 },
      { instruction: "Open your eyes. The simulation is done. The real thing will feel familiar.", duration_seconds: 30 },
    ]
  },
  {
    title: "The Pressure Release Valve",
    category: "pressure",
    duration_seconds: 360,
    description: "A physical and mental technique to instantly lower accumulated pressure before it derails you.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 55,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Stand up. Walk 5 deliberate steps. Feel the ground. Physical movement breaks the spiral.", duration_seconds: 30 },
      { instruction: "Take one massive breath in. Hold for 4 counts. Release it all at once loudly.", duration_seconds: 40 },
      { instruction: "Roll your shoulders back slowly 5 times. Unload the weight.", duration_seconds: 40 },
      { instruction: "Ask: 'What is the single next right action?' Not the whole solution — just next.", duration_seconds: 60 },
      { instruction: "Name it. Commit to it. Only it.", duration_seconds: 50 },
      { instruction: "Take 3 slow breaths. The pressure is not gone — but it is no longer in charge.", duration_seconds: 70 },
      { instruction: "Say: 'One thing at a time. I can do one thing at a time.'", duration_seconds: 30 },
    ]
  },
  {
    title: "Performing for the Love of It",
    category: "pressure",
    duration_seconds: 420,
    description: "Strip away all external pressure by reconnecting purely with the joy of the game itself.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Remember when cricket was just fun. Before the results mattered. How did it feel?", duration_seconds: 70 },
      { instruction: "Recall playing with friends, or a moment of pure joy in the game.", duration_seconds: 70 },
      { instruction: "That pure state is still available. The pressure is added by humans — not the game.", duration_seconds: 70 },
      { instruction: "Ask: if no one was watching and nothing was at stake, how would I play right now?", duration_seconds: 70 },
      { instruction: "Play like that. The results often follow when the pressure drops.", duration_seconds: 70 },
      { instruction: "Say: 'I play because I love this game. That love is bigger than any pressure.'", duration_seconds: 70 },
    ]
  },
  {
    title: "Breathing Through a Batting Collapse",
    category: "pressure",
    duration_seconds: 360,
    description: "Stay mentally composed and contribute when your team's batting is collapsing around you.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Your team has lost quick wickets. The situation is dire. Notice your emotional state.", duration_seconds: 50 },
      { instruction: "Breathe in for 4 slow counts. This calms the fight-or-flight response immediately.", duration_seconds: 40 },
      { instruction: "Out for 6. Repeat 3 times. Your body is now listening to you.", duration_seconds: 70 },
      { instruction: "Remind yourself: collapses are reversed by one person choosing to stay in.", duration_seconds: 60 },
      { instruction: "You are that person. Defence first. Run-rate later. Survival is the job.", duration_seconds: 60 },
      { instruction: "Say: 'I am the anchor. I stay. I fight. One ball at a time.'", duration_seconds: 50 },
      { instruction: "Picture yourself still at the crease 10 overs later. Begin that innings now.", duration_seconds: 30 },
    ]
  },

  // ===== IMPROVING FOCUS =====
  {
    title: "Task Isolation Protocol",
    category: "focus",
    duration_seconds: 300,
    description: "Eliminate multi-tasking by training your brain to isolate and fully complete one task at a time.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 50,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Write down everything currently on your mind. Every task, worry, and to-do.", duration_seconds: 60 },
      { instruction: "Look at the list. Choose the single most important item.", duration_seconds: 30 },
      { instruction: "Cross off everything else — not forever, just for the next 25 minutes.", duration_seconds: 30 },
      { instruction: "Take 5 deep breaths. You have permission to do only one thing.", duration_seconds: 60 },
      { instruction: "Begin. If another task intrudes mentally — write it down, then return.", duration_seconds: 70 },
      { instruction: "Singular focus is a competitive advantage almost no one actually uses.", duration_seconds: 30 },
      { instruction: "Say: 'One task. Full attention. That is how mastery is built.'", duration_seconds: 20 },
    ]
  },
  {
    title: "Environmental Intention Setting",
    category: "focus",
    duration_seconds: 360,
    description: "Design your mental and physical environment to make deep focus the default, not the exception.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 55,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Look around your current space. What is making focus harder than it needs to be?", duration_seconds: 60 },
      { instruction: "Remove or minimise the top 2 distractions. This is a physical act of intention.", duration_seconds: 60 },
      { instruction: "Place something in your space that represents your current goal. A visual anchor.", duration_seconds: 60 },
      { instruction: "Take 5 deep breaths. Notice how even small environmental changes shift your state.", duration_seconds: 70 },
      { instruction: "You do not need willpower when your environment already supports focus.", duration_seconds: 60 },
      { instruction: "Say: 'My environment and my mind both point in one direction.'", duration_seconds: 50 },
    ]
  },

  // ===== MENTAL RECOVERY =====
  {
    title: "The Decompression Zone",
    category: "recovery",
    duration_seconds: 480,
    description: "A deliberate transition ritual between performance and rest to prevent mental burnout.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Training is done. You now officially enter recovery mode. This transition is deliberate.", duration_seconds: 40 },
      { instruction: "Take 5 slow breaths. With each exhale, release the intensity of the session.", duration_seconds: 70 },
      { instruction: "Mentally acknowledge 3 things you did well in the session, however small.", duration_seconds: 80 },
      { instruction: "Name one thing to work on next time. Just one. File it. Done.", duration_seconds: 60 },
      { instruction: "Do something entirely unrelated to cricket for the next 30 minutes. Full permission.", duration_seconds: 60 },
      { instruction: "Recovery is not passive — it is an active investment in tomorrow's performance.", duration_seconds: 70 },
      { instruction: "Say: 'This session is complete. I honour it with genuine rest.'", duration_seconds: 60 },
      { instruction: "Step away. You've earned it.", duration_seconds: 40 },
    ]
  },
  {
    title: "Repair After a Row",
    category: "recovery",
    duration_seconds: 420,
    description: "Process interpersonal conflict or tension and restore your mental equilibrium and perspective.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Take 3 deep, slow breaths. Conflict triggers the nervous system. First: regulate.", duration_seconds: 40 },
      { instruction: "Name exactly what you felt — not what they did. Your feelings are information.", duration_seconds: 70 },
      { instruction: "Ask: what did I contribute to this situation? Be honest, not harsh.", duration_seconds: 70 },
      { instruction: "Ask: what do I actually want from this situation going forward?", duration_seconds: 70 },
      { instruction: "Conflict rarely improves performance. Resolution does. What is the first repair step?", duration_seconds: 80 },
      { instruction: "Say: 'I understand what happened. I choose repair over resentment.'", duration_seconds: 50 },
      { instruction: "Breathe. The tension has been processed. Move forward.", duration_seconds: 40 },
    ]
  },
  {
    title: "Recharge Your Internal Battery",
    category: "recovery",
    duration_seconds: 600,
    description: "A complete mental recharge using silence, breath and guided imagination after heavy output.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 75,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Lie down or sit completely still. This is a full battery recharge.", duration_seconds: 30 },
      { instruction: "Breathe in for 4, hold for 4, out for 6. Repeat 5 times.", duration_seconds: 90 },
      { instruction: "Imagine a warm golden light entering your body with each inhale.", duration_seconds: 90 },
      { instruction: "With each exhale, see grey fatigue leaving your body completely.", duration_seconds: 90 },
      { instruction: "Your body is being refilled with fresh, clean energy. Feel the warmth spreading.", duration_seconds: 90 },
      { instruction: "Stay in silence for 2 full minutes. No input. Just restoration.", duration_seconds: 120 },
      { instruction: "Say: 'I am recharged. My mind and body are ready for what comes next.'", duration_seconds: 60 },
      { instruction: "Open your eyes slowly. Move with renewed energy.", duration_seconds: 30 },
    ]
  },
  {
    title: "Compassionate Coaching Voice",
    category: "recovery",
    duration_seconds: 360,
    description: "Replace harsh self-judgment after a poor performance with constructive, compassionate self-coaching.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 55,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Think of your harshest self-criticism from a recent performance. Hear it clearly.", duration_seconds: 50 },
      { instruction: "Now imagine the best coach you have ever had saying this to you. They wouldn't. Why not?", duration_seconds: 70 },
      { instruction: "A great coach is honest AND kind. They point to the improvement, not the failure.", duration_seconds: 60 },
      { instruction: "Restate your self-criticism as a great coach would — specific, actionable, supportive.", duration_seconds: 80 },
      { instruction: "You deserve the same quality of coaching internally that you would accept externally.", duration_seconds: 60 },
      { instruction: "Say: 'I coach myself like a champion deserves to be coached. Always.'", duration_seconds: 40 },
    ]
  },

  // ===== VISUALIZATION PRACTICE =====
  {
    title: "Fielding Brilliance Rehearsal",
    category: "visualization",
    duration_seconds: 420,
    description: "Mentally rehearse making brilliant, match-winning fielding interventions to build automatic excellence.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. You are in the field. The batsman has just middled one toward you.", duration_seconds: 50 },
      { instruction: "See your footwork — quick, clean, committed. No hesitation.", duration_seconds: 60 },
      { instruction: "Feel your hands reading the ball. Soft hands receiving. Clean pick up.", duration_seconds: 70 },
      { instruction: "See the throw: flat, direct, on target. The run out is on. The throw goes in perfectly.", duration_seconds: 80 },
      { instruction: "Replay 3 different fielding moments — diving stop, relay, direct hit.", duration_seconds: 90 },
      { instruction: "Say: 'My fielding is a weapon. I bring energy and pressure every ball.'", duration_seconds: 50 },
      { instruction: "Open your eyes. Your body now has a blueprint for brilliance in the field.", duration_seconds: 20 },
    ]
  },
  {
    title: "The Comeback Innings",
    category: "visualization",
    duration_seconds: 540,
    description: "Mentally rehearse playing a defining innings after a run of low scores to rebuild batting confidence.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 75,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. You are walking to the crease after a difficult run of form.", duration_seconds: 50 },
      { instruction: "Your body is calm. Your mind is clear. This is a fresh start and you know it.", duration_seconds: 60 },
      { instruction: "First ball — watch it onto the bat. Leave the wide one. Respect the good one.", duration_seconds: 80 },
      { instruction: "Runs come slowly at first. That is fine. You are building. Brick by brick.", duration_seconds: 80 },
      { instruction: "You reach 20. Then 30. The hard work is paying off. Time in the middle.", duration_seconds: 80 },
      { instruction: "Feel the confidence growing with each run. You belong here. You always did.", duration_seconds: 80 },
      { instruction: "Say: 'I know how to build an innings. My technique is sound. Form returns.'", duration_seconds: 60 },
      { instruction: "Open your eyes. You have seen yourself succeed. The body remembers.", duration_seconds: 50 },
    ]
  },
  {
    title: "Catching Under Pressure",
    category: "visualization",
    duration_seconds: 360,
    description: "Eliminate catching anxiety by vividly rehearsing clean, confident catches in any conditions.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. A skied catch is coming straight to you. See it clearly.", duration_seconds: 50 },
      { instruction: "Call for it clearly. Move under it early. Balanced. Eyes never leaving the ball.", duration_seconds: 60 },
      { instruction: "Hands together. Soft cushion. The ball settles. Clean catch.", duration_seconds: 60 },
      { instruction: "Replay this 5 times in different conditions: bright sun, evening light, cold hands.", duration_seconds: 120 },
      { instruction: "You have now caught that ball hundreds of times in your mind.", duration_seconds: 40 },
      { instruction: "Say: 'I catch every ball I go for. My hands are reliable.'", duration_seconds: 30 },
    ]
  },
  {
    title: "Running Between the Wickets",
    category: "visualization",
    duration_seconds: 300,
    description: "Mentally rehearse sharp, decisive running between the wickets to eliminate run-out anxiety.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 50,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. You and your partner are at the crease. See the field placement clearly.", duration_seconds: 40 },
      { instruction: "Ball is hit to a gap. Instant assessment. 'Yes!' — and you're off immediately.", duration_seconds: 50 },
      { instruction: "Head down. Arms pumping. Bat grounded at completion. Safe. Easy run converted.", duration_seconds: 60 },
      { instruction: "Replay 3 different scenarios: tight single, quick two, a decisive call-and-go.", duration_seconds: 90 },
      { instruction: "Say: 'My running is sharp, decisive and pressure-free. I trust my calls.'", duration_seconds: 60 },
    ]
  },

  // ===== DEEP CONCENTRATION =====
  {
    title: "The 20-Minute Deep Dive",
    category: "focus",
    duration_seconds: 1200,
    description: "A guided 20-minute uninterrupted concentration session for developing elite sustained focus.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 100,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Set a clear singular task. Remove all other inputs. Commit to 20 minutes of purity.", duration_seconds: 60 },
      { instruction: "Take 10 deep breaths to fully transition into active mental mode.", duration_seconds: 90 },
      { instruction: "Begin the task. When distracted, return immediately without frustration. Return is the skill.", duration_seconds: 300 },
      { instruction: "Halfway check: are you still on the original task? Gently redirect if not.", duration_seconds: 30 },
      { instruction: "Continue. Deeper now. You are building concentration like a muscle.", duration_seconds: 420 },
      { instruction: "Final 2 minutes: notice how much longer you can sustain now than when you started.", duration_seconds: 120 },
      { instruction: "Complete. This is a genuine cognitive workout. Well done.", duration_seconds: 120 },
      { instruction: "Say: 'I can hold focus under any conditions for any duration.'", duration_seconds: 60 },
    ]
  },
  {
    title: "Thought Labeling Practice",
    category: "focus",
    duration_seconds: 480,
    description: "Train your metacognitive muscle by naming your thoughts as they arise and returning to focus.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit still. Close your eyes. No task — simply observe your mind.", duration_seconds: 30 },
      { instruction: "When a thought arises, label it: 'planning', 'worrying', 'remembering', 'judging'.", duration_seconds: 60 },
      { instruction: "Do not engage the thought. Just label it and watch it dissolve.", duration_seconds: 90 },
      { instruction: "Return to your breath each time. The breath is the home base.", duration_seconds: 90 },
      { instruction: "You are building the observer muscle — the part of you that watches thoughts without being owned by them.", duration_seconds: 90 },
      { instruction: "This is the foundation of elite concentration. The gap between stimulus and response.", duration_seconds: 90 },
      { instruction: "Say: 'I see my thoughts. I am not my thoughts.'", duration_seconds: 40 },
      { instruction: "Open your eyes. You have just trained the most important focus skill there is.", duration_seconds: 20 },
    ]
  },

  // ===== BOOSTING MOTIVATION =====
  {
    title: "Letter to Your Future Self",
    category: "confidence",
    duration_seconds: 540,
    description: "Write a vivid mental letter to your future self describing all you have achieved — then read it backward.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 75,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. You are 2 years from now. You have done the work.", duration_seconds: 60 },
      { instruction: "Begin mentally writing to your current self: 'Dear me...'", duration_seconds: 60 },
      { instruction: "Tell yourself what you achieved: the specific milestones, the development, the person you became.", duration_seconds: 100 },
      { instruction: "Tell yourself what you are grateful you committed to doing now.", duration_seconds: 90 },
      { instruction: "What does your future self wish you had started sooner?", duration_seconds: 90 },
      { instruction: "Now read that letter to yourself in the present. Let it land.", duration_seconds: 90 },
      { instruction: "Say: 'The future self I imagined is possible. I start building today.'", duration_seconds: 50 },
    ]
  },
  {
    title: "The Discipline Contract",
    category: "focus",
    duration_seconds: 360,
    description: "Make a crystal-clear internal contract with yourself about what you commit to doing regardless of how you feel.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Identify the one thing you keep procrastinating or avoiding in your development.", duration_seconds: 60 },
      { instruction: "Ask honestly: why have I not been doing it consistently? Name the real reason.", duration_seconds: 60 },
      { instruction: "Understand: discipline means doing it even when the reason isn't motivation.", duration_seconds: 60 },
      { instruction: "Write a simple contract in your mind: 'I will do [specific thing] at [specific time] for [specific duration].'", duration_seconds: 70 },
      { instruction: "Sign it mentally. Shake your own hand. You have made a commitment to yourself.", duration_seconds: 60 },
      { instruction: "Say: 'I honour commitments I make to myself. That is who I am.'", duration_seconds: 50 },
    ]
  },
  {
    title: "Craving the Challenge",
    category: "pressure",
    duration_seconds: 360,
    description: "Rewire your relationship with difficulty so that challenges become things you actively seek, not avoid.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Think of something currently challenging you. Feel the discomfort of it honestly.", duration_seconds: 60 },
      { instruction: "Now reframe: this challenge exists because you are at the edge of your current capability.", duration_seconds: 60 },
      { instruction: "The edge is where growth happens. Comfortable never grows.", duration_seconds: 60 },
      { instruction: "Ask: 'What if I leaned INTO this challenge instead of away from it?'", duration_seconds: 70 },
      { instruction: "Imagine finishing this challenge successfully. How does that feel?", duration_seconds: 70 },
      { instruction: "Say: 'I welcome hard things. They are the evidence of my progress.'", duration_seconds: 40 },
    ]
  },

  // ===== DEALING WITH FAILURE =====
  {
    title: "The Failure Inventory",
    category: "recovery",
    duration_seconds: 480,
    description: "Systematically extract the growth hidden inside your biggest failures, building wisdom from pain.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Think of your top 3 biggest failures or disappointments in cricket. List them.", duration_seconds: 70 },
      { instruction: "For failure 1: what is the ONE lesson it gave you that no success could have?", duration_seconds: 80 },
      { instruction: "For failure 2: who did you become because of going through that difficulty?", duration_seconds: 80 },
      { instruction: "For failure 3: what skill or resilience did you build in the aftermath?", duration_seconds: 80 },
      { instruction: "Your failure inventory is actually a wisdom inventory. See that now.", duration_seconds: 70 },
      { instruction: "Say: 'My failures are not the opposite of my story. They are the foundation of it.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Every future failure will now be filtered through this lens.", duration_seconds: 40 },
    ]
  },
  {
    title: "The Bounce-Back Blueprint",
    category: "recovery",
    duration_seconds: 420,
    description: "Design a personal blueprint for how you respond to failure so your recovery is automatic and powerful.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Think about your instinctive pattern after a failure. What do you usually do?", duration_seconds: 70 },
      { instruction: "Is that pattern serving you well? Or does it keep you stuck?", duration_seconds: 60 },
      { instruction: "Design your ideal bounce-back sequence: breathe, acknowledge, extract, act.", duration_seconds: 90 },
      { instruction: "Breathe: physiologically regulate first. Then acknowledge: what happened?", duration_seconds: 70 },
      { instruction: "Extract: what is the single lesson? Act: what is the very next step forward?", duration_seconds: 70 },
      { instruction: "This is now your blueprint. You do not improvise failure recovery — you execute the blueprint.", duration_seconds: 80 },
      { instruction: "Say: 'I have a plan for failure. So failure no longer has power over me.'", duration_seconds: 50 },
      { instruction: "The blueprint is yours. Use it every time.", duration_seconds: 30 },
    ]
  },
  {
    title: "Separating Result from Worth",
    category: "recovery",
    duration_seconds: 360,
    description: "Break the destructive pattern of tying self-worth to performance outcomes.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 55,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "State a poor result you recently had. Say it clearly without drama.", duration_seconds: 40 },
      { instruction: "Now ask: does this result change your character? Your effort? Your intent? No.", duration_seconds: 60 },
      { instruction: "Understand: results measure performance. They do not measure human worth.", duration_seconds: 60 },
      { instruction: "List 3 things about yourself that remain true regardless of any result.", duration_seconds: 80 },
      { instruction: "Your worth is constant. Your results fluctuate. These are separate things.", duration_seconds: 60 },
      { instruction: "Say: 'I am not my score. I am the person who showed up and competed.'", duration_seconds: 60 },
    ]
  },

  // ===== STAYING CALM =====
  {
    title: "The Physiological Sigh",
    category: "pressure",
    duration_seconds: 180,
    description: "The fastest evidence-based breathing technique to instantly reduce physiological stress.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 35,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Inhale fully through your nose until your lungs are almost full.", duration_seconds: 15 },
      { instruction: "Take a second short sniff on top of that first inhale. Completely full now.", duration_seconds: 10 },
      { instruction: "Now exhale slowly and completely through your mouth. Long, full exhale.", duration_seconds: 20 },
      { instruction: "Repeat 3 times. This technique deflates the air sacs and lowers CO2 rapidly.", duration_seconds: 60 },
      { instruction: "You will feel calmer within 30 seconds. This is biological fact.", duration_seconds: 40 },
      { instruction: "Use this any time, anywhere. It requires no preparation and takes under 2 minutes.", duration_seconds: 35 },
    ]
  },
  {
    title: "The Inner Lake",
    category: "match-day-calm",
    duration_seconds: 420,
    description: "A visualisation technique to access deep inner calm regardless of external chaos.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. Imagine a perfectly still mountain lake deep inside your chest.", duration_seconds: 50 },
      { instruction: "The surface is glass-smooth. No wind reaches it. No noise disturbs it.", duration_seconds: 70 },
      { instruction: "External events are happening above the surface — but they don't reach the depths.", duration_seconds: 70 },
      { instruction: "Breathe down into that stillness. Feel your nervous system slow.", duration_seconds: 90 },
      { instruction: "Everything chaotic is on the surface. Your core is always still.", duration_seconds: 70 },
      { instruction: "Say: 'My core is always calm. Nothing outside changes what is inside.'", duration_seconds: 50 },
      { instruction: "Return here whenever the surface world gets too loud. The lake is always here.", duration_seconds: 40 },
      { instruction: "Open your eyes carrying the lake with you.", duration_seconds: 30 },
    ]
  },
  {
    title: "The Five Senses Slow Down",
    category: "match-day-calm",
    duration_seconds: 300,
    description: "Use deliberate sensory attention to slow time, calm the mind and anchor to this exact moment.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 50,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Stop. Wherever you are. Notice one thing you can see. Describe it in detail in your mind.", duration_seconds: 40 },
      { instruction: "Notice one thing you can hear. Really listen to its texture.", duration_seconds: 40 },
      { instruction: "Notice one thing you can physically feel — temperature, surface, weight.", duration_seconds: 40 },
      { instruction: "Take one slow, complete breath. Smell the air. What is in it?", duration_seconds: 40 },
      { instruction: "You are 100% here. Not in the future. Not in the past. Here.", duration_seconds: 60 },
      { instruction: "Anxiety needs the future. Calm lives in the present.", duration_seconds: 50 },
      { instruction: "Say: 'Right here. This exact moment. This is where I choose to be.'", duration_seconds: 30 },
    ]
  },

  // ===== POSITIVE MINDSET =====
  {
    title: "The Possibility Scanner",
    category: "confidence",
    duration_seconds: 360,
    description: "Train your brain to habitually search for possibilities and upside in any situation.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 55,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Think of your current biggest challenge or limitation. State it clearly.", duration_seconds: 40 },
      { instruction: "Ask: 'What would have to be true for this to actually be an advantage?'", duration_seconds: 70 },
      { instruction: "Ask: 'What opportunities has this situation created that didn't exist before?'", duration_seconds: 70 },
      { instruction: "Ask: 'Who have I become in dealing with this that I wouldn't otherwise be?'", duration_seconds: 70 },
      { instruction: "The scanner finds what you programme it to find. Programme it for possibility.", duration_seconds: 60 },
      { instruction: "Say: 'I find the opening in every wall. There is always one.'", duration_seconds: 50 },
    ]
  },
  {
    title: "Morning Positivity Charge",
    category: "confidence",
    duration_seconds: 240,
    description: "A rapid-fire positive start that takes under 4 minutes and sets an optimistic tone for the entire day.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 40,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit up. Take one deep breath in through the nose. Smile deliberately. Yes, really.", duration_seconds: 30 },
      { instruction: "Name 3 things you are genuinely excited about today. Not tomorrow. Today.", duration_seconds: 60 },
      { instruction: "Name one person who adds genuine value to your life. Feel the appreciation.", duration_seconds: 40 },
      { instruction: "Name one capability or trait you are proud of right now.", duration_seconds: 40 },
      { instruction: "Say: 'Today I choose to see what is good, possible, and working. I start here.'", duration_seconds: 50 },
      { instruction: "Stand up. Shoulders back. Begin.", duration_seconds: 20 },
    ]
  },
  {
    title: "The Positive Reframe Machine",
    category: "confidence",
    duration_seconds: 420,
    description: "Train the discipline of consistently reframing negative events into actionable growth perspectives.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Write or think of 3 negative situations from your recent cricket experience.", duration_seconds: 70 },
      { instruction: "Situation 1 — find the silver lining, the hidden lesson, or the strength it built.", duration_seconds: 80 },
      { instruction: "Situation 2 — reframe completely. What does this look like from a different angle?", duration_seconds: 80 },
      { instruction: "Situation 3 — what action does this suggest you take to improve?", duration_seconds: 80 },
      { instruction: "Reframing is not denial. It is choosing the most useful interpretation.", duration_seconds: 60 },
      { instruction: "Say: 'Every event holds information. I use all of it — including the bad.'", duration_seconds: 50 },
    ]
  },
  {
    title: "Believing in Tomorrow",
    category: "confidence",
    duration_seconds: 360,
    description: "Rebuild optimism and hope for what is genuinely possible in your development journey.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 55,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Ask: where do I most want to be in my cricket in 12 months?", duration_seconds: 60 },
      { instruction: "Ask: is this realistically achievable if I show up consistently? Yes.", duration_seconds: 60 },
      { instruction: "Recall one thing you achieved in cricket that once seemed impossible. It happened.", duration_seconds: 70 },
      { instruction: "Tomorrow is genuinely undecided. Your choices today write it.", duration_seconds: 60 },
      { instruction: "Say: 'I believe in what is possible. That belief is the first step toward it.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Act as if you believe it. Because you do.", duration_seconds: 50 },
    ]
  },

  // ===== BOX BREATHING (restored standalone) =====
  {
    title: "4-7-8 Breath Reset",
    category: "match-day-calm",
    duration_seconds: 420,
    description: "The 4-7-8 breathing method — inhale, hold, extended exhale — for rapid activation of the parasympathetic system.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit upright. Place the tip of your tongue gently behind your upper front teeth.", duration_seconds: 20 },
      { instruction: "Exhale completely through your mouth, making a soft whoosh sound.", duration_seconds: 20 },
      { instruction: "Inhale quietly through your nose for a count of 4.", duration_seconds: 30 },
      { instruction: "Hold your breath for a count of 7. Stay relaxed — do not tense.", duration_seconds: 50 },
      { instruction: "Exhale completely through your mouth for a count of 8. Slow. Complete.", duration_seconds: 60 },
      { instruction: "That is one cycle. Repeat 4 complete cycles. Do not rush.", duration_seconds: 180 },
      { instruction: "After the 4th cycle, breathe normally. Notice the profound stillness.", duration_seconds: 40 },
      { instruction: "Say: 'My nervous system responds to my breath. I am in command.'", duration_seconds: 20 },
    ]
  },
  {
    title: "Box Breathing — The Navy Seal Method",
    category: "pressure",
    duration_seconds: 480,
    description: "The tactical breathing technique used by special forces to maintain calm and control under extreme stress.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit or stand straight. Shoulders back. This is a performance breathing technique.", duration_seconds: 20 },
      { instruction: "Exhale fully to begin with empty lungs.", duration_seconds: 20 },
      { instruction: "Inhale through the nose for exactly 4 counts. Fill completely.", duration_seconds: 40 },
      { instruction: "Hold for 4 counts. Lungs full. Stay completely relaxed.", duration_seconds: 40 },
      { instruction: "Exhale for 4 counts. Empty slowly and completely.", duration_seconds: 40 },
      { instruction: "Hold empty for 4 counts. Lungs empty. Still relaxed.", duration_seconds: 40 },
      { instruction: "That is one box. Repeat this cycle 8 complete times.", duration_seconds: 200 },
      { instruction: "Notice: heart rate is slower. Mind is quieter. Hands are steady.", duration_seconds: 50 },
      { instruction: "Say: 'I control my body under pressure. That is a trained skill.'", duration_seconds: 30 },
    ]
  },

  // ===== ADDITIONAL UNIQUE ROUTINES =====
  {
    title: "Processing Disappointment",
    category: "recovery",
    duration_seconds: 480,
    description: "A structured session to fully process deep disappointment and move toward genuine acceptance.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Name the disappointment honestly. No softening. Say exactly what it is.", duration_seconds: 50 },
      { instruction: "Allow yourself 60 full seconds to feel it. Not 10. Not 5. A full minute.", duration_seconds: 60 },
      { instruction: "Ask: was this outcome within my full control? Most of the time — partially.", duration_seconds: 70 },
      { instruction: "Separate: what can I own? What was outside my control? Both are real.", duration_seconds: 70 },
      { instruction: "For what you owned — extract the single most useful lesson.", duration_seconds: 70 },
      { instruction: "Understand: disappointment at this level means you cared. Caring is not a weakness.", duration_seconds: 70 },
      { instruction: "Say: 'I feel this. I learn from this. I do not stop because of this.'", duration_seconds: 50 },
      { instruction: "Breathe three times. Let the emotion settle. Begin again.", duration_seconds: 40 },
    ]
  },
  {
    title: "The Calm Competitor",
    category: "match-day-calm",
    duration_seconds: 360,
    description: "Build the identity of someone who competes with genuine calm, not forced relaxation.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Think of the calmest, most composed performer you have ever seen or admired.", duration_seconds: 60 },
      { instruction: "What is different about them? They are not less invested — they are more anchored.", duration_seconds: 60 },
      { instruction: "Calm does not mean not caring. It means caring from a place of security, not fear.", duration_seconds: 60 },
      { instruction: "Step into that identity: you are a calm competitor. It is who you are.", duration_seconds: 70 },
      { instruction: "See yourself in competition — fully present, clear-eyed, composed.", duration_seconds: 60 },
      { instruction: "Say: 'I compete with calm intensity. That is my identity now.'", duration_seconds: 50 },
    ]
  },
  {
    title: "Motivation Without Mood",
    category: "focus",
    duration_seconds: 360,
    description: "Perform your most important habits on the days you feel least motivated — and build unstoppable consistency.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Check in honestly: do you feel motivated right now? If not — that is perfect.", duration_seconds: 40 },
      { instruction: "Motivation is a weather system. It changes daily. Habits are the building.", duration_seconds: 60 },
      { instruction: "The session you do when you least want to is worth 10 sessions done in peak motivation.", duration_seconds: 70 },
      { instruction: "Identify the ONE thing you committed to today. Just that thing. Not five things.", duration_seconds: 60 },
      { instruction: "Do just the first 2 minutes of it. The rest follows — action creates motivation.", duration_seconds: 80 },
      { instruction: "Say: 'My habits do not depend on how I feel. They depend on who I am.'", duration_seconds: 50 },
    ]
  },
  {
    title: "The Pre-Tournament Mind Lock",
    category: "match-day-calm",
    duration_seconds: 600,
    description: "A comprehensive mental preparation session for the night before a major tournament or selection match.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 80,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Tonight is preparation. Not worry. Make that choice explicitly now.", duration_seconds: 40 },
      { instruction: "Review your strengths slowly. Everything you bring. Every weapon you carry.", duration_seconds: 90 },
      { instruction: "Visualise your first 10 minutes of play tomorrow — calm, purposeful, sharp.", duration_seconds: 90 },
      { instruction: "Accept any result anxiety by breathing into it. 'Yes, this matters. And I can handle it.'", duration_seconds: 80 },
      { instruction: "Do your sleep preparation: 5 slow deep breaths. Body scan. Release everything.", duration_seconds: 120 },
      { instruction: "Remind yourself: the preparation is done. Tomorrow you execute, you don't prepare.", duration_seconds: 80 },
      { instruction: "Say: 'I trust everything I have done to get here. Tomorrow I show it.'", duration_seconds: 60 },
      { instruction: "Sleep. That is the final act of preparation.", duration_seconds: 40 },
    ]
  },
  {
    title: "The Power of No Excuses",
    category: "pressure",
    duration_seconds: 420,
    description: "Develop radical personal responsibility — eliminating excuses and owning outcomes fully.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Think of a recent underperformance. List the excuses your mind offered.", duration_seconds: 70 },
      { instruction: "Now honestly ask: what percentage of this was truly within my control?", duration_seconds: 70 },
      { instruction: "Even if it's only 30% — that 30% is yours. Fully. No excuses for it.", duration_seconds: 70 },
      { instruction: "Understand: taking ownership is not about blame. It is about power. You own what you control.", duration_seconds: 80 },
      { instruction: "The person who makes the fewest excuses grows the fastest.", duration_seconds: 70 },
      { instruction: "Say: 'I own my game completely. No excuses. Full responsibility. Full power.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Act from complete ownership from this point forward.", duration_seconds: 30 },
      { instruction: "Responsibility is freedom.", duration_seconds: 20 },
    ]
  },
  {
    title: "Finding Flow Through Challenge",
    category: "focus",
    duration_seconds: 480,
    description: "Understand the science of flow and deliberately increase challenge to achieve it more consistently.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 75,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Understand: flow happens when challenge exactly matches skill. Too easy = boredom. Too hard = anxiety.", duration_seconds: 60 },
      { instruction: "In your current practice, are you in the boredom zone or the anxiety zone?", duration_seconds: 60 },
      { instruction: "If bored: increase the challenge. Add constraints. Make the drill harder.", duration_seconds: 70 },
      { instruction: "If anxious: break the challenge into smaller steps until one feels achievable.", duration_seconds: 70 },
      { instruction: "The flow channel is thin but incredibly powerful when you're in it.", duration_seconds: 70 },
      { instruction: "Visualise being in that sweet spot — fully absorbed, effortlessly focused.", duration_seconds: 80 },
      { instruction: "Say: 'I design my practice to create flow. Flow is the environment of mastery.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Adjust your next session to hit the flow zone.", duration_seconds: 30 },
    ]
  },
  {
    title: "Staying Positive After Being Dropped",
    category: "recovery",
    duration_seconds: 480,
    description: "Process the psychological pain of being dropped from a team and rebuild your drive constructively.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Being dropped hurts. That pain is valid. Do not skip over it. Feel it for 60 seconds.", duration_seconds: 60 },
      { instruction: "Now separate: the decision was made by others. Your response is made by you.", duration_seconds: 70 },
      { instruction: "Ask: what would make them unable to justify NOT selecting me next time?", duration_seconds: 80 },
      { instruction: "Use the anger, the hurt, the hunger — as fuel for sharper training.", duration_seconds: 70 },
      { instruction: "Many of cricket's greatest performers used being dropped as the beginning of their best chapter.", duration_seconds: 70 },
      { instruction: "Say: 'I use this. I grow from this. I come back better than they imagined.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Train like someone who has something to prove.", duration_seconds: 40 },
      { instruction: "Your story is not over. This is the pivot point.", duration_seconds: 30 },
    ]
  },
  {
    title: "The Pressure Is Information",
    category: "pressure",
    duration_seconds: 360,
    description: "Reframe pressure as useful physiological information, not a threat, to restore clear-headed performance.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Notice the sensations of pressure right now: fast heart, tight chest, dry mouth.", duration_seconds: 50 },
      { instruction: "These are not danger signals. They are preparation signals. Your body is getting ready.", duration_seconds: 60 },
      { instruction: "Athletes who reframe arousal as excitement outperform those who try to calm down.", duration_seconds: 60 },
      { instruction: "Say to yourself: 'I am not anxious. I am excited. The same signal. Better meaning.'", duration_seconds: 60 },
      { instruction: "Channel the physical energy into sharp attention and quick reaction time.", duration_seconds: 60 },
      { instruction: "Say: 'My pressure response is my performance engine. I use it.'", duration_seconds: 70 },
    ]
  },
  {
    title: "Radical Acceptance",
    category: "recovery",
    duration_seconds: 480,
    description: "Practice accepting what you cannot change with complete peace — the foundation of resilient mental health.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Name one thing in your cricket life you are resisting or refusing to accept.", duration_seconds: 60 },
      { instruction: "Observe how much energy that resistance costs you daily. It is significant.", duration_seconds: 70 },
      { instruction: "Acceptance does not mean approval. It means acknowledging what is real.", duration_seconds: 70 },
      { instruction: "Take 5 deep breaths. With each exhale, soften your resistance a little.", duration_seconds: 80 },
      { instruction: "Say the thing out loud, then add: 'And that is the reality. And I can work with reality.'", duration_seconds: 80 },
      { instruction: "The energy freed from resistance becomes available for action.", duration_seconds: 70 },
      { instruction: "Say: 'I accept what is. I act within what is. That is where my power lives.'", duration_seconds: 50 },
      { instruction: "Breathe. Release the resistance. Begin.", duration_seconds: 40 },
    ]
  },
  {
    title: "The Competitor's Code",
    category: "pressure",
    duration_seconds: 420,
    description: "Define and embody the personal code you compete by — the values that hold when everything else breaks down.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Ask: what do I stand for as a competitor? Not what I want — what I stand for.", duration_seconds: 80 },
      { instruction: "Name 3 principles that define how you compete, regardless of score or opponent.", duration_seconds: 90 },
      { instruction: "For example: total effort, relentless honesty, back-your-teammate always.", duration_seconds: 70 },
      { instruction: "These principles are your code. They do not change under pressure.", duration_seconds: 70 },
      { instruction: "When you live your code, the result becomes secondary. You competed as yourself.", duration_seconds: 70 },
      { instruction: "Say: 'I compete by a code I am proud of. Win or lose, I keep my code.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Compete from your code today.", duration_seconds: 30 },
      { instruction: "Character is what you do when no one is watching.", duration_seconds: 30 },
    ]
  },
  {
    title: "Developing Elite Patience",
    category: "focus",
    duration_seconds: 480,
    description: "Build the rare and powerful ability to stay committed and trust the process when results are invisible.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 75,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Identify your most frustrating development plateau right now. Name it clearly.", duration_seconds: 60 },
      { instruction: "Ask: how long have I genuinely, consistently worked on this? Be honest.", duration_seconds: 70 },
      { instruction: "Understand: most meaningful improvements become visible after longer than people expect.", duration_seconds: 80 },
      { instruction: "The days of invisible progress are not wasted — they are the foundation.", duration_seconds: 80 },
      { instruction: "Athletes who outlast their doubt break through. Most quit just before the breakthrough.", duration_seconds: 80 },
      { instruction: "Commit to 30 more days of consistent work before judging progress.", duration_seconds: 70 },
      { instruction: "Say: 'I trust the process. Growth is happening even when I cannot see it.'", duration_seconds: 60 },
      { instruction: "Show up again tomorrow. That is all patience requires.", duration_seconds: 30 },
      { instruction: "The breakthrough is coming. Stay.", duration_seconds: 20 },
    ]
  },
  {
    title: "Positive Pressure Partnership",
    category: "match-day-calm",
    duration_seconds: 360,
    description: "Build a healthy, productive relationship with pressure so it becomes your partner, not your opponent.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 55,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Pressure signals importance. Name 3 things that matter enough to create pressure for you.", duration_seconds: 70 },
      { instruction: "These things are worth caring about. The pressure is appropriate.", duration_seconds: 60 },
      { instruction: "Breathe: treat the pressure like a training partner — useful, not threatening.", duration_seconds: 70 },
      { instruction: "When pressure shows up, say internally: 'Good. This means it matters. Let's go.'", duration_seconds: 70 },
      { instruction: "Athletes who befriend pressure perform better than those who fight it.", duration_seconds: 50 },
      { instruction: "Say: 'Pressure is my training partner. I welcome it. I grow with it.'", duration_seconds: 40 },
    ]
  },
  {
    title: "The Mind Over Fatigue",
    category: "pressure",
    duration_seconds: 420,
    description: "Train your mental capacity to override physical fatigue in the final stages of any performance.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 75,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Understand: the body often hits its limit before the mind does. The mind has reserves.", duration_seconds: 70 },
      { instruction: "In moments of physical tiredness, the brain sends the signal to stop. Question it.", duration_seconds: 70 },
      { instruction: "Recall a time you pushed past tiredness and found extra capacity. You found it.", duration_seconds: 70 },
      { instruction: "That reserve is always there. Your trained mind knows how to access it.", duration_seconds: 70 },
      { instruction: "In late-game fatigue, focus on one ball at a time. Not the innings. Not the day.", duration_seconds: 70 },
      { instruction: "Say: 'My body tires. My mind does not. I have more in reserve always.'", duration_seconds: 60 },
      { instruction: "Find the reserve. Push through.", duration_seconds: 40 },
    ]
  },
  {
    title: "Trusting Instinct",
    category: "focus",
    duration_seconds: 420,
    description: "Rebuild trust in your instinctive decision-making after overthinking or analysis paralysis.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Think of a moment you ignored your instinct and paid the price. It has happened.", duration_seconds: 70 },
      { instruction: "Your instinct is not random. It is the sum of everything you have trained and experienced.", duration_seconds: 70 },
      { instruction: "Overthinking in performance overrides this library of experience. The training suffers.", duration_seconds: 70 },
      { instruction: "Practise: close eyes. Question about your game. First answer you get — trust it.", duration_seconds: 70 },
      { instruction: "Do this 3 times on different aspects of your game. Notice how clear the instinct is.", duration_seconds: 70 },
      { instruction: "Say: 'My training speaks through my instincts. I get out of the way and let it.'", duration_seconds: 70 },
    ]
  },
  {
    title: "The Long View Perspective",
    category: "recovery",
    duration_seconds: 360,
    description: "Zoom out from today's result to reconnect with the bigger arc of your development journey.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 55,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "You are consumed by today's result. Acknowledge it. Now: zoom out.", duration_seconds: 50 },
      { instruction: "Where were you in your cricket 1 year ago? 2 years ago?", duration_seconds: 60 },
      { instruction: "Notice the distance covered. The struggles navigated. The growth achieved.", duration_seconds: 60 },
      { instruction: "Today's result is one data point in a multi-year curve. Not the whole curve.", duration_seconds: 60 },
      { instruction: "Where will you be in 2 years if you continue showing up? Forward. Always forward.", duration_seconds: 70 },
      { instruction: "Say: 'One day does not define my journey. My journey is defined by every day.'", duration_seconds: 60 },
    ]
  },
  {
    title: "Celebrating Others' Success",
    category: "confidence",
    duration_seconds: 300,
    description: "Build genuine generosity of spirit by celebrating teammate success as your own.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 45,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Think of a teammate who recently performed well. Their name, their achievement.", duration_seconds: 50 },
      { instruction: "Feel genuine happiness for them. Not envy — celebration.", duration_seconds: 60 },
      { instruction: "Understand: their success does not reduce yours. Excellence is not a fixed pie.", duration_seconds: 60 },
      { instruction: "Teams of people who celebrate each other outperform those driven by individual ego.", duration_seconds: 60 },
      { instruction: "Say: 'When my teammates win, we all win. I celebrate freely. I inspire by celebrating.'", duration_seconds: 70 },
    ]
  },
  {
    title: "Night Review — Three Good Things",
    category: "recovery",
    duration_seconds: 300,
    description: "The scientifically validated practice of recording three good things each night to rewire optimism.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 50,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Before sleep: set aside 5 minutes. No phone. Just reflection.", duration_seconds: 30 },
      { instruction: "Name the first genuinely good thing from today. Any size. Make it specific.", duration_seconds: 60 },
      { instruction: "Name the second. Something that went well, worked, or brought a moment of satisfaction.", duration_seconds: 60 },
      { instruction: "Name the third. It could be small — a conversation, a shot, a decision made well.", duration_seconds: 60 },
      { instruction: "Done daily, this practice measurably increases optimism and resilience within 2 weeks.", duration_seconds: 50 },
      { instruction: "Say: 'Today had good in it. I found it. Tomorrow will too.'", duration_seconds: 40 },
    ]
  },
  {
    title: "The Pressure Ladder",
    category: "pressure",
    duration_seconds: 540,
    description: "Systematically expose yourself to escalating levels of mental pressure to build a higher tolerance.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 80,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Rung 1: Imagine a low-stakes training session. See yourself performing well.", duration_seconds: 60 },
      { instruction: "Rung 2: Imagine a club game. Stakes are real. See yourself composed.", duration_seconds: 70 },
      { instruction: "Rung 3: Imagine a selector is watching. Feel the added tension. Breathe through it.", duration_seconds: 80 },
      { instruction: "Rung 4: Imagine a major final. Your team needs 15 off last over. Breathe. Execute.", duration_seconds: 90 },
      { instruction: "Rung 5: Imagine the highest-pressure moment you can conceive of. You are still here.", duration_seconds: 90 },
      { instruction: "At every rung, your response was the same: breathe, present, execute.", duration_seconds: 80 },
      { instruction: "Say: 'I have climbed the pressure ladder. The highest rung no longer frightens me.'", duration_seconds: 60 },
      { instruction: "Open your eyes. The ladder has been climbed.", duration_seconds: 20 },
    ]
  },
];