// 30 Additional Universal Mental Training Routines (91-120)
export const EXTRA_MENTAL_ROUTINES = [
  {
    title: "Deep Work Session Primer",
    category: "focus",
    duration_seconds: 540,
    description: "Prime your mind for a session of deep, uninterrupted focused work.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close all tabs, silence your phone. Create a physical and mental clear space.", duration_seconds: 40 },
      { instruction: "Write down one clear outcome you intend to achieve this session.", duration_seconds: 40 },
      { instruction: "Take 5 deep breaths. Let each exhale clear mental noise.", duration_seconds: 60 },
      { instruction: "Visualise yourself in deep focus — absorbed, making real progress.", duration_seconds: 90 },
      { instruction: "Say: 'For the next [X] minutes, nothing exists except this one task.'", duration_seconds: 50 },
      { instruction: "Set a timer. Commit fully. No switching. No checking.", duration_seconds: 60 },
      { instruction: "Begin. You are ready. Deep work creates real results.", duration_seconds: 40 },
      { instruction: "The world will wait. Your focus cannot.", duration_seconds: 30 },
      { instruction: "Go.", duration_seconds: 30 },
    ]
  },
  {
    title: "Under the Microscope",
    category: "pressure",
    duration_seconds: 480,
    description: "Train your mind to thrive when all eyes are on you and the stakes are highest.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 80,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Picture yourself in a high-visibility moment — people watching, judging, waiting.", duration_seconds: 60 },
      { instruction: "Notice any shrinking, hesitation, or self-consciousness. Acknowledge it.", duration_seconds: 60 },
      { instruction: "Reframe: 'These eyes are witnesses to my best work. I perform for myself, not them.'", duration_seconds: 70 },
      { instruction: "Breathe deeply. Expand your chest. Take up space.", duration_seconds: 60 },
      { instruction: "See yourself delivering with calm authority despite every eye on you.", duration_seconds: 90 },
      { instruction: "The spotlight is a gift — it means you matter in this moment.", duration_seconds: 60 },
      { instruction: "Say: 'I perform best when it matters most.'", duration_seconds: 50 },
      { instruction: "Open your eyes. Bring the spotlight. You're ready.", duration_seconds: 30 },
    ]
  },
  {
    title: "The Detox Breath",
    category: "recovery",
    duration_seconds: 360,
    description: "Rapidly flush stress chemicals from your body with rhythmic breathing.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 55,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit upright. Place hands on your belly.", duration_seconds: 20 },
      { instruction: "Inhale through the nose for 4 counts — belly rises.", duration_seconds: 40 },
      { instruction: "Hold for 1 count. Feel fullness.", duration_seconds: 20 },
      { instruction: "Exhale completely through the mouth for 6 counts — belly falls.", duration_seconds: 50 },
      { instruction: "Repeat this cycle 10 times. With each exhale, release tension.", duration_seconds: 120 },
      { instruction: "After the 10th breath, sit silently. Notice the calm in your system.", duration_seconds: 60 },
      { instruction: "Your nervous system has reset. You are calmer than 4 minutes ago.", duration_seconds: 30 },
      { instruction: "Carry this rhythm into your next activity.", duration_seconds: 20 },
    ]
  },
  {
    title: "The Process Film",
    category: "visualization",
    duration_seconds: 540,
    description: "Rehearse not just the result but every micro-step of your best performance.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 75,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. You are about to shoot a mental film.", duration_seconds: 30 },
      { instruction: "Begin at the very start — your preparation, your mindset entering.", duration_seconds: 60 },
      { instruction: "Watch each step in real time. Preparation → warm-up → first action.", duration_seconds: 90 },
      { instruction: "Pay attention to how your body feels, what you hear, what you see.", duration_seconds: 90 },
      { instruction: "A challenge arises. You pause, breathe, and execute the right response.", duration_seconds: 90 },
      { instruction: "The film ends with a strong finish and proud completion.", duration_seconds: 60 },
      { instruction: "Process film creates process mastery. Watch it daily.", duration_seconds: 60 },
      { instruction: "Open your eyes. The film is ready. Now make it real.", duration_seconds: 30 },
      { instruction: "Action follows vision. Always.", duration_seconds: 30 },
    ]
  },
  {
    title: "Silent Minute Protocol",
    category: "focus",
    duration_seconds: 420,
    description: "Build elite concentration through 7 escalating minutes of intentional silence.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit still. No movement. Eyes closed or softly focused.", duration_seconds: 30 },
      { instruction: "Minute 1: Observe your breathing only. No other input.", duration_seconds: 60 },
      { instruction: "Minute 2: Notice sounds in your environment without labelling them.", duration_seconds: 60 },
      { instruction: "Minute 3: Focus on the sensation of your breath entering and leaving.", duration_seconds: 60 },
      { instruction: "Minute 4: Expand awareness to your whole body simultaneously.", duration_seconds: 60 },
      { instruction: "Minute 5: Narrow again to a single point — the tip of your nose.", duration_seconds: 60 },
      { instruction: "Minute 6+: Stay here. Completely. No thought is more important than this moment.", duration_seconds: 80 },
      { instruction: "Open your eyes. That was elite concentration training.", duration_seconds: 30 },
    ]
  },
  {
    title: "The Why Engine",
    category: "confidence",
    duration_seconds: 480,
    description: "Reconnect to the deepest reason you do what you do — and let it fuel everything.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Ask yourself: 'Why do I work at this? What is the real reason?'", duration_seconds: 60 },
      { instruction: "Dig one layer deeper: 'But WHY does that matter to me?'", duration_seconds: 60 },
      { instruction: "Dig one more layer: 'And what does THAT mean for my life?'", duration_seconds: 60 },
      { instruction: "You've found your core purpose. Sit with it. Feel its weight.", duration_seconds: 90 },
      { instruction: "Connect every action today to this root purpose.", duration_seconds: 60 },
      { instruction: "When effort feels pointless — return here. To the why.", duration_seconds: 60 },
      { instruction: "Say: 'Everything I do is in service of this purpose. It is worth it.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Your why is your engine. Turn the key.", duration_seconds: 30 },
    ]
  },
  {
    title: "The Champion's Setback",
    category: "recovery",
    duration_seconds: 480,
    description: "Every great champion has a comeback story. Write yours starting today.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Name the setback you're facing right now honestly.", duration_seconds: 50 },
      { instruction: "Recall a champion you admire who faced something worse and kept going.", duration_seconds: 60 },
      { instruction: "What did they do? How did they respond? They didn't quit.", duration_seconds: 60 },
      { instruction: "Understand: setbacks are selection events. Only those who continue become champions.", duration_seconds: 80 },
      { instruction: "Ask: 'What is the next single step forward from where I stand right now?'", duration_seconds: 80 },
      { instruction: "Breathe. Decide. The comeback starts with the next step.", duration_seconds: 60 },
      { instruction: "Say: 'My story is not over. The best chapter is still being written.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Take that step. The comeback starts now.", duration_seconds: 30 },
    ]
  },
  {
    title: "Box Breathing Method",
    category: "match-day-calm",
    duration_seconds: 480,
    description: "The box breathing method for instant calm under extreme pressure.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit upright. Spine straight. Shoulders relaxed.", duration_seconds: 20 },
      { instruction: "Exhale fully to empty your lungs completely.", duration_seconds: 20 },
      { instruction: "Inhale slowly for 4 counts. Fill completely.", duration_seconds: 40 },
      { instruction: "Hold for 4 counts. Stay relaxed.", duration_seconds: 40 },
      { instruction: "Exhale for 4 counts. Empty slowly.", duration_seconds: 40 },
      { instruction: "Hold for 4 counts. Empty lungs.", duration_seconds: 40 },
      { instruction: "Repeat this 4-4-4-4 cycle 8 times. Each cycle deepens the calm.", duration_seconds: 180 },
      { instruction: "Notice: your heart rate has slowed. Your mind is clear.", duration_seconds: 60 },
      { instruction: "Use this technique any time tension spikes.", duration_seconds: 30 },
    ]
  },
  {
    title: "Abundance Mindset Shift",
    category: "confidence",
    duration_seconds: 420,
    description: "Break free from scarcity thinking and step into a mindset of abundance and possibility.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Identify one scarcity thought you've had recently. ('I don't have enough...')", duration_seconds: 60 },
      { instruction: "Challenge it: 'Is this absolutely true? Am I missing things I already have?'", duration_seconds: 60 },
      { instruction: "List 10 things you DO have that are valuable. Take time. Be genuine.", duration_seconds: 120 },
      { instruction: "Shift: 'There is enough. There is more coming. I am enough.'", duration_seconds: 60 },
      { instruction: "Abundance is first a perspective, then a reality.", duration_seconds: 60 },
      { instruction: "Say: 'I operate from abundance. I share freely. I receive openly.'", duration_seconds: 40 },
      { instruction: "Open your eyes. One abundant action today — give something without expectation.", duration_seconds: 30 },
      { instruction: "Abundance begets abundance.", duration_seconds: 20 },
    ]
  },
  {
    title: "The 2-Minute Warrior",
    category: "pressure",
    duration_seconds: 300,
    description: "A rapid-fire mental reset for any high-pressure moment — anywhere, any time.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 50,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "30 seconds: close your eyes, breathe deeply 3 times. Slow down.", duration_seconds: 40 },
      { instruction: "30 seconds: acknowledge the pressure. 'This is real. I can handle this.'", duration_seconds: 40 },
      { instruction: "30 seconds: recall one moment you handled pressure like a warrior.", duration_seconds: 40 },
      { instruction: "30 seconds: set one clear intention for the next 10 minutes.", duration_seconds: 40 },
      { instruction: "30 seconds: breathe out all tension. Roll your shoulders. Stand tall.", duration_seconds: 40 },
      { instruction: "30 seconds: say your word or phrase. Walk forward. Begin.", duration_seconds: 40 },
      { instruction: "2 minutes. You just changed your state completely.", duration_seconds: 30 },
      { instruction: "Warriors reset fast. Now go.", duration_seconds: 30 },
    ]
  },
  {
    title: "The Grief Permission",
    category: "recovery",
    duration_seconds: 540,
    description: "A compassionate session to process loss, disappointment, or deep sadness.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 80,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Find privacy. Give yourself permission to feel whatever is present.", duration_seconds: 30 },
      { instruction: "Name the loss or disappointment fully. Say it to yourself honestly.", duration_seconds: 60 },
      { instruction: "Feel the weight of it. Don't rush to fix it or move on.", duration_seconds: 90 },
      { instruction: "Grief is the price of love and caring. It means something mattered.", duration_seconds: 60 },
      { instruction: "Breathe slowly. Let your body process what your mind is feeling.", duration_seconds: 90 },
      { instruction: "Ask: 'What has this experience taught me about what I value?'", duration_seconds: 90 },
      { instruction: "Say: 'I allow myself to grieve. I also allow myself to heal in time.'", duration_seconds: 60 },
      { instruction: "You don't have to be okay immediately. Healing is not linear.", duration_seconds: 40 },
      { instruction: "Be gentle with yourself today.", duration_seconds: 30 },
    ]
  },
  {
    title: "10 Years Forward",
    category: "visualization",
    duration_seconds: 540,
    description: "Project yourself a decade into the future and design the life you intend to live.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 75,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. Breathe slowly. Let time stretch.", duration_seconds: 40 },
      { instruction: "You are now 10 years in the future. The best realistic version.", duration_seconds: 60 },
      { instruction: "What does your life look like? Work, relationships, health, fulfilment.", duration_seconds: 90 },
      { instruction: "Who are you? What do people say about you? What have you built?", duration_seconds: 90 },
      { instruction: "Feel the pride and satisfaction of that life fully realised.", duration_seconds: 90 },
      { instruction: "Now look back to today. What did you do differently starting here?", duration_seconds: 90 },
      { instruction: "Commit to one change, starting today, that moves toward that life.", duration_seconds: 60 },
      { instruction: "Open your eyes. The gap between now and then is filled with daily choices.", duration_seconds: 30 },
      { instruction: "Today's choices are tomorrow's results.", duration_seconds: 30 },
    ]
  },
  {
    title: "Owning Your Uniqueness",
    category: "confidence",
    duration_seconds: 420,
    description: "Discover and deeply accept what makes you specifically, powerfully different.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Ask: 'What 3 things do I bring that are distinctly, authentically mine?'", duration_seconds: 70 },
      { instruction: "Don't list generic strengths. Find the ones that feel peculiarly, deeply YOU.", duration_seconds: 70 },
      { instruction: "Recognise: the world doesn't need a copy of anyone else. It needs the real you.", duration_seconds: 70 },
      { instruction: "Think of a time someone appreciated exactly that thing about you.", duration_seconds: 70 },
      { instruction: "The things that make you feel 'different' are often your greatest assets.", duration_seconds: 70 },
      { instruction: "Say: 'I am not meant to fit a mold. I am meant to be unmistakably myself.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Live from that place today. Fully. Without apology.", duration_seconds: 30 },
      { instruction: "The world needs the specific version of you that only you can offer.", duration_seconds: 30 },
    ]
  },
  {
    title: "Competition as Fuel",
    category: "pressure",
    duration_seconds: 420,
    description: "Reframe competition as a gift that reveals your potential and raises your game.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Think of someone you compete with or compare yourself to.", duration_seconds: 50 },
      { instruction: "Reframe: they are not your enemy. They are a signal of what is possible.", duration_seconds: 60 },
      { instruction: "Ask: 'What does their excellence teach me about my own potential?'", duration_seconds: 70 },
      { instruction: "Use their performance as a target, not a threat.", duration_seconds: 60 },
      { instruction: "Breathe in the energy of competition. It sharpens you.", duration_seconds: 60 },
      { instruction: "Your best performances likely came when the competition was highest.", duration_seconds: 60 },
      { instruction: "Say: 'I love competition. It reveals a better version of me.'", duration_seconds: 50 },
      { instruction: "Open your eyes. Raise your game because of them.", duration_seconds: 30 },
      { instruction: "Iron sharpens iron. Be grateful for those who push you.", duration_seconds: 30 },
    ]
  },
  {
    title: "Joy Audit",
    category: "recovery",
    duration_seconds: 360,
    description: "Deliberately identify and amplify the sources of genuine joy in your life.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 55,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Sit quietly. Ask: 'When was the last time I felt genuinely, fully joyful?'", duration_seconds: 60 },
      { instruction: "Recall that moment. Where were you? Who was there? What made it so?", duration_seconds: 70 },
      { instruction: "List 3 activities or people that reliably bring you joy.", duration_seconds: 60 },
      { instruction: "Ask: 'How much space do I give these things in my week?'", duration_seconds: 60 },
      { instruction: "Make one commitment: give one of these more space this week.", duration_seconds: 60 },
      { instruction: "Joy is not a reward for hard work. It is the fuel for it.", duration_seconds: 30 },
      { instruction: "Say: 'I prioritise joy because it makes everything else possible.'", duration_seconds: 30 },
      { instruction: "Schedule the joy. Put it in your calendar.", duration_seconds: 30 },
    ]
  },
  {
    title: "Sensory Performance Blueprint",
    category: "visualization",
    duration_seconds: 600,
    description: "Build a hyper-detailed multi-sensory performance rehearsal for peak readiness.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 85,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Close your eyes. Build your performance environment in total detail.", duration_seconds: 60 },
      { instruction: "What do you SEE? Every colour, shape, distance, light.", duration_seconds: 80 },
      { instruction: "What do you HEAR? Crowd, wind, your own breathing, sounds of the game.", duration_seconds: 80 },
      { instruction: "What do you FEEL? Ground beneath you, equipment in hand, temperature.", duration_seconds: 80 },
      { instruction: "What do you SMELL? Cut grass, sweat, the air. Make it utterly real.", duration_seconds: 60 },
      { instruction: "Now perform. Fully immersed. Every sense active.", duration_seconds: 120 },
      { instruction: "When complete, feel the pride and certainty. Your brain has been there.", duration_seconds: 60 },
      { instruction: "Open your eyes. The blueprint is laid. Execute the build.", duration_seconds: 30 },
      { instruction: "Your body doesn't know the difference. It just prepares.", duration_seconds: 30 },
    ]
  },
  {
    title: "The Imposter Dissolve",
    category: "confidence",
    duration_seconds: 480,
    description: "Dismantle imposter syndrome and claim your place with full authority.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Acknowledge: 'I sometimes feel like I don't deserve to be here.'", duration_seconds: 50 },
      { instruction: "Understand: imposter syndrome is most common among high performers. It's self-awareness, not incompetence.", duration_seconds: 70 },
      { instruction: "List the real, earned reasons you have a place at this table.", duration_seconds: 80 },
      { instruction: "Ask: 'Would someone who truly didn't belong have made it this far?'", duration_seconds: 60 },
      { instruction: "Recognise: you are not faking it. You are growing into it. That's called learning.", duration_seconds: 70 },
      { instruction: "Say: 'I belong here. Not because I'm perfect, but because I've earned this moment.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Act from belonging. Not from fear.", duration_seconds: 40 },
      { instruction: "Imposter syndrome fades with each time you show up anyway.", duration_seconds: 30 },
      { instruction: "Show up. Again. And again.", duration_seconds: 30 },
    ]
  },
  {
    title: "Releasing Expectations",
    category: "pressure",
    duration_seconds: 480,
    description: "Free yourself from the weight of others' expectations and perform for yourself.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Name whose expectations you carry most heavily.", duration_seconds: 50 },
      { instruction: "Ask: are these expectations actually theirs, or ones I've assumed they have?", duration_seconds: 60 },
      { instruction: "Understand: you can only control your effort and intention. Not how it lands.", duration_seconds: 70 },
      { instruction: "Breathe out the weight of trying to meet expectations that aren't yours to carry.", duration_seconds: 80 },
      { instruction: "Define your own standard. Based on your values. Your growth. Your journey.", duration_seconds: 80 },
      { instruction: "When you perform for approval, you lose. When you perform from purpose, you win.", duration_seconds: 80 },
      { instruction: "Say: 'I perform for me. That is the only standard that endures.'", duration_seconds: 50 },
      { instruction: "Open your eyes. Put down the expectations. Pick up your purpose.", duration_seconds: 30 },
    ]
  },
  {
    title: "Pre-Sleep Mental Shutdown",
    category: "recovery",
    duration_seconds: 540,
    description: "Systematically close the mental tabs so your body can enter deep sleep.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Lie down. Phone away. Darkness and quiet if possible.", duration_seconds: 20 },
      { instruction: "Mentally list every 'open tab' — unresolved thoughts, worries, tomorrow's tasks.", duration_seconds: 90 },
      { instruction: "For each one, say: 'That is noted. I'll address it tomorrow. Closing it now.'", duration_seconds: 90 },
      { instruction: "Take 5 slow breaths. Each exhale closes another tab.", duration_seconds: 80 },
      { instruction: "Your to-do list is on pause. The world is okay without you for 8 hours.", duration_seconds: 60 },
      { instruction: "Imagine a slow sunset in your mind — beautiful, gradual, peaceful.", duration_seconds: 90 },
      { instruction: "Feel your body getting heavier with every breath.", duration_seconds: 60 },
      { instruction: "Sleep is the best recovery tool available. Use it fully.", duration_seconds: 30 },
      { instruction: "Let go. Drift. Rest deeply.", duration_seconds: 30 },
    ]
  },
  {
    title: "Breaking the Mental Block",
    category: "visualization",
    duration_seconds: 480,
    description: "Identify and dissolve the mental blocks that stop you from performing at your best.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 80,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Name one thing you consistently struggle to do despite having the skill.", duration_seconds: 60 },
      { instruction: "What is the thought that precedes the block? Find it exactly.", duration_seconds: 70 },
      { instruction: "Visualise the block as a physical object. What shape is it? What colour?", duration_seconds: 60 },
      { instruction: "Now in your mind, begin dismantling it. Slowly. Piece by piece.", duration_seconds: 90 },
      { instruction: "In the space where it was — see yourself executing freely. Cleanly. Naturally.", duration_seconds: 90 },
      { instruction: "Replay this 3 times: block gone, execution perfect, feeling free.", duration_seconds: 90 },
      { instruction: "Say: 'The block is a pattern I created. I can create a new one.'", duration_seconds: 50 },
      { instruction: "Open your eyes. The pattern starts shifting with this session.", duration_seconds: 30 },
      { instruction: "Repetition builds the new neural pathway. Return here daily.", duration_seconds: 30 },
    ]
  },
  {
    title: "Freedom from Judgment",
    category: "confidence",
    duration_seconds: 480,
    description: "Dissolve fear of what others think and step into authentic, fearless action.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Identify a situation where you held back because of fear of being judged.", duration_seconds: 60 },
      { instruction: "Ask: 'What is the worst realistic judgment someone could make of me here?'", duration_seconds: 60 },
      { instruction: "Ask: 'Could I survive that judgment? Could I still grow from it?'", duration_seconds: 60 },
      { instruction: "Realise: most people are too focused on themselves to truly notice or remember.", duration_seconds: 70 },
      { instruction: "The cost of not acting is almost always higher than the cost of judgment.", duration_seconds: 80 },
      { instruction: "Take one bold, authentic action this week you've been avoiding out of judgment-fear.", duration_seconds: 70 },
      { instruction: "Say: 'I will not let imagined judgment imprison my real potential.'", duration_seconds: 50 },
      { instruction: "Open your eyes. Act. Judge later — if at all.", duration_seconds: 30 },
    ]
  },
  {
    title: "Choke-Proof Preparation",
    category: "pressure",
    duration_seconds: 540,
    description: "Train your mind to prevent choking by over-learning automation under pressure.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 80,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Understand: choking happens when conscious attention hijacks automatic processes.", duration_seconds: 60 },
      { instruction: "The solution is to practice so deeply that skill becomes automatic and bulletproof.", duration_seconds: 70 },
      { instruction: "Visualise performing your skill while deliberately thinking about something else.", duration_seconds: 90 },
      { instruction: "See your body executing perfectly while your mind is calm and uninvolved.", duration_seconds: 90 },
      { instruction: "Practise trusting your training rather than controlling execution in real time.", duration_seconds: 90 },
      { instruction: "Use a mantra during performance to occupy the conscious mind and let the body work.", duration_seconds: 90 },
      { instruction: "Say: 'My body knows. I trust the training. I get out of my own way.'", duration_seconds: 60 },
      { instruction: "Open your eyes. Trust is the antidote to choking. Build it daily.", duration_seconds: 30 },
      { instruction: "The training is the protection. Trust it.", duration_seconds: 30 },
    ]
  },
  {
    title: "Life Balance Audit",
    category: "recovery",
    duration_seconds: 540,
    description: "Honestly review the key areas of your life and take action toward genuine balance.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 75,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Rate these areas of your life 1-10: health, relationships, purpose, finances, growth, joy.", duration_seconds: 90 },
      { instruction: "Which area scored lowest? That is where life is sending you a message.", duration_seconds: 60 },
      { instruction: "Ask: What one action this week would move that score from X to X+1?", duration_seconds: 80 },
      { instruction: "Lasting performance requires balance over time. Not just sprints in one lane.", duration_seconds: 80 },
      { instruction: "Commit to one specific action for your lowest area this week.", duration_seconds: 60 },
      { instruction: "Say: 'I am not just a performer. I am a whole person. I invest in all of me.'", duration_seconds: 60 },
      { instruction: "Open your eyes. One action. One area. This week.", duration_seconds: 30 },
      { instruction: "Balance is intentional investment, not perfection.", duration_seconds: 30 },
      { instruction: "Begin.", duration_seconds: 30 },
    ]
  },
  {
    title: "The Vivid Goal Map",
    category: "visualization",
    duration_seconds: 600,
    description: "Transform vague goals into a vivid, emotionally-charged mental map you can act on daily.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 80,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Choose your most important current goal. Make it specific and measurable.", duration_seconds: 60 },
      { instruction: "Close your eyes. See yourself having achieved it fully. What does it look like?", duration_seconds: 90 },
      { instruction: "What do you feel? Pride, relief, joy, freedom? Stay in that feeling.", duration_seconds: 90 },
      { instruction: "Now trace backward: what was the last step before achieving it?", duration_seconds: 70 },
      { instruction: "And the step before that? Build the path backward to today.", duration_seconds: 90 },
      { instruction: "You now have a map from today to the goal. Each step is real and doable.", duration_seconds: 70 },
      { instruction: "Return to the feeling of achieving it. Anchor that emotion.", duration_seconds: 60 },
      { instruction: "Say: 'I know where I'm going. I know the next step. I begin.'", duration_seconds: 50 },
      { instruction: "Open your eyes. What is the very next step? Do it today.", duration_seconds: 30 },
      { instruction: "The map is in you now. Trust it.", duration_seconds: 30 },
    ]
  },
  {
    title: "Morning Clarity Protocol",
    category: "focus",
    duration_seconds: 420,
    description: "Start every day with complete mental clarity on your priorities and inner state.",
    difficulty: "beginner",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Before checking anything, sit quietly for 2 minutes. Just exist.", duration_seconds: 60 },
      { instruction: "Ask: 'What is the single most important thing I need to do today?'", duration_seconds: 60 },
      { instruction: "Ask: 'How do I want to show up today? What kind of person will I be?'", duration_seconds: 60 },
      { instruction: "Set a 3-word intention for the day: e.g. calm, focused, generous.", duration_seconds: 50 },
      { instruction: "Take 5 deep, slow breaths. Each one sets the tone for the day.", duration_seconds: 70 },
      { instruction: "Say: 'Today I begin with clarity, not chaos. I lead my day.'", duration_seconds: 50 },
      { instruction: "Open your eyes. Do the important thing first. Before anything else.", duration_seconds: 40 },
      { instruction: "The morning sets the tone for everything that follows. Own it.", duration_seconds: 30 },
    ]
  },
  {
    title: "Vocal and Physical Presence",
    category: "confidence",
    duration_seconds: 360,
    description: "Train your voice, posture and presence so that you command respect before you speak.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 60,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Stand up. Take up full space. Feet wide. Back straight. Chin level.", duration_seconds: 40 },
      { instruction: "Take 5 deep, slow breaths into your chest and belly.", duration_seconds: 60 },
      { instruction: "Speak your name out loud, slowly, with full conviction. Own it.", duration_seconds: 30 },
      { instruction: "Speak one sentence about your goal with full voice, full volume, full confidence.", duration_seconds: 40 },
      { instruction: "Notice how your body feels when you inhabit it fully. This is available always.", duration_seconds: 60 },
      { instruction: "Presence is not loud. It is grounded, unhurried, unconditional.", duration_seconds: 60 },
      { instruction: "Say: 'I take up the space I deserve. Fully. Without apology.'", duration_seconds: 40 },
      { instruction: "Walk confidently into your next interaction. Presence first.", duration_seconds: 30 },
    ]
  },
  {
    title: "Embrace the Discomfort",
    category: "pressure",
    duration_seconds: 420,
    description: "Learn to sit with discomfort instead of escaping it — and find growth on the other side.",
    difficulty: "advanced",
    is_premium: false,
    xp_value: 70,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Identify a discomfort you've been avoiding. Physical, emotional, or situational.", duration_seconds: 50 },
      { instruction: "Deliberately sit with the discomfort now. Don't escape it. Just breathe into it.", duration_seconds: 70 },
      { instruction: "Notice: discomfort rarely kills. It is survivable. You are surviving it right now.", duration_seconds: 70 },
      { instruction: "Ask: 'What becomes available to me on the other side of this discomfort?'", duration_seconds: 70 },
      { instruction: "Every great outcome lives beyond a discomfort you had to endure.", duration_seconds: 70 },
      { instruction: "Say: 'I lean into discomfort. It is the gateway to my growth.'", duration_seconds: 50 },
      { instruction: "Breathe deeply. Stay present. The discomfort will pass. Your strength will remain.", duration_seconds: 70 },
      { instruction: "Open your eyes. Face one uncomfortable thing today. On purpose.", duration_seconds: 30 },
      { instruction: "Growth lives outside comfort. Choose growth.", duration_seconds: 30 },
    ]
  },
  {
    title: "Closing the Loop",
    category: "recovery",
    duration_seconds: 420,
    description: "Find mental closure on unfinished emotional business so it stops draining your energy.",
    difficulty: "intermediate",
    is_premium: false,
    xp_value: 65,
    calming_sound: "https://cdn.pixabay.com/audio/2022/03/10/audio_c8c8e1c1ab.mp3",
    steps: [
      { instruction: "Name one thing from the past that still lives rent-free in your mind.", duration_seconds: 50 },
      { instruction: "Write it out mentally: what happened, what you feel, what you wish had been different.", duration_seconds: 80 },
      { instruction: "Acknowledge what was in your control, and what wasn't. Be honest.", duration_seconds: 70 },
      { instruction: "If action is still possible — plan it. If not — consciously choose to release it.", duration_seconds: 80 },
      { instruction: "Say: 'This chapter is complete. I learned from it. I'm releasing it.'", duration_seconds: 60 },
      { instruction: "Breathe. Feel the space that opens when you let something go.", duration_seconds: 60 },
      { instruction: "Open loops consume your mental RAM. Close them deliberately.", duration_seconds: 40 },
      { instruction: "Open your eyes. A loop is closed. Energy is freed.", duration_seconds: 30 },
    ]
  },
];